### ISSUE TITLE
ObjectPool机制与bthread 内存相关问题

### ISSUE THREAD

**Issue by feifeiiong** [apache/brpc#1027]
**Describe the bug (描述bug)**
日前在做压测时发现，在高并发的情况下，大量bthread被创建，bthread_stack_count迅速增长，在压测结束后，bthread_stack_count 未释放，同样内存也未释放。查看代码发现与ObjectPool机制可能有关。想知道这一块的内存释放的时机是如何确定的？是否ObjectPool申请的内存不会释放？

**To Reproduce (复现方法)**
高并发情况下的压测，必现。

**Expected behavior (期望行为)**
内存释放的机制。

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
内存只会复用，不会释放。

**Comment by feifeiiong** [comment]
感谢解答！如果考虑线上出现峰值后，内存未释放的情况，想问下大佬对这种情况有没有什么好的建议？想要限制的话似乎只有限制服务本身的最大并发数？

**Comment by jamesge** [comment]
对

**Comment by feifeiiong** [comment]
是否有计划对对象池的释放机制有改动呢，或者说有没有一些改动思路可以提供，针对内存释放的问题？
