### ISSUE TITLE
cpu profiler功能异常

### ISSUE THREAD

**Issue by scottzzq** [apache/brpc#1039]
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

日志报错：
E0206 11:20:57.427878 27576 brpc/builtin/pprof_service.cpp:302] Fail to popen `nm -C -p /usr/lib64/libm-2.17.so'

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
