### ISSUE TITLE
编译出错：make: *** [protoc-gen-mcpack] 错误 1

### ISSUE THREAD

**Issue by pklim101** [apache/brpc#1043]
**Describe the bug (描述bug)**
> Linking protoc-gen-mcpack
g++ -o protoc-gen-mcpack -I./src -I/usr/include/ -L/usr/lib64 -std=c++0x -Xlinker "-(" src/idl_options.pb.cc src/mcpack2pb/generator.o libbrpc.a -Wl,-Bstatic  -Wl,-Bdynamic -Xlinker "-)" -lpthread -lssl -lcrypto -ldl -lz -lrt -lgflags -lprotobuf -lleveldb -lprotoc
libbrpc.a(file_path.o): In function `_M_check':
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
libbrpc.a(string_util.o): In function `_M_check':
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
libbrpc.a(string_util.o):/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
libbrpc.a(task_group.o): In function `init':
/home/tom/local/incubator-brpc/./src/bthread/work_stealing_queue.h:60: undefined reference to `__cxa_throw_bad_array_new_length'
libbrpc.a(string16.o): In function `std::basic_string<unsigned short, butil::string16_char_traits, std::allocator<unsigned short> >::_M_check(unsigned long, char const*) const':
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
libbrpc.a(string16.o): In function `std::basic_string<unsigned short, butil::string16_char_traits, std::allocator<unsigned short> >::at(unsigned long) const':
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:878: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
libbrpc.a(string16.o): In function `_M_check':
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
libbrpc.a(string16.o):/usr/local/gcc4.9.2/include/c++/4.9.2/bits/basic_string.h:324: more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
collect2: 错误：ld 返回 1
make: *** [protoc-gen-mcpack] 错误 1

**To Reproduce (复现方法)**
编译：make后就报如上错误。

**Expected behavior (期望行为)**
不报错。

**Versions (各种版本)**
OS: CentOS release 6.2 (Final)
Compiler: g++ (GCC) 4.9.2
brpc: 0.9.7
protobuf: 2.4.1-1.el6.x86_64

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
