### ISSUE TITLE
GET请求丢失uri部分

### ISSUE THREAD

**Issue by pklim101** [apache/brpc#1051]
在ParallelChannel里，发送HTTP请求的时候，抓包发现uri并没有发送过去。

初步看好像是ApplyClientSettings(settings)这个函数里没设置URI，所以在发送sub channel的时候，在ParallelChannel里设置的很多header信息丢失了。

代码如下：
brpc::Controller cntl;
cntl.http_request().uri() = "www.test.com/abc?a=1"
cntl.http_request().set_content_type("text/plain");
pchan->CallMethod(NULL, &cntl, &request, &response, NULL);

抓包的header部分如下：
GET / HTTP/1.1        =========>这里path部分应该是：/abc而不是/
Host: www.test.com:80
Content-Type: application/json   ======>这里应该是text/plain
log-id: 100
Accept: */*
User-Agent: brpc/1.0 curl/7.0

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
