### ISSUE TITLE
latency 数值不断更新，但是latency_9999 没有变化

### ISSUE THREAD

**Issue by Pangm** [apache/brpc#1071]
**Describe the bug (描述bug)**
latency 数值不断更新，但是latency_9999 没有变化

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
latency_9999 同步更新

**Versions (各种版本)**
OS: "Linux version 3.10.0_3-0-0-32 (root@cp01-cos-dev01.cp01.baidu.com) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #2 SMP Sun Feb 9 09:13:38 CST 2020"
Compiler: gcc_version : "8.2.0"
brpc: rpc_revision : "62fc6c28a64a18e49a16c6fe25f658191cb05a4c"
protobuf:

**Additional context/screenshots (更多上下文/截图)**

![image](https://user-images.githubusercontent.com/2490578/77404369-96ec4f00-6dec-11ea-8d4b-22c72edc22a2.png)

**Comment by TheFinalHydra** [comment]
我也遇到了这个问题，而且实际上，通过promethus格式暴露出来的lateny_80/90/99/9999/cdf也同样没有值，只有count, ops, latency和max_latency有值。

之前的旧版本是好的，更新到了今年6月份的某一个commit之后，就不可以了，请问是什么地方修改了吗？

另外我看到[`latency_recorder.cpp的137行`](https://github.com/apache/incubator-brpc/blob/master/src/bvar/latency_recorder.cpp#L137)里面有这样一段话

> // NOTE: We don't show 99.99% since it's often significantly larger than
> // other values and make other curves on the plotted graph small and
> // hard to read.

这里不太明白，为什么这里要直接把99.99%去掉呢？如果用户觉得指标不需要，完全应该由用户在监控上直接不抓取这一项的值，或者读取`/brpc_metrics`的时候直接跳过这一项就好了，而不是由brpc这个框架级别的东西要这个值写死成一个假的值。这样bvar里面既暴露了9999，但却一直是一个假的值，会容易让人迷惑

**Comment by TheFinalHydra** [comment]
我在`latency_percentil`里面手动获取`cb->get_number(0.9999)`有时候是可以获取到值的，基本是若干个0后，就有几个值

下面是一部分数值
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 1
> ratio = 0.9999, val = 1
> ratio = 0.9999, val = 2
> ratio = 0.9999, val = 1
> ratio = 0.9999, val = 3
> ratio = 0.9999, val = 20673
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 14836
> .....
> ratio = 0.9999, val = 0
> ratio = 0.9999, val = 757
> ratio = 0.9999, val = 15320
> ratio = 0.9999, val = 61
> ratio = 0.9999, val = 1152
> ratio = 0.9999, val = 2687

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
