### ISSUE TITLE
使用LatencyRecorder无法统计出qps的问题

### ISSUE THREAD

**Issue by zhangls** [apache/brpc#1083]
看了下计算qps的demo，我个人理解的是调用了LatencyRecorder中重载的<<方法，就可以算出qps。但是用在实际服务中，计算出的qps一直是0，计算qps使用的_q队列长度一直是1，是我使用的方法存在什么问题吗？万分感谢解答

**Comment by gydong** [comment]
> 计算qps使用的_q队列  
这是什么？建议贴下你的代码和效果图

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
