### ISSUE TITLE
Fail to write to _fake_socket, Invalid argument有人遇到过吗？

### ISSUE THREAD

**Issue by 13299022010** [apache/brpc#1092]
**stream模式下传输文件，报错W0420 21:01:29.515434  1297 src/brpc/stream.cpp:282] Fail to write to _fake_socket, Invalid argument
F0420 21:01:29.516066  1297 client.cpp:231] Check failed: 0 == brpc::StreamWrite(stream, msg1) (0 vs 22).**

**Comment by moyucd** [comment]
有相同问题

**Comment by ehds** [comment]
可能 stream 的另一端已经close了。
https://github.com/apache/brpc/blob/d6df0f156ad6bd8ec6722a3c3c15691607bb62e7/src/brpc/stream.cpp#L295-L297
