### ISSUE TITLE
Stream 的on_received_messages怎么进行错误处理？

### ISSUE THREAD

**Issue by cstarc** [apache/brpc#1097]
请问Stream 的on_received_messages 返回非0值，这种异常是怎么处理？ 客户端怎么感知到?

**Comment by zhijunfu** [comment]
这个是需要用户实现的callback，返回值是自己填的啊。如果是连接断了的话，应该是on_error会被调用

**Comment by cstarc** [comment]
> 这个是需要用户实现的callback，返回值是自己填的啊。如果是连接断了的话，应该是on_error会被调用

返回值自己填的清楚，但这个是返回哪里？ 客户端怎么通过函数或变量获取这个返回值？
找了下代码on_received_messages 没有处理返回值
```
class MessageBatcher {
    void flush() {
        if (_size > 0 && _s->_options.handler != NULL) {
            _s->_options.handler->on_received_messages(
                    _s->id(), _storage, _size);
        }
        for (size_t i = 0; i < _size; ++i) {
            delete _storage[i];
        }
        _size = 0;
    }
```

**Comment by zhijunfu** [comment]
上边贴的代码，brpc里面是没有这个函数的处理的

**Comment by cstarc** [comment]
@zhijunfu  那现在brpc 还不支持on_received_message返回错误? 即使返回了也不处理?

**Comment by zhijunfu** [comment]
> @zhijunfu 那现在brpc 还不支持on_received_message返回错误? 即使返回了也不处理?

这个应该不会支持的。一般错误处理逻辑是说上层处理下层的错误，比如说断连的错误brpc会通过on_closed 告诉上层。下层不会处理上层的错误的，你的函数返回个错误，brpc也不知道该怎么处理啊。。

**Comment by cstarc** [comment]
不是让brpc处理，是让brpc可以返回给客户端，这个函数返回类型就是int，如果返回了错误又不能处理，为什么不是void？

**Comment by chenzhangyi** [comment]
stream目前对照的语义是和tcp连接类似的(除了有消息边界外). 这个接口用int在当时的设计上是也是为了能够合适的方式传递用户态错误而不需要改接口。
你可以看下目前的场景直接Close是否能满足需求，这个应该是目前唯一的可以提前结束的手段。

**Comment by zhijunfu** [comment]
btw：StreamClose这里有个坑，因为client端上层传给brpc的是handler的指针，有可能上层析构了on_closed还会被调用，有可能访问到已经析构了的数据，这块需要处理一下

**Comment by cstarc** [comment]
@chenzhangyi  close 是直接调用streamclose？可以在receive端调用？

**Comment by describe2022** [comment]
> btw：StreamClose这里有个坑，因为client端上层传给brpc的是handler的指针，有可能上层析构了on_closed还会被调用，有可能访问到已经析构了的数据，这块需要处理一下

请问一下这块怎么处理呢？现在只要调用StreamClose，如您说的handler被紧接着析构掉的话就会发生段错误。

**Comment by hanyueming001** [comment]
> > btw：StreamClose这里有个坑，因为client端上层传给brpc的是handler的指针，有可能上层析构了on_closed还会被调用，有可能访问到已经析构了的数据，这块需要处理一下
> 
> 请问一下这块怎么处理呢？现在只要调用StreamClose，如您说的handler被紧接着析构掉的话就会发生段错误。

请问这个问题有解决办法了吗？现在也同样遇到了这个问题，求大佬帮忙解答下
