### ISSUE TITLE
bthread

### ISSUE THREAD

**Issue by vanehu** [apache/brpc#1099]
我看文档，感觉bthread 和boost.fiber 差不多
另外bthread用了之后再使用线程的mutex的时候死锁，这个多人开发的时候不太好操作了。没办法每个人都知道哪些函数需要bthread的mutex,哪些是需要thread mutex

**Comment by GOGOYAO** [comment]
> 我看文档，感觉bthread 和boost.fiber 差不多
> 另外bthread用了之后再使用线程的mutex的时候死锁，这个多人开发的时候不太好操作了。没办法每个人都知道哪些函数需要bthread的mutex,哪些是需要thread mutex

+1。那个bthread用std::mutex导致死锁的问题，感觉很蛋疼。

**Comment by jamesge** [comment]
> bthread用了之后再使用线程的mutex的时候死锁
临界区内有做阻塞或等待另一个资源的操作么？

**Comment by vanehu** [comment]
例如，业务需要请求其他的数据，但是这个数据是另外的人写的 他可不管你用什么锁 直接mutex 就上去了

**Comment by billowqiu** [comment]
> > 我看文档，感觉bthread 和boost.fiber 差不多
> > 另外bthread用了之后再使用线程的mutex的时候死锁，这个多人开发的时候不太好操作了。没办法每个人都知道哪些函数需要bthread的mutex,哪些是需要thread mutex
> 
> +1。那个bthread用std::mutex导致死锁的问题，感觉很蛋疼。

目前没细看实现，文档里面有这方面的说明么？

**Comment by ming-relax** [comment]
【那个bthread用std::mutex导致死锁的问题】请问这个是什么问题，现有的 issue 上也没有搜到

**Comment by GOGOYAO** [comment]
> 【那个bthread用std::mutex导致死锁的问题】请问这个是什么问题，现有的 issue 上也没有搜到

![image](https://user-images.githubusercontent.com/18675094/90017948-cee22900-dcde-11ea-8bcd-c02005b0421b.png)

**Comment by GOGOYAO** [comment]
> 【那个bthread用std::mutex导致死锁的问题】请问这个是什么问题，现有的 issue 上也没有搜到

https://github.com/apache/incubator-brpc/blob/master/docs/cn/bthread.md
“但这个机制更多是为了规避在一些极端情况下的死锁, 比如所有的用户代码都lock在一个pthread mutex上, 并且这个mutex需要在某个RPC回调中unlock, 如果所有的worker都被阻塞, 那么就没有线程来处理RPC回调了, 整个程序就死锁了. 虽然绝大部分的RPC实现都有这个潜在问题, 但实际出现频率似乎很低, 只要养成不在锁内做RPC的好习惯, 这是完全可以规避的.”
