### ISSUE TITLE
brpc 0.9.7 +braft 压力测试下，内存持续增长问题

### ISSUE THREAD

**Issue by tojoyccnu** [apache/brpc#1105]
**Describe the bug (描述bug)**
测试业务，braft  example/counter 示例。
压力测试工具： rpc_press

/run_press.sh --dummy_port=18882 --server_port=8100 --req_method="example.CounterService.fetch_add" --req_json='{"value": 1}' --thread_num=10 --qps=100000
/run_press.sh --dummy_port=18881 --server_port=8100 --req_method="example.CounterService.get" --req_json='{}' --thread_num=10 --qps=200000

内存使用情况，从初始 使用不到50M ， 到后续 2G， 且持续增长中。vars 中相关iobuf_block 在正常值范围。

**Comment by jamesge** [comment]
哪个模块的内存？

**Comment by tojoyccnu** [comment]
![counter_1](https://user-images.githubusercontent.com/12874335/80562445-5e0e4e00-8a1a-11ea-8613-ec752f82614a.jpg)
![counter_2](https://user-images.githubusercontent.com/12874335/80562451-5fd81180-8a1a-11ea-98dc-e3b5a08c4375.jpg)
![counter_3](https://user-images.githubusercontent.com/12874335/80562453-61093e80-8a1a-11ea-8a42-1ded3d25bfcb.jpg)

**Comment by tojoyccnu** [comment]
改成两个rpc_press 都做example.CounterService.get 查询，没有 braft 状态机 apply 。
![counter_4](https://user-images.githubusercontent.com/12874335/80563662-43d66f00-8a1e-11ea-9fc7-bd095beb82e6.jpg)

**Comment by chenzhangyi** [comment]
用了tcmalloc没？

**Comment by tojoyccnu** [comment]
> 用了tcmalloc没？

用了的。

![counter_5](https://user-images.githubusercontent.com/12874335/80564366-35895280-8a20-11ea-9921-b0045131448c.jpg)

**Comment by tojoyccnu** [comment]
![counter_5](https://user-images.githubusercontent.com/12874335/80564421-58b40200-8a20-11ea-95eb-78ea2264ff1e.jpg)

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
