### ISSUE TITLE
BVar keeps logging error

### ISSUE THREAD

**Issue by chunyang-wen** [apache/brpc#1113]
**Describe the bug (描述bug)**
程序启动后，一直频繁的输出如下 WARNINING 日志。是解析 "/proc/self/stat" 失败。但是单独去解析对应 pid 的 stat 文件是可以解析成功的。（把 bvar 对应代码拿出来去读取对应 pid 文件）

> bvar/default_variables.cpp:93] Fail to fscanf: Success

**To Reproduce (复现方法)**

没有一个 minimal 的 case 来复现

**Expected behavior (期望行为)**
正确解析

**Versions (各种版本)**
OS: 
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

bvar/default_variables.cpp:93] Fail to fscanf: Success

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
