### ISSUE TITLE
默认thrift编译问题

### ISSUE THREAD

**Issue by songlong** [apache/brpc#1122]
**Describe the bug (描述bug)**
example/echo_c++
编译失败：
/usr/bin/ld: warning: libssl.so.10, needed by /usr/lib/../lib64/libthrift.so, may conflict with libssl.so.1.0.0
/usr/bin/ld: warning: libssl.so.10, needed by /usr/lib/../lib64/libthrift.so, may conflict with libssl.so.1.0.0
/usr/bin/ld: warning: libcrypto.so.10, needed by /usr/lib/../lib64/libthrift.so, may conflict with libcrypto.so.1.0.0
/usr/bin/ld: warning: libcrypto.so.10, needed by /usr/lib/../lib64/libthrift.so, may conflict with libcrypto.so.1.0.0
/usr/lib/../lib64/libthriftnb.so: undefined reference to `evhttp_set_cb'
/usr/lib/../lib64/libthriftnb.so: undefined reference to `evhttp_bind_socket'
/usr/lib/../lib64/libthriftnb.so: undefined reference to `evbuffer_add'
/usr/lib/../lib64/libthriftnb.so: undefined reference to `evbuffer_pullup'
/usr/lib/../lib64/libthriftnb.so: undefined reference to `evhttp_send_reply'
/usr/lib/../lib64/libthriftnb.so: undefined reference to `evhttp_make_reques

**To Reproduce (复现方法)**
example/echo_c++

**Expected behavior (期望行为)**
编译不通过

**Versions (各种版本)**
OS: cent0s6.2
Compiler: gcc-4.8.5 cmake3.15
brpc: 0.9.7
protobuf: 2.6

**Additional context/screenshots (更多上下文/截图)**

**Comment by wshilaji** [comment]
大佬你解决了吗。我也遇到这个问题了

**Comment by yshiyuan** [comment]
使用libthriftnb的情况下需要链接libevent，可以检查下是否链接了libevent

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
