### ISSUE TITLE
brpc server用户代码里面使用hdfslib的api服务core掉

### ISSUE THREAD

**Issue by hpsdy** [apache/brpc#1123]
在demo里，std::thread使用hdfsBuilderConnect、hdfsExists正常。
在brpc服务中，直接在init里初始化fs=hdfsBuilderConnect，调用fs->hdfsExists，服务正常。
在brpc服务中，init里初始化fs=hdfsBuilderConnect，发起请求，调用fs->hdfsExists，服务core掉。

怀疑是bthread的stack和jar包里面不兼容问题，使用usercode_in_pthread，注释掉bthread，也不行。但是报错已经变了。

这种情况有啥思路么？

**Comment by chenzhangyi** [comment]
这个是已知问题，bthread里面没法跑jni代码.
