### ISSUE TITLE
Contention profiler 用不了？

### ISSUE THREAD

**Issue by zhijunfu** [apache/brpc#1125]
**Describe the bug (描述bug)**

Contention profiler 用不了

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

contention profiling 结果能够通过内置http服务的contention页面展示

**Versions (各种版本)**
OS: linux centos 7
Compiler:
brpc: 最新master和 0.9.7都试过
protobuf:

**Additional context/screenshots (更多上下文/截图)**

contention页面显示如下：

[20200527.125758.contention]
Using local file ./bazel-bin/asynchronous_echo_c++_server.
Using local file ./rpc_data/profiling/ff9a9eed9e62f8e0e337d6234c5692ad/20200527.125758.contention.

![image](https://user-images.githubusercontent.com/37800433/82979895-c270fd00-a01a-11ea-8d75-4b78f6849025.png)

**Comment by jamesge** [comment]
有流量吗？

**Comment by zhijunfu** [comment]
> 有流量吗？

有的。生成的contention文件也比较小，只有十几k，感觉是没数据。这种该怎么排查呢？

**Comment by jamesge** [comment]
> > 有流量吗？
> 
> 有的。生成的contention文件也比较小，只有十几k，感觉是没数据。这种该怎么排查呢？

那可能就是没有contention

**Comment by kof02guy** [comment]
> > > 有流量吗？
> > 
> > 
> > 有的。生成的contention文件也比较小，只有十几k，感觉是没数据。这种该怎么排查呢？
> 
> 那可能就是没有contention

使用这个依赖libprofile么？我这里也用不了，不过网页上错误如下：
Fail to execute `perl ./rpc_data/profiling/pprof.pl --dot ./ts ./rpc_data/profiling/180f54b113b35acab63e2f8d1cd0d898/20200617.181201.contention 2>&1 ', No child processes

生成的.contention文件大约2MB左右

**Comment by zhijunfu** [comment]
不依赖的，你这个错误可能是 代码里面ignore了SIGTERM，我之前遇到过同样的问题。
 
> 使用这个依赖libprofile么？我这里也用不了，不过网页上错误如下：
> Fail to execute `perl ./rpc_data/profiling/pprof.pl --dot ./ts ./rpc_data/profiling/180f54b113b35acab63e2f8d1cd0d898/20200617.181201.contention 2>&1 ', No child processes
> 
> 生成的.contention文件大约2MB左右

**Comment by kof02guy** [comment]
> 不依赖的，你这个错误可能是 代码里面ignore了SIGTERM，我之前遇到过同样的问题。
> 
> > 使用这个依赖libprofile么？我这里也用不了，不过网页上错误如下：
> > Fail to execute `perl ./rpc_data/profiling/pprof.pl --dot ./ts ./rpc_data/profiling/180f54b113b35acab63e2f8d1cd0d898/20200617.181201.contention 2>&1 ', No child processes
> > 生成的.contention文件大约2MB左右

SIGTERM不是正常的退出SIGNAL么，这个一般都会被截获然后实现优雅退出的逻辑吧，我们也是的。我这边看到生成的contention文件里面有内容，里面还有各个数字以及相应的内存地址，addr2line是可以正常转换为具体的代码行数的，但是不是图，所以没法看
我理解应该是在转换为图的时候出了什么问题

**Comment by zhijunfu** [comment]
那可能还不太一样，我这边遇到过两个问题：
>  一个是C++的程序，是因为ignore了SIGTERM，错误现象和你的一样，后来解决掉了；
>  另外一个是java里面load C++的so，然后报了这个issue里面的错误，还没有找到原因

**Comment by kof02guy** [comment]
> 那可能还不太一样，我这边遇到过两个问题：
> 
> > 一个是C++的程序，是因为ignore了SIGTERM，错误现象和你的一样，后来解决掉了；
> > 另外一个是java里面load C++的so，然后报了这个issue里面的错误，还没有找到原因

我这边没有用到java。c++的话你说的ignore了sigterm是值没有自己处理sigterm吗？

**Comment by zhijunfu** [comment]
> > 那可能还不太一样，我这边遇到过两个问题：
> > > 一个是C++的程序，是因为ignore了SIGTERM，错误现象和你的一样，后来解决掉了；
> > > 另外一个是java里面load C++的so，然后报了这个issue里面的错误，还没有找到原因
> 
> 我这边没有用到java。c++的话你说的ignore了sigterm是值没有自己处理sigterm吗？

oops，我说错了，是ignore了SIG_CHLD，就是设置了SIG_IGN，因为现在brpc用的popen和子进程交互，如果ignore了这个signal的话，pclose的时候会失败

**Comment by dongdongwcpp** [comment]
@kof02guy 后来解决了吗，我也有遇到，不过我是用dummy server

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
