### ISSUE TITLE
fail to build example `echo_c++` and report `Undefined symbols for architecture x86_64:`

### ISSUE THREAD

**Issue by ruoshui1314** [apache/brpc#1159]
**Describe the bug (描述bug)**
1.build brpc successfully
2.fail to build echo_c++ in example.details as follow:

31 warnings generated.
[ 25%] Linking CXX executable echo_server
Undefined symbols for architecture x86_64:
  "_BN_get_rfc2409_prime_1024", referenced from:
      brpc::SSLDHInit() in libbrpc.a(ssl_helper.cpp.o)
      brpc::policy::DHWrapper::do_initialize() in libbrpc.a(dh.cpp.o)
  "_BN_get_rfc3526_prime_2048", referenced from:
      brpc::SSLDHInit() in libbrpc.a(ssl_helper.cpp.o)
  "_BN_get_rfc3526_prime_4096", referenced from:
      brpc::SSLDHInit() in libbrpc.a(ssl_helper.cpp.o)
  "_BN_get_rfc3526_prime_8192", referenced from:
      brpc::SSLDHInit() in libbrpc.a(ssl_helper.cpp.o)
  "_DH_get0_key", referenced from:
      brpc::policy::DHWrapper::initialize(bool) in libbrpc.a(dh.cpp.o)
      brpc::policy::DHWrapper::copy_public_key(char*, int*) const in libbrpc.a(dh.cpp.o)
  "_DH_set0_pqg", referenced from:
      brpc::SSLDHInit() in libbrpc.a(ssl_helper.cpp.o)

**To Reproduce (复现方法)**
------------
environment is MAC OS 10.14.5
1. build dependencies such as leveldb, glog in local
2. move ssl headers and library to local directory
3. build brpc successfully

```shell

cd incubator-brpc-0.9.7
mkdir build
cd build
cmake -DCMAKE_INCLUDE_PATH="/xxx/local/include" -DCMAKE_LIBRARY_PATH="/xxx/local/lib" -DCMAKE_INSTALL_PREFIX=/xxx/local  --with-glog  ..

```

4. fail to build example

```shell

cd example/echo_c++
mkdir build
cd build
cmake -DCMAKE_INCLUDE_PATH="/xxx/local/include" -DCMAKE_LIBRARY_PATH="/xxx/local/lib"  --with-glog  ..

```

error

**Expected behavior (期望行为)**
build successfully

**Versions (各种版本)**
OS:macos 10.14.5
Compiler:
 g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
brpc: 0.9.7
protobuf: protobuf-3.5.0.1

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/18414978/87282980-68bf8600-c527-11ea-9809-583ddba6f7b6.png)

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [echo_server] Error 1
make[1]: *** [CMakeFiles/echo_server.dir/all] Error 2
make: *** [all] Error 2

how can I solve it or any other suggestions ?

**Comment by ruoshui1314** [comment]
update:
It could be builded successfully when using master branch.
The command is:
`sh config_brpc.sh --headers="/xxx/local/include /usr/local/include" --libs="/xxx/local/lib /usr/local/lib /xxx/local/bin" --cc=clang --cxx=clang++
`
and building example is correct.


but fail to build 0.9.7 brpc library.
The detail errors :

`
Linking protoc-gen-mcpack
Undefined symbols for architecture x86_64:
  "fLI::FLAGS_v", referenced from:
      bthread::ContentionProfiler::flush_to_disk(bool) in libbrpc.a(mutex.o)
      bthread::TaskControl::worker_thread(void*) in libbrpc.a(task_control.o)
      bthread::TimerThread::run() in libbrpc.a(timer_thread.o)
  "google::LogMessage::stream()", referenced from:
      mcpack2pb::generate_serializing(google::protobuf::Descriptor const*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, google::protobuf::io::Printer&) in generator.o
      mcpack2pb::is_map_entry(google::protobuf::Descriptor const*) in generator.o
      bthread::ContentionProfiler::flush_to_disk(bool) in libbrpc.a(mutex.o)
      bthread::ContentionProfiler::init_if_needed() in libbrpc.a(mutex.o)
      butil::FlatMap<bthread::SampledContention*, bthread::SampledContention*, bthread::ContentionHash, bthread::ContentionEqual, false>::init(unsigned long, unsigned int) in libbrpc.a(mutex.o)
      bthread::ContentionProfilerStart(char const*) in libbrpc.a(mutex.o)
      bthread::ContentionProfilerStop() in libbrpc.a(mutex.o)
`

**Comment by critical27** [comment]
Still failed on macos big sur 11.3.1, it will fail if `--with-glog`. Will work if no `--with-glog` is added.
