### ISSUE TITLE
 [OnWindowUpdate] Invalid connection-level window_size_increment=103930

### ISSUE THREAD

**Issue by feng-y** [apache/brpc#1162]
**Describe the bug (描述bug)**
使用brpc client 访问 grpc server 时报错
E0714 10:22:33.653168 29518 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=195156
E0714 10:22:33.679425 29512 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=200042
E0714 10:22:33.698884 29515 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=190714
E0714 10:22:33.707713 29518 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=119851
E0714 10:22:33.719517 29512 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=41554
E0714 10:22:33.746649 29515 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=147503
E0714 10:22:33.754849 29512 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=201788
E0714 10:22:33.762006 29515 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=37681
E0714 10:22:33.777652 29518 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=462638
E0714 10:22:33.780248 29512 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=315310
E0714 10:22:33.789692 29508 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=100877
E0714 10:22:33.806560 29518 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=147603
E0714 10:22:33.826849 29512 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=103930
E0714 10:22:33.847781 29518 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=98243
E0714 10:22:33.855846 29518 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=3713
E0714 10:22:33.876771 29512 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level window_size_increment=56293
E0714 10:22:33.886059 29508 http2_rpc_protocol.cpp:998, OnWindowUpdate] Invalid connection-level  #window_size_increment=272550

使用grpc client 访问无异常

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:gcc8.4
brpc:0.96
protobuf:3.10

**Additional context/screenshots (更多上下文/截图)**

**Comment by feng-y** [comment]
E0714 10:17:41.036844 29512 http2_rpc_protocol.cpp:723, OnData] Fail to find stream_id=27791
  E0714 10:17:41.036900 29512 http2_rpc_protocol.cpp:723, OnData] Fail to find stream_id=27791
   E0714 10:17:41.036912 29512 http2_rpc_protocol.cpp:723, OnData] Fail to find stream_id=27791

在报 connection-level 时报了这个错误

**Comment by zyearn** [comment]
可以看看client的connections内置界面找到对应的socket，然后看看h2的各个参数是不是都是正常的，特别是_remote_window_left，这个报错是因为_remote_window_left整型溢出了。如果_remote_window_left不正常的话，需要抓个包看看grpc有没有正常把h2 Setting包发给client了

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
