### ISSUE TITLE
设置interval的正确方式是什么？

### ISSUE THREAD

**Issue by TheFinalHydra** [apache/brpc#1165]
目前在选择合适的interval上遇到一些问题：

1 LatencyRecorder设置interval为1s的时候，发现latency_80/90/99/9999都是没有值的，但是latency和qps都是有值的，换成10s(bvar_dump_interval)就一切正常了，是否因为其interval太短造成采样线程没有采到数据？
2 LatencyRecorder的interval设置成10s，那么latency是每10s的平均latency吗？如果我只希望获取过去每1s的平均latency，该如何设置？
3 PerSecond的interval默认是10s，如果觉得这个范围太宽，设置成1s，是不是就是和window<1s>是一样的效果？

此外，能否进一步说明一下设置的interval和http界面暴露的值的关系？发现有时候设置的interlval为60s，但是仍然http上是按照秒来更新的，算的平均值似乎也是1s为单位

**Comment by jamesge** [comment]
interval具体是指哪个参数？LatencyRecorder的初始化参数是window_size，这是其支持的最大统计窗口，需要取的时候是可以更小的。

**Comment by TheFinalHydra** [comment]
是的就是window_size, 但是设置成1s就是会发现`latency/max_latency`有值，但是`latency_90/90/99/9999`值为0

所以它为0的原因会不会是因为采样线程周期为1s, 然后我这里window_size设置为1s的话，可能恰好取不到上一次采样线程采到的值？
