### ISSUE TITLE
gdb_bthread_stack.py查看不了bthread stack

### ISSUE THREAD

**Issue by JianyuLi** [apache/brpc#1173]
使用gdb attach 服务进程后，试图查看其bthread的堆栈，遇到如下问题：
![image](https://user-images.githubusercontent.com/4198752/87770583-c6b6db00-c851-11ea-98dd-ef5b2ae49b8d.png)

报告g_task_control 不在 namespace "bthread"中，但是代码中是有对应的定义
![image](https://user-images.githubusercontent.com/4198752/87770887-2b723580-c852-11ea-92bb-505797b611d3.png)
请问是哪里不对，多谢

**Comment by lorinlee** [comment]
请问是什么系统，brpc是哪个版本

**Comment by JianyuLi** [comment]
os是centos7，内核版本3.10.0-693.5.2.el7.x86_64，brpc版本是incubator-brpc-0.9.7.tar.gz

**Comment by zhongleihe** [comment]
> 请问是什么系统，brpc是哪个版本

我也碰到这个问题了，请问这个问题有结论了吗？

**Comment by JianyuLi** [comment]
> > 请问是什么系统，brpc是哪个版本
> 
> 我也碰到这个问题了，请问这个问题有结论了吗？

目前还没有 :(

**Comment by lorinlee** [comment]
@JianyuLi @zhongleihe 辛苦试下https://github.com/apache/incubator-brpc/pull/1195这个看看，如果不行的话再提供一下gdb的版本吧，我这里没有复现出来，不过猜是上面这个PR的问题

**Comment by JianyuLi** [comment]
用#1195里的脚本，遇到新的问题
![image](https://user-images.githubusercontent.com/4198752/89284310-2bab6700-d681-11ea-97f1-5bf54de60d86.png)

![image](https://user-images.githubusercontent.com/4198752/89284356-3c5bdd00-d681-11ea-8e74-2289a7956207.png)

**Comment by lorinlee** [comment]
我用了centos7.4，gdb版本7.6.1-119.el7尝试复现，还是没有复现出来。如果方便的话能否提供一个可复现问题的Dockerfile呢

**Comment by lorinlee** [comment]
@JianyuLi @zhongleihe 请问可以提供一个可复现的环境嘛，Dockerfile就行

**Comment by lorinlee** [comment]
@JianyuLi @zhongleihe 请问问题解决了吗

**Comment by feng-y** [comment]
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/1547384/222759357-2615f45f-20f3-4d8e-87fa-32719b063104.png">

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1547384/222759534-6209b3a9-bbb0-4f40-92ad-94c69935c1b1.png">

@lorinlee  辛苦帮忙看看，怎么解

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.

**Comment by Gabriel39** [comment]
I met this error in Apache Doris. I solved it by not stripping brpc library (brpc library is stripped by default).
