### ISSUE TITLE
bthread::Mutex的内存占用远大于std::mutex

### ISSUE THREAD

**Issue by GOGOYAO** [apache/brpc#1190]
**Describe the bug (描述bug)**
std::vector<bthread::Mutex> locks_(1000000)
std::vector<std::mutex> locks_(1000000)
top查看，前者占用 VIRT：212M，RES：84612；后者占用 VIRT：66624，RES：7120

这个内存使用的差距有点大（RES是10倍关系）哦，简单看了下源码，感觉应该没有那么大差距才对？

**To Reproduce (复现方法)**
随意写个main函数就可以了

**Expected behavior (期望行为)**
差距没有量级的差距

**Versions (各种版本)**
OS: centos7
Compiler: gcc 8
brpc: master (11da9c8cbdc2ec8c0da728aedb4ed906717d6e0f)
protobuf: 3.11

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
什么场景需要用到这么多mutex实例？

**Comment by GOGOYAO** [comment]
> 什么场景需要用到这么多mutex实例？

在braft 做 multi raft的时候，每个分片（一个分片一个raft group）都放了一个条带锁。最开始放得比较大（10000个），分片多了就导致内存爆了。

**Comment by gydong** [comment]
我看你提供的数据10000实例的时候，虚拟内存使用量也就2M吧？这个对于您的场景来说很大是吧

**Comment by GOGOYAO** [comment]
> 我看你提供的数据10000实例的时候，虚拟内存使用量也就2M吧？这个对于您的场景来说很大是吧

分片多了就不行了。这个问题是在有个测试case发现的，当时调成了1000000。多几个分片就挂了
