### ISSUE TITLE
brpc超时设置不准？

### ISSUE THREAD

**Issue by kkstudykk** [apache/brpc#1206]
**Describe the bug (描述bug)**
请求后端redis，打印的超时日志：
E0812 16:38:14.126286 210330 redis_client.cpp:303] cntl failed, remote_ip:10.193.22.135:11127 cost_us:101858 error:[E1008]Reached timeout=10ms @10.193.22.135:11127

源码是：
if (cntl_ptr->Failed()) {
        VLOG_APP(ERROR) << "cntl failed, remote_ip:" << cntl_ptr->remote_side()
                     << " cost_us:" << cntl_ptr->latency_us() 
                     << " error:"<< cntl_ptr->ErrorText() ;
        response_ptr.reset();
}
rpc的latency_us怎么到了100ms？

**To Reproduce (复现方法)**
在qps较大的情况下复现概率高一些

**Expected behavior (期望行为)**
后端请求的延时，应该会按照超时设置截断？

**Versions (各种版本)**
OS: 
Compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
brpc: master
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
看下是不是请求发得太快了，导致server端不能正常处理（timeout），同时client不能正常及时运行新增的bthread了。

**Comment by kkstudykk** [comment]
> 看下是不是请求发得太快了，导致server端不能正常处理（timeout），同时client不能正常及时运行新增的bthread了。

server是redis集群，我们启的bthread来发rpc请求，一次请求，会触发20多个bthread请求，怀疑client新增请求过多吗？

**Comment by cdjingit** [comment]
看下bvar中的bthread_count和work usage是不是超过负载了。

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
