### ISSUE TITLE
remove the docs and comments related to HealthCheckThread

### ISSUE THREAD

**Issue by zyearn** [apache/brpc#1209]
HealthCheckThread is replaced by StartHealthCheck function in socket.cpp, but some of the docs/comments are not modified correspondingly. There are 3 files that HealthCheckThread is involved in:
* test/brpc_socket_unittest.cpp(3 occurrences)
* docs/cn/load_balancing.md(1 occurrence)
* src/brpc/socket.h(1 occurrence)

All sentences with 'HealthCheckThread' should be rewritten to sync with the meaning of updated code.

**Comment by VirendraYadav1234** [comment]
I want to work on this issue please assign me this issue

**Comment by Divyansh200102** [comment]
Can anyone review the pr? @zyearn
