### ISSUE TITLE
是否支持Curl通过Http发送大量数据至brpc server？

### ISSUE THREAD

**Issue by ZZili89** [apache/brpc#1217]
查阅了大量资料无果，只能求助社区，请问这种场景是否支持：
通过curl发送一个二进制流（<= 200M）给brpc http server，经过处理后再将处理后的流返回给client。
如果支持需要怎样做，不支持的话用brpc http client是否可行呢（client优先考虑curl的原因是易于部署，方便用户使用）？
谢谢。

**Comment by gydong** [comment]
server支持接收大body，但不支持持续接收（边接收边处理），所以只要内存足够用，是可以传输大body的
