### ISSUE TITLE
rpc_dump的功能可以方便的自定义采样频率吗？

### ISSUE THREAD

**Issue by guodongxiaren** [apache/brpc#1225]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
不用生产环境来dump流量。用的非生产环境，但是非生产环境的流量很小。想dump流量貌似很慢。

**Describe the solution you'd like (描述你期望的解决方法)**

```c
inline size_t is_collectable(CollectorSpeedLimit* speed_limit) {
    if (speed_limit->ever_grabbed) { // most common case
        const size_t sampling_range = speed_limit->sampling_range;
        // fast_rand is faster than fast_rand_in
        if ((butil::fast_rand() & (COLLECTOR_SAMPLING_BASE - 1)) >= sampling_range) {
            return 0;
        }
        return sampling_range;
    }
    // Slower, only runs before -bvar_collector_expected_per_second samples are
    // collected to calculate a more reasonable sampling_range for the type.
    extern size_t is_collectable_before_first_time_grabbed(CollectorSpeedLimit*);
    return is_collectable_before_first_time_grabbed(speed_limit);
}
```
这个sampling_range 受FLAGS_bvar_collector_expected_per_second影响。
但是计算方法太迷了。怎么设置才能让每个请求过来都能dump。

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
把 FLAGS_bvar_collector_expected_per_second 设置成超过你服务QPS的数据不可以吗？

**Comment by guodongxiaren** [comment]
> 把 FLAGS_bvar_collector_expected_per_second 设置成超过你服务QPS的一个数字不可以吗？

这个flag默认值是1000。已经远超我们的qps了。
@gydong

**Comment by gydong** [comment]
那你实际观测到的采样率大概是多少呢？

**Comment by guodongxiaren** [comment]
> 那你实际观测到的采样率大概是多少呢？

一个非线上的机器，就是一分钟内一会有请求一会没有。qps小于1吧。就想每次请求都落一下。不想用线上的机器落。怕影响性能。

**Comment by gydong** [comment]
『貌似很慢』这个描述很笼统，不清楚哪里不符合预期，是流量少导致慢还是采样频率不符合预期，如何不符合预期

**Comment by guodongxiaren** [comment]
> 『貌似很慢』这个描述很笼统，不清楚哪里不符合预期，是流量少导致慢还是采样频率不符合预期，如何不符合预期

不符合预期是说。当qps小于1的时候，一条都dump不下来。

**Comment by jamesge** [comment]
从实现角度来说，如果FLAGS_bvar_collector_expected_per_second远大于实际qps，应该是有很大概率会采样每一条请求
