### ISSUE TITLE
cpu profiler 开启的一个问题

### ISSUE THREAD

**Issue by GOGOYAO** [apache/brpc#1244]
**Describe the bug (描述bug)**

按照文档编译了brpc，然后在工程中，没有使用libunwind，使用了-fno-omit-frame-pointer，链接了/usr/lib64/libtcmalloc_and_profiler.so（通过yum安装的gperfs）

使用brpc server的，最终出现了
![image](https://user-images.githubusercontent.com/18675094/93303479-156efa00-f82e-11ea-9c01-e8b92f74217f.png)

但是最后发现cpu profile结果的下拉列表里面，可以正常打开看到cpu profile结果。

**To Reproduce (复现方法)**
编译brpc时，cmake .. -DBRPC_ENABLE_CPU_PROFILER=ON
编译工程时，除了连接brpc，还链接了/usr/lib64/libtcmalloc_and_profiler.so（通过yum安装的gperfs），同时加入了-fno-omit-frame-pointer到CMAKE_CXX_FLAGS中
**Expected behavior (期望行为)**
正常开启cpu profiler

**Versions (各种版本)**
OS: centos 7
Compiler: gcc 8
brpc: 11da9c8cbdc2ec8c0da728aedb4ed906717d6e0f
protobuf: 3.11

**Additional context/screenshots (更多上下文/截图)**

**Comment by pexeer** [comment]
1. 编译brpc时，带不带-DBRPC_ENABLE_CPU_PROFILER=ON这个都可以

2. 编译工程时，必需要带上-DBRPC_ENABLE_CPU_PROFILER=ON并且链接libtcmalloc_and_profiler.so

因为brpc的profile功能是在.h文件中定义的，只有在链接的时候才会去看BRPC_ENABLE_CPU_PROFILER是否开启，具体代码请看` brpc/details/profiler_linker.h`

**Comment by GOGOYAO** [comment]
> 因为brpc的profile功能是在.h文件中定义的，只有在你使用brpc的代码部分才会去看BRPC_ENABLE_CPU_PROFILER是否开启，具体代码请看` brpc/details/profiler_linker.h`

是你这样弄的。我的问题是，”发现cpu profile结果的下拉列表里面，可以正常打开看到cpu profile结果“，但是如果是选择<new profile>提示的是未开启。很奇怪

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
