### ISSUE TITLE
自适应限流问题E2004

### ISSUE THREAD

**Issue by alandiaslee** [apache/brpc#1277]
开启method自适应限流options.method_max_concurrency = "auto";
response [E2004]Rejected by **.**'s ConcurrencyLimiter, concurrency=2

![image](https://user-images.githubusercontent.com/73467889/97156049-20179a00-17b1-11eb-9559-8c413508cd49.png)

**Comment by TousakaRin** [comment]
自适应限流的concurrency会通过qps*latency来计算，并且最小值不会低于FLAGS_bthread_concurrency。
看图片应该是符合预期的，针对 latency与qps之积过于极端的场景，可以调整 bthread_concurrency减少reject请求数。

**Comment by alandiaslee** [comment]
> bthread_concurrency

![image](https://user-images.githubusercontent.com/73467889/97159989-a7b3d780-17b6-11eb-8a01-a50774893888.png)
已经配置到50，但计算出的max_concurrency看起来不符合预期

**Comment by zyearn** [comment]
@alandiaslee 应该用的是老版本，之后我们把策略改成 @TousakaRin 说的那样了，更新下版本试试

**Comment by alandiaslee** [comment]
> @alandiaslee 应该用的是老版本，之后我们把策略改成 @TousakaRin 说的那样了，更新下版本试试

我用的是0.9.6构建的，不知道是否包含了修改的策略，如果没有用哪个版本可以呢？

**Comment by zyearn** [comment]
0.9.8-rc01

**Comment by alandiaslee** [comment]
> 0.9.8-rc01

升级了新版brpc，开启自适应限流，在压力较大的情况下，服务端率先触发了E1008超时错误，
![image](https://user-images.githubusercontent.com/73467889/102179554-4d93e080-3ee2-11eb-905b-ae04b15490b5.png)
看起来线程已经被用满。认为正常的逻辑应该是自适应限流先被触发，这样对server以及服务稳定性能起到保护作用。
![image](https://user-images.githubusercontent.com/73467889/102179827-cb57ec00-3ee2-11eb-9d8d-bcd9af59db01.png)
