### ISSUE TITLE
bvar::Collector::run_dump_thread coredump

### ISSUE THREAD

**Issue by weixinwei** [apache/brpc#1318]
**Describe the bug (描述bug)**
bvar::Collector::run_dump_thread coredump

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: CentOS Linux release 8.1.1911 (Core)
Compiler: gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
brpc: brpc-0.9.8_rc01-1
protobuf: protobuf-3.5.0-7

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/47912552/103256801-77acce80-49c9-11eb-9e13-cbe65847aed5.png)

**Comment by cdjingit** [comment]
触发场景是什么？

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
