### ISSUE TITLE
Fail to epoll_wait

### ISSUE THREAD

**Issue by hustnn** [apache/brpc#1333]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/73186/105136207-3cb33c00-5b2c-11eb-81ee-8feddfcf26b6.png)

Any ideas on the possible reason for this error? Thanks in advance.

**Comment by jamesge** [comment]
The file descriptor for epoll (epfd) was probably closed somewhere

**Comment by hustnn** [comment]
@jamesge Thanks. Do you have any suggestion on how to debug the root cause? like finding out the place closes this fd.

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
