### ISSUE TITLE
brpc stream

### ISSUE THREAD

**Issue by guaniqming** [apache/brpc#1360]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/64455492/111792396-2d1f5c00-88ff-11eb-8bbc-ea156b71df27.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
