### ISSUE TITLE
有考虑过添加可以阻塞在bthread上的promise/future吗

### ISSUE THREAD

**Issue by cool-colo** [apache/brpc#1363]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
目前基于folly::future和brpc redis client封装了一个异步redis库, 
支持基于key slot分发请求和组装响应(用了folly::collectAll),
但folly::future只能阻塞在pthread上或folly的fiber上，
如果brpc提供个能阻塞在bthread上的版本就好了， 可以愉快的在brpc server 回调函数内部同步使用了。

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by leoncamel** [comment]
+1

**Comment by UncleWangNearBy** [comment]
+1

**Comment by pilife** [comment]
+1

**Comment by chenBright** [comment]
[babylon](https://github.com/baidu/babylon)支持在bthread上使用[future](https://github.com/baidu/babylon/blob/main/docs/future.md)。
