### ISSUE TITLE
brpc channel 并发delete和new情况导致sendmessage返回E112

### ISSUE THREAD

**Issue by guowei-bian** [apache/brpc#1380]
我在使用brpc时，client发消息给server报E112错误，此处有个疑问想请教一下。
场景是这样：有两个client一个server，两个client在同一个进程；一开始先是server重启并恢复正常，接着，每个client重新delete和new一下channel再send message给server，但在sendmessage时报E112错误（此处两个client的动作可能并行）。
为了便于说明问题，我画了个图：https://app.yinxiang.com/fx/849cca7d-0c31-4db9-9021-90bfcc8a7c72，
请帮忙解答一下。谢谢！

**Comment by zyearn** [comment]
可能是因为两个client看似是并发执行其实是串行的（代码块太小了），导致框架一直用原来的socket对象表示这个对端，而你服务器重启的时候导致这个socket处于Failed状态，之后发消息自然失败了。两个办法：
1）确保两个new Channel发生在两个delete Channel之后
2）等健康检查恢复server

**Comment by guowei-bian** [comment]
感谢zyearn的回复，对我理解这块有很大帮助。下面是我的简单理解，请您空了帮忙看看是否有误，谢谢！
那么channel和socket是什么关系呢？
通常情况下，一个channel对应一个socket，随着channel的init创建socket，channel析构时销毁socket。但在多个channel使用single连接类型情况下，多个channel就公用一个socket；在这种情况下，某个channel析构后，socket也不会析构；所以，在两个channel并发delete后又new的工作场景下，其对应的socket是否能够真正释放后再重建就不能确定了。
前面在issue中提到的，在服务端重启后，两个客户端军返回E112，就是因为两个channel并发delete和new，一旦其中一个client delete和new执行完了，另一个client才执行，就会导致原socket不能释放，也就是新的client1和client2还继续使用原socket，而原socket由于服务端重启还处在恢复过程中，所以两个client给server发消息就报E112错误，直到socket通过healchcheck恢复才可以成功发送。
channel对socket的管理是通过引用计数实现的，只有socket的引用计数归0，socket才能回收。

**Comment by zyearn** [comment]
> 但在多个channel使用single连接类型情况下，多个channel就公用一个socket

我之前说的socket对象和single连接没关系，这个socket是在socket_map中的socket（详见channel.cpp中调用的SocketMapInsert），拿到这个socket后，会根据不同的连接类型single,short还是pooled再确定发送数据的socket
