### ISSUE TITLE
heap 监控不显示图片，一般是因为什么？后台执行tools/pprof命令可以显示

### ISSUE THREAD

**Issue by cstarc** [apache/brpc#1384]
**Describe the bug (描述bug)**

![图片](https://user-images.githubusercontent.com/11407488/115195205-0c763c00-a121-11eb-9ab2-05b91db5fb1e.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
