### ISSUE TITLE
使用cpu profile的时候出core

### ISSUE THREAD

**Issue by GOGOYAO** [apache/brpc#1391]
**Describe the bug (描述bug)**
程序中使用了libhdfs，使用cpu profile的时候出core。
![image](https://user-images.githubusercontent.com/18675094/116428701-bd927a00-a877-11eb-8fa0-eb889522c957.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos 7 3.10.0-1.0.1.el7.x86_64
Compiler: gcc 485
brpc:  0.9.6
protobuf: 3.11

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
