### ISSUE TITLE
编译成功后，链接失败

### ISSUE THREAD

**Issue by dheart-joe** [apache/brpc#1425]
我的动态库文件一旦加上brpc的库后，编译可执行文件后，会报我的动态库，undefined symbol: pthread_mutex_lock。
无论pthread位置在前面还是后面，依旧报错

**Comment by lorinlee** [comment]
可以提供一个最小复现的环境吗，比如一个Dockerfile加上一个小的代码片段

**Comment by dheart-joe** [comment]
我发现由于brpc的bhtread中覆盖了，系统的pthread_mutex_lock，所以有时候会莫名其他的找不到pthread_mutex_lock

**Comment by dheart-joe** [comment]
brpc的pthread_mutex_lock
nm -A brpc/lib/libbrpc.so | grep pthread_mutex_lock
brpc/lib/libbrpc.so:0000000000499610 T pthread_mutex_lock
brpc/lib/libbrpc.so:0000000000498270 T _ZN7bthread28first_sys_pthread_mutex_lockEP15pthread_mutex_t
brpc/lib/libbrpc.so:0000000000b9f3b0 d _ZN7bthreadL22sys_pthread_mutex_lockE

phtread的pthread_mutex_lock
nm -A /lib/x86_64-linux-gnu/libpthread.so.0 | grep pthread_mutex_lock
/lib/x86_64-linux-gnu/libpthread.so.0:000000000000bfc0 t __GI___pthread_mutex_lock
/lib/x86_64-linux-gnu/libpthread.so.0:000000000000bfc0 T __pthread_mutex_lock
/lib/x86_64-linux-gnu/libpthread.so.0:000000000000bfc0 W pthread_mutex_lock
/lib/x86_64-linux-gnu/libpthread.so.0:000000000000b8a0 t __pthread_mutex_lock_full

我在猜可能其他项目用到brpc库的时候，估计要开启gcc的有关参数，才能解决这个冲突的问题，跟系统库的函数名冲突，是个比较麻烦的事情。

**Comment by lorinlee** [comment]
一般链接brpc都会链接pthread的，没有遇到过冲突的问题，能给个可复现demo么

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
