### ISSUE TITLE
call AskToQuit, then cannot restart server

### ISSUE THREAD

**Issue by yqynju** [apache/brpc#1471]
**Describe the bug (描述bug)**
```
void AskToQuit() {
    raise(SIGINT);
}


static volatile bool s_signal_quit = false;
static SignalHandler s_prev_sigint_handler = NULL;
static SignalHandler s_prev_sigterm_handler = NULL;

static void quit_handler(int signo) {
    s_signal_quit = true;
    if (SIGINT == signo && s_prev_sigint_handler) {
        s_prev_sigint_handler(signo);
    }
    if (SIGTERM == signo && s_prev_sigterm_handler) {
        s_prev_sigterm_handler(signo);
    }
}

the server start do not set 
s_signal_quit to false agin.

```

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
Hi, would you please describe the detail progress to reproduce this issue?

**Comment by yqynju** [comment]
> Hi, would you please describe the detail progress to reproduce this issue?

if server started,  do some work, then AskToQuit . server do not listen port any more. 

after a while, restart server again, the server cannot listen port.

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
