### ISSUE TITLE
日志中查看同一个请求的上下文

### ISSUE THREAD

**Issue by EngineerAzure** [apache/brpc#1490]
如标题述，brpc线程是非阻塞式的，由于并发量较高，在查看日志时不是很好看同一请求的上下文，求问同仁是否有建议可以提供，谢谢。
附部分日志的截图：
![image](https://user-images.githubusercontent.com/38313252/126441793-b7ef78e1-6827-4589-9ec9-8c8986b2b789.png)

**Comment by cdjingit** [comment]
具体需要看什么样的上下文，可以看看[rpcz](https://github.com/apache/incubator-brpc/blob/master/docs/cn/rpcz.md)是否满足你的需求？
