### ISSUE TITLE
brpc服务在ClosureGuard对象析构函数中coredump问题 message_lite.cc:65 CHECK failed异常

### ISSUE THREAD

**Issue by beforedream** [apache/brpc#1518]
**Describe the bug (描述bug)**
brpc方法出core，core的时候的部分堆栈如下
![image](https://user-images.githubusercontent.com/23582757/129338982-beff61f2-6002-40dc-986c-01b44a2bdd09.png)

出core时伴随的错误日志：
 google/protobuf/message_lite.cc:65 CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification of the message.
**To Reproduce (复现方法)**
暂无

**Expected behavior (期望行为)**
不出core

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by beforedream** [comment]
初次出现时，发现是bool类型赋值为了非1/0，修改为赋值true/false之后，测试10w+次未出现错误。
目前这次的原因并不清楚

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
