### ISSUE TITLE
go grpc 循环访问 brpc的一个接口服务拿数据，拿到的数据到达一定量的时候，brpc服务端会卡住，客户端收不到回的数据包

### ISSUE THREAD

**Issue by fishheader** [apache/brpc#1659]
**Describe the bug (描述bug)**

go grpc 循环访问 brpc的一个接口服务拿数据，拿到的数据到达一定量的时候，brpc服务端会卡住，客户端收不到回的数据包
每次拿2000行数据，第一次rpc就会卡住 
每次拿500行数据，第四次rpc会卡住
每次拿1行数据，差不多到第2w次rpc会卡住

卡住的现象，go grpc调用接口后不返回任何错误码，直到超时，抓包观察到的是brpc服务端填充了response但是没有回包
**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
go grpc用的是HTTP2，看看在服务端有没有关于WINDOW SIZE相关的日志错误

**Comment by wwbmmm** [comment]
有没有具体的复现方法？

**Comment by SinnerA** [comment]
可能两边的 initial window size 没对齐，默认是 64K，看下你没有改过？

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
