### ISSUE TITLE
用户注册的bthread local变量析构函数触发bthread切换引起coredump

### ISSUE THREAD

**Issue by zhaodongzhi** [apache/brpc#1776]
**Describe the bug (描述bug)**

### 问题1

<img width="669" alt="image" src="https://user-images.githubusercontent.com/6293650/172091827-9394b4b0-b6e9-4877-9438-6966784c0ac6.png">
使用了bthread local会以一定概率出现coredump，并且core的栈不固定，但大多在bthread::TaskGroup::sched_to的 errno = saved_errno;，分析后发现是由于注册的bthread local析构函数调用了bthread_mutex_lock会引发bthread local析构的时候出发bthread切换导致的，如下

![image](https://user-images.githubusercontent.com/6293650/172087148-8ed71dee-3ae5-4004-80e6-2e0af9df2484.png)

1. 假设bthread1在pthread1上调用return_keytable最终会调用用户注册的bthread local析构函数，如果这个析构函数调用了bthread_mutex_lock等会导致bthread切换的函数则会使得执行return_keytable之后bthread1切换到另一个线程pthread2上
2. 由于g还是用的pthread1上的thread local tls_task_group，在pthread2调用g->set_remained(TaskGroup::_release_last_context, m);会使得pthread1提前将bthread1的stack释放掉，如果此时另一个bthread2申请到了这个stack则会导致bthread1和bthread2共用了同一个stack，会导致互相踩栈引发coredump

### 问题1修复
![image](https://user-images.githubusercontent.com/6293650/172087227-44073939-a118-4f1b-a93d-fba4735ef28a.png)
可以移动g = tls_task_group到bthread local析构函数之后的位置修复

### 问题2
**应用上述修复后会遇到第二个问题，是由于gcc编译优化thread local访问方式结合bthread跨线程调度导致的**
<img width="871" alt="image" src="https://user-images.githubusercontent.com/6293650/172087565-1d162523-3a23-4e4e-9b8a-16b91b20491c.png">
bthread meta中记录的local_storage.keytable是正确的但是tls_bls.keytable被设置为null导致一个运行过程中的bthread突然获取不到这个bthread之前注册过的bthread local变量引起coredump
![image](https://user-images.githubusercontent.com/6293650/172087675-27600409-2ffd-4a67-8e1d-936137440bd9.png)

![image](https://user-images.githubusercontent.com/6293650/172087615-f33e0693-7a45-4178-a154-d818a8901c77.png)

![image](https://user-images.githubusercontent.com/6293650/172087694-21a0a581-8111-4feb-aecc-36bd247ea4ab.png)

可以看到编译优化后将tls_bls的地址保存在了寄存器r15中

我们知道如果用户注册的bthread local析构函数如果存在引起bthread切换的调用，return_keytable可能会触发bthread从pthread1切换到pthread2上，这里由于gcc将tls_bls的地址保存在r15寄存器的优化会导致在pthread2执行
tls_bls.keytable = NULL;
这个操作实际上是将pthread1的tls_bls.keytable设置为null了，而此时pthread1上运行的bthread2可能设置过tls_bls.keytable是不为null的，也就导致了我们上面看到的现象，pthread1上的bthread2获取不到自己设置的bthread local变量了

### 问题2修复
这个问题使用原子变量或memory fence也解决不了，因为这两者对gcc来说只能组织缓存值的优化不能阻止缓存地址的优化
可以将
KeyTable* kt = tls_bls.keytable;
修改为
KeyTable* kt = m->local_storage.keytable
判定上是等价的，但是可以先避开gcc 缓存tls_bls地址的优化

也可以考虑将thread local关键字声明的tls_bls用pthread_getspecific函数api替代，因为gcc无法对通过pthread_getspecific获取到的thread local做缓存优化，不过这样改的会有点多

**To Reproduce (复现方法)**

自己写一个注册bthread local 析构函数中调用bthread_mutex_lock的代码多线程并发启动，停止bthread以触发bthread_local析构

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler: gcc 4.8.5
brpc: v1.0.0
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by zcfh** [comment]
Has this issue been resolved so far? I see that the relevant patch has not been merged yet, and the issue is still open.

**Comment by chenBright** [comment]
This bug has been fixed in #2558 .

**Comment by zcfh** [comment]
问题2，关于 tls_bls 被缓存在寄存器上的问题，看起来还没解决吧？

**Comment by yuanzhubi** [comment]
> 问题2，关于 tls_bls 被缓存在寄存器上的问题，看起来还没解决吧？

感觉是一个机制的问题，worker steal的实现机制对于任何可能发生thread 切换，都可能让对tls的使用产生问题。需要系统的在避免tls使用。

**Comment by BiteTheDDDDt** [comment]
我们在1.12.1上也遇到了这个问题2，而且在之前的1.4版本没遇到这个问题，可能是中间关于keytable的某些改动造成这个问题更容易被触发了？

![Image](https://github.com/user-attachments/assets/b2372a46-b2f5-4365-a0d3-53c1a1db7e69)
试了一下这样改可以正确获取到bthread local的值

**Comment by zcfh** [comment]
请问下，这个有可复现的demo吗？
目前加上这个patch后，真实的服务场景还是有问题，所以想简化demo复现下。
