### ISSUE TITLE
使用brpc作grpc客户端发请求时是否可以带上域名呢

### ISSUE THREAD

**Issue by jiangdongzi** [apache/brpc#2046]
![image](https://user-images.githubusercontent.com/17529657/206676462-2181c6eb-a263-4733-b62c-febb7f4281a9.png)
我们使用nginx做grpc的网关, 没有域名的话, 会被直接驳回 返回404

下面是使用grpc 客户端的网关日志, 访问是正常的
![image](https://user-images.githubusercontent.com/17529657/206676922-d8591876-40cc-45e3-a82f-3510a9ef1449.png)

**Comment by wwbmmm** [comment]
用controller.http_request().uri().set_host()可以吗？

**Comment by jiangdongzi** [comment]
> 用controller.http_request().uri().set_host()可以吗？

试了下, 没有加上,  也试了下 "cntl.http_request().SetHeader("Host, "xxxxxx") 也不行
