### ISSUE TITLE
Bash shebangs are wrong: they should be #!/usr/bin/env bash

### ISSUE THREAD

**Issue by yurivict** [apache/brpc#2070]
[Here](https://github.com/apache/incubator-brpc/blob/master/tools/get_brpc_revision.sh#L1) and in all other shell scripts

**Comment by wwbmmm** [comment]
related: #2072

**Comment by wasphin** [comment]
After some googling, it seems not all OS uses `/bin/bash` as the default bash location. e.g. FreeBSD use `/usr/local/bin/bash`?

And, if I understand right, there's no standard POSIX location for `env`, either.

`#!/usr/bin/env bash` may be more portable, but that doesn't mean `#!/bin/bash` is wrong.


https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang
https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash
https://en.wikipedia.org/w/index.php?title=Shebang_(Unix)&oldid=878552871#Portability

**Comment by yurivict** [comment]
```#!/usr/bin/env bash``` works on all systems.
