### ISSUE TITLE
关于append_user_data中使用引用计数内存的问题

### ISSUE THREAD

**Issue by luliyucoordinate** [apache/brpc#2073]
我看到现有iobuf里面如果想要使用一个申请好的内存可以使用append_user_data，这个方法需要传入一个delete的析构（是一个`void(void*)`函数，传入raw数据地址）。

如果申请好的内存是一个引用计数管理的内存，也就是需要append_user_data需要支持引用计数管理的内存，这个现有的代码中有办法实现吗？还是说需要修改原来iobuf的逻辑，将delete改为支持可以传入对象地址的一个function呢？

**Comment by Tuvie** [comment]
目前IOBuf还不支持帮外部内存做引用技术
