### ISSUE TITLE
客户端请求比较耗时的case 时，rpc E1010，500 Internal Server Error

### ISSUE THREAD

**Issue by xiaoyuxee** [apache/brpc#2074]
**Describe the bug (描述bug)**
server 端响应时间超过一定阈值时，client 收到 rpc 错误：E1010。如果请求server 端处理时间较少的case，client 端 则可以接受到正常响应。

rpc 错误时，client 端 controller 错误信息如下：
```
E20230108 17:38:30.313141 ... code[1010] timeout[-1] latency_us[149377] err[[E1010]1/1 channels failed, fail_limit=1 
[C0][E1010]HTTP/2.0 500 Internal Server Error]
```

此时服务端业务处理逻辑正常，日志如下：
```
INFO 2023-01-08 17:38:30 140677572634368 Received query: ...
INFO 2023-01-08 17:38:30 140677572634368 Handle success. rt[137044us]
```

client 端信息如下：
- ParallelChannel 中包含多个 SelectiveChannel，用于并行调用 SelectiveChannel 中某个 server
- protocol = "h2:grpc"
- SelectiveChannel `timeout_ms`、`connect_timeout_ms` 均为 -1

**To Reproduce (复现方法)**
增加 server 端业务处理时长，client 将获取到 rpc 错误

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: 
Compiler: 4.9.2
brpc: 0.9.7
protobuf: 3.11.4

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
client和server间是不是还有一层http代理？

**Comment by xiaoyuxee** [comment]
> client和server间是不是还有一层http代理？

通过 k8s 的pod域名来调用 server 的

**Comment by xiaoyuxee** [comment]
通过打印日志发现，client 端socket 接受到的 header 中已经是 500 了

**Comment by wwbmmm** [comment]
在client和server分别抓包看看

**Comment by xiaoyuxee** [comment]
> client 端信息如下：
> 
> * ParallelChannel 中包含多个 SelectiveChannel，用于并行调用 SelectiveChannel 中某个 server
> * protocol = "h2:grpc"
> * SelectiveChannel `timeout_ms`、`connect_timeout_ms` 均为 -1
> 

刚刚试了下，client protocol 改为 "baidu_std" 则没问题

**Comment by xiaoyuxee** [comment]
把 client 端 window size 调大后，问题解决。

> 客户端请求比较耗时的case ...

应该不是耗时引起，而是耗时的 case 所产生的 response 也比较大。

**Comment by pengybhnu** [comment]
> 把 client 端 window size 调大后，问题解决。
> 
> > 客户端请求比较耗时的case ...
> 
> 应该不是耗时引起，而是耗时的 case 所产生的 response 也比较大。

 请教 client 端 window size 调大的具体代码如何写的？调大了 brpc client 和 server 端的h2_client_connection_window_size，h2_client_stream_window_size 大小，还是出现E1010]HTTP/2.0 500 Internal Server Error
