### ISSUE TITLE
后台工作线程在fork后不会再工作

### ISSUE THREAD

**Issue by jamesge** [apache/brpc#208]
比如bvar的sampler thread在fork后就不会再运行，这就是之前simpledb中vars异常的原因。这要通过pthread_atfork才能支持.
因为有很多bvar是全局变量，所以即使用户没有在代码中明确地使用rpc相关的东西，在fork前也会启动sampling thread，从而造成问题。

**Comment by xmm1989218** [comment]
这个啥时候会解决么

**Comment by jamesge** [comment]
你在什么场景中会依赖这点？

**Comment by xmm1989218** [comment]
我demon方式启动服务

**Comment by jamesge** [comment]
具体形式是？fork()之后parent exit，child不exec直接继续运行么？

**Comment by jamesge** [comment]
看下https://github.com/apache/incubator-brpc/blob/master/docs/cn/server.md#fork-without-exec

**Comment by wasphin** [comment]
@jamesge  #1227 中的现象和这个是不是也有关系? 如何在使用 ``brpc`` 的程序中启动其他子进程呢?

**Comment by Superskyyy** [comment]
Is this fixed and can be closed?

**Comment by jamesge** [comment]
> Is this fixed and can be closed?
already fixed and should be closed
