### ISSUE TITLE
发版前添加 release notes 讨论环节

### ISSUE THREAD

**Issue by wasphin** [apache/brpc#2101]
更新发版流程，添加 release notes 的确认环节，避免遗漏部分改动。

参考：https://shardingsphere.apache.org/community/cn/involved/release/shardingsphere/

**Comment by wwbmmm** [comment]
赞同，直接加到发版流程文档里吧

**Comment by wwbmmm** [comment]
Test github email

**Comment by wwbmmm** [comment]
test issue
