### ISSUE TITLE
Release plan of RDMA support?

### ISSUE THREAD

**Issue by SongGuyang** [apache/brpc#2104]
I know that the master branch has supported RDMA now. What's the state of RDMA development? Do we have plans to release it and make it to be used in production environment?

**Comment by wasphin** [comment]
The 1.4.0 release, which is in the release process, contains the RDMA feature and will be publicly available in the following few days.

**Comment by wasphin** [comment]
Hi, the new version 1.4.0 with RDMA support has been released.

https://dlcdn.apache.org/brpc/1.4.0/
https://github.com/apache/brpc/releases/tag/1.4.0

**Comment by SongGuyang** [comment]
Nice! Thanks.
