### ISSUE TITLE
Question: scheduling of the bthread of ExecutionQueue

### ISSUE THREAD

**Issue by liangjchen** [apache/brpc#2110]
I try to understand scheduling behavior of ExecutionQueue and fit into our scenarios. My understanding is that there is a bthread (consumer) associated with a queue to execute tasks. Is it like a normal concurrent queue such that each time a new task is enqueued, the consumer is notified and woke up to execute? Is there any configuration that allows me to specify the consumer bthread's scheduling, e.g., how often it is scheduled?  

Suppose that I want to introduce a small artificial delay on consumer execution (hoping to gather more tasks in a batch), what's the best option to accomplish this? Is it wise to call ``sleep`` in the consumer bthread? 

thanks,

**Comment by cooper-zhzhang** [comment]
1. 当有新的任务入队时，就会开启一个新的bthread消费队列(如果当时没有bthread在消费)
2. 目前没有办法指定一个特定的bthread去消费队列中的任务。不过可以设置参数in_place_if_possible指定在当前线程直接执行任务，而不是开启一个新bthread。
3. 在bthread中调用sleep会造成整个thread休眠。这是不允许的。

**Comment by liangjchen** [comment]
thanks. This answers my question.
