### ISSUE TITLE
使用grpc协议时，如何支持填充metadata信息 

### ISSUE THREAD

**Issue by 982945902** [apache/brpc#2113]

**Comment by xiaoyuxee** [comment]
@982945902 请问找到填充 matadata 的办法了吗

**Comment by 982945902** [comment]
> @982945902 请问找到填充 matadata 的办法了吗

client:
cntl.http_request().SetHeader("test","111")

server:
brpc::Controller *cntl =
            static_cast<brpc::Controller *>(controller);
auto ptest = cntl->http_request().GetHeader("test")

**Comment by xiaoyuxee** [comment]
> > @982945902 请问找到填充 matadata 的办法了吗
> 
> client: cntl.http_request().SetHeader("test","111")
> 
> server: brpc::Controller *cntl = static_cast<brpc::Controller *>(controller); auto ptest = cntl->http_request().GetHeader("test")

嗯，我刚刚也这么测试work 了。因为 grpc 协议中 metadata 是解析于 http 中 header。
