### ISSUE TITLE
ExtendedEndPoint 类报错：<Fatal> brpc: Check failed: old_ref >= 1. ExtendedEndPoint has unexpected reference -21

### ISSUE THREAD

**Issue by luffyhwl** [apache/brpc#2114]
最基本的使用方式：
client 端：

Client类成员包括 channel，XXXService_Stub，多个请求复用。

> class Client {
>        brpc::Channel channel;
>        XXXService_Stub stub;
> };

发送请求：

> void Client::sendRequest () {
>         brpc::Controller cntl;
>         XXXRequest request;
>         XXXResponse response;
>         stub->XXXMethod(&cntl, &request, &response, nullptr);
> }

server：

> void XXXServiceImpl::XXXMethod(
>     google::protobuf::RpcController * cntl,
>     const XXXRequest * request,
>     XXXResponse * response,
>     google::protobuf::Closure * done)
> {
>         auto & controller = static_cast<brpc::Controller &>(cntl);
>         auto client_str = butil::endpoint2str(controller.remote_side()).c_str();                //**这边发现client_str 是空串**
> }

<Fatal> brpc: Check failed: old_ref == 0. new ExtendedEndPoint has reference 10
<Fatal> brpc: Check failed: eep->_u.sa.sa_family == AF_UNSPEC. new ExtendedEndPoint has family 10 set
<Fatal> brpc: Check failed: old_ref >= 1. ExtendedEndPoint has unexpected reference -21
发现有以上几种报错，请问可能的原因是什么呢？

**Comment by Huixxi** [comment]
> 

代码中是怎么使用的呢？

**Comment by luffyhwl** [comment]
> > 
> 
> 代码中是怎么使用的呢？

最基本的使用方式，已更新到问题中。

**Comment by wwbmmm** [comment]
用到ipv6或UDS功能了吗？

**Comment by luffyhwl** [comment]
> 用到ipv6或UDS功能了吗？

用了ipv6

**Comment by wwbmmm** [comment]
感觉可能是内存问题，建议跑一下asan看一下

**Comment by luffyhwl** [comment]
> 感觉可能是内存问题，建议跑一下asan看一下

好的，感谢
