### ISSUE TITLE
brpc_metrics里面缺少单独的average统计

### ISSUE THREAD

**Issue by mrwhyxxk** [apache/brpc#2116]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

brpc_metrics
**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**
对于rpc_server的metric，单独添加一行average

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
related: #2012

**Comment by wwbmmm** [comment]
试试PR #2024
