### ISSUE TITLE
brpc的用户态tcp支持多进程吗？

### ISSUE THREAD

**Issue by netjia-cpu** [apache/brpc#2118]
在分布式存储领域，比如ceph，一个节点上有多个osd进程，brpc是可以用一张网卡支持所有的osd网络收发吗？

**Comment by Tuvie** [comment]
现在用户态tcp的实现还没有合入到brpc。多进程理论上是可以支持，但是支持的方法会和网卡型号有关。

**Comment by xihaishibei** [comment]
> 现在用户态tcp的实现还没有合入到brpc。多进程理论上是可以支持，但是支持的方法会和网卡型号有关。

多谢大佬解惑，还想再问一个问题，就是目前商用的用户态tcp用的是多进程还是单进程，比如阿里的盘古

**Comment by Tuvie** [comment]
什么叫『商用的用户态TCP』呢？

**Comment by xihaishibei** [comment]
就是已经用在生产系统中，已经产品化了的

**Comment by Tuvie** [comment]
我们可以就具体的开源项目或针对bRPC用户态具体的需求、实现方式进行讨论。其他非开源或非开放的信息，我们这里不具备讨论基础。
