### ISSUE TITLE
调整bthread_concurrency小于cpu核数不生效问题 

### ISSUE THREAD

**Issue by cmdmspaint** [apache/brpc#2125]
用于测试的server是128核的cpu
brpc内部bthread_concurrency参数的default value应该是9
![image](https://user-images.githubusercontent.com/50624748/218966802-2053df34-4bd2-4f2f-b8db-11b131609bdc.png)
但是为什么在bavr上显示的value是129而不是9呢，这和ServerOptions.num_threads数量默认是cpu core的个数有关吗？
![image](https://user-images.githubusercontent.com/50624748/218967035-9eedafb2-16bb-4a66-a88c-bba8a323fcd0.png)

**Comment by ehds** [comment]
是的。
https://github.com/apache/brpc/blob/3d4db04303736903f5345be2187a7842cf4a11f7/src/brpc/server.cpp#L146-L148

这里会初始化为 cpu 个数 + 1。
https://github.com/apache/brpc/blob/3d4db04303736903f5345be2187a7842cf4a11f7/src/brpc/server.cpp#L960-L968

这里会增加 worker 数量。

**Comment by cmdmspaint** [comment]
> 是的。
> 
> https://github.com/apache/brpc/blob/3d4db04303736903f5345be2187a7842cf4a11f7/src/brpc/server.cpp#L146-L148
> 
> 这里会初始化为 cpu 个数 + 1。
> 
> https://github.com/apache/brpc/blob/3d4db04303736903f5345be2187a7842cf4a11f7/src/brpc/server.cpp#L960-L968
> 
> 这里会增加 worker 数量。

好的，多谢
