### ISSUE TITLE
brpc channel保序问题

### ISSUE THREAD

**Issue by netjia-cpu** [apache/brpc#2150]
测试brpc的example/asynchronous_echo_c++ 例子，协议是baidu_std，正常情况下server端收到的log_id顺序没问题，重启网络：network restart后，server端收到的log_id的顺序就不对了，brpc channel无法保序吗？还是要应用自己做？
![image](https://user-images.githubusercontent.com/13553842/223069061-b12c8412-6776-47c6-ad65-299f4d3075d7.png)

**Comment by netjia-cpu** [comment]
echo.pb里面的request也加上id，打印出来，在故障情况下，也是乱序的

**Comment by wwbmmm** [comment]
这个和channel没关系，这是因为server端收到请求时，会启动新的bthread来处理请求，如果同时有多个请求，它们的处理顺序是不能保障的。

**Comment by netjia-cpu** [comment]
> 这个和channel没关系，这是因为server端收到请求时，会启动新的bthread来处理请求，如果同时有多个请求，它们的处理顺序是不能保障的。

明白了，谢谢
