### ISSUE TITLE
brpc与grpc可以共存么, 

### ISSUE THREAD

**Issue by jiangdongzi** [apache/brpc#2155]
brpc定义proto需要 option cc_generic_services = true;, 而brpc不能使用这一行, 他们二者生成不通的接口, 目前是共存不了, 不知道有没办法呢

**Comment by wwbmmm** [comment]
> 而brpc不能使用这一行

这里是想写grpc？

**Comment by jiangdongzi** [comment]
> > 而brpc不能使用这一行
> 
> 这里是想写grpc？

是我们与别人共用proto, 别人比如java用的grpc, 我们不能随便改proto

**Comment by wwbmmm** [comment]
好像没啥好办法，可以在编译脚本里加个命令临时改一下proto文件里的option cc_generic_services

**Comment by jiangdongzi** [comment]
> 好像没啥好办法，可以在编译脚本里加个命令临时改一下proto文件里的option cc_generic_services

感谢
