### ISSUE TITLE
brpc的协议格式是什么样子的，想通过wireshark解析一下brpc

### ISSUE THREAD

**Issue by cmdmspaint** [apache/brpc#2157]
在wireshark写了一个lua插件，按照sofa_pbrpc_meta.proto格式解析了一下。发现格式好像不太正确，所以想请教一下brpc协议格式
![image](https://user-images.githubusercontent.com/50624748/223951455-257513d5-eedb-46d8-b3a0-776a3f1029c2.png)
![image](https://user-images.githubusercontent.com/50624748/223951649-c9f938d3-4af4-49d8-a155-7aba7fe0968e.png)

**Comment by chenBright** [comment]
src/brpc/policy/baidu_rpc_meta.proto，这个吧

**Comment by cmdmspaint** [comment]
> src/brpc/policy/baidu_rpc_meta.proto，这个吧

应该是由包头和包体组成，包体又分为metadata、data和payload
包头我知道是12个字节，通过包头我解析出来是SOFA协议
![image](https://user-images.githubusercontent.com/50624748/223962519-58cc5f4c-fb43-4813-89d7-9d22eb193fda.png)

**Comment by cmdmspaint** [comment]
> src/brpc/policy/baidu_rpc_meta.proto，这个吧

目前就是不太清楚包体的格式

**Comment by chenBright** [comment]
看了一下代码，SOFA协议应该是24字节吧
https://github.com/apache/brpc/blob/2ec8f469f82a30c0abfb534f98b7fce0f0f77455/src/brpc/policy/sofa_pbrpc_protocol.cpp#L132-L138

**Comment by cmdmspaint** [comment]
我理解brpc包的结构是这样的，目前了解到RpcMessageHeader是24字节。
![image](https://user-images.githubusercontent.com/50624748/224207552-ad2fbcf4-956b-4503-98dd-b4cb5c77db4b.png)
这个是RpcMeta的结构，按照对应的字节数进行解析。为什么对不上呢？ enum类型应该是占4字节吧
message RpcMeta {
  enum Type {
    REQUEST = 0;
    RESPONSE = 1;
  };
  required Type type = 1;                 // 4bytes
  required uint64 sequence_id = 2;  //8bytes
  optional string method = 100;       
  optional int64 server_timeout = 101;
  optional bool failed = 200;
  optional int32 error_code = 201;
  optional string reason = 202;
  optional CompressType compress_type = 300;
  optional CompressType expected_response_compress_type = 301;
}

**Comment by cmdmspaint** [comment]
是开了什么压缩导致的吗？

**Comment by cmdmspaint** [comment]
看了一下代码 rpcmeta是通过protobuf进行了编码，应该是按照Base 128 Varints来进行压缩的。待会验证一下看看是否正确。
![image](https://user-images.githubusercontent.com/50624748/224243432-0ebee61a-644f-4db4-bccd-aa272b93ef6b.png)

**Comment by wasphin** [comment]
需要看具体解析或者序列化部分，部分协议只是内部用 protobuf 传递，而没有在网络传输时用，并不能完全按照 proto 文件解析。
