### ISSUE TITLE
请问brpc是如何保证pb在client和server端间的数据一致性的？

### ISSUE THREAD

**Issue by ravenxrz** [apache/brpc#2159]
如题，这是由brpc来保证，还是说pb来保证？另外，是如何保证的呢，对整个pb字节数组进行crc吗？

**Comment by wwbmmm** [comment]
这是tcp协议保证的，brpc不做crc检查

**Comment by ravenxrz** [comment]
好的，谢谢。

**Comment by qq1033731787** [comment]
> 这是tcp协议保证的，brpc不做crc检查

http://noahdavids.org/self_published/CRC_and_checksum.html
TCP协议保证很弱的，brpc会考虑做业务层crc吗？
