### ISSUE TITLE
性能测试：同机单client→单server在固定QPS下的延时CDF（越左越好，越直越好）

### ISSUE THREAD

**Issue by Darwinnpos** [apache/brpc#2170]
你好，是否可以给出详细数据

**Comment by Huixxi** [comment]
https://brpc.apache.org/zh/docs/benchmark/#%E5%90%8C%E6%9C%BA%E5%8D%95client%E5%8D%95server%E5%9C%A8%E5%9B%BA%E5%AE%9Aqps%E4%B8%8B%E7%9A%84%E5%BB%B6%E6%97%B6cdfbuiltin-servicesvars%E7%BB%9F%E8%AE%A1%E5%92%8C%E6%9F%A5%E7%9C%8B%E5%88%86%E4%BD%8D%E5%80%BC%E8%B6%8A%E5%B7%A6%E8%B6%8A%E5%A5%BD%E8%B6%8A%E7%9B%B4%E8%B6%8A%E5%A5%BD 可以看下图片中的测试基准参数。
