### ISSUE TITLE
[feature request] support rvalue in bthread::execution_queue_execute

### ISSUE THREAD

**Issue by qiuhuiming** [apache/brpc#2182]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

In some scenario, the task structures do not have copy constructor, but have move constructor. In this case, we cannot use the  `execution_queue_execute` function directly. I think it would be better to provide an overload function which takes rvalue task.

在有一些场景中，Task不可支持拷贝构造，仅支持移动构造，就需要execution_queue_execute提供一个右值版本的重载。

**Describe the solution you'd like (描述你期望的解决方法)**

为execution_queue_execute添加右值引用版本，右值版本的内部实现调用移动构造。

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

当前版本，显式删除单元测试test/bthread_execution_queue_unittest.cpp中的`LongIntTask`的复制构造函数，会有编译错误。

![image](https://user-images.githubusercontent.com/47179776/227978041-9bf6ac36-aeeb-4488-b96b-aaa79466fcd2.png)

如果能够提供右值引用版本，可能会比较好解决这个问题。

**Comment by chenBright** [comment]
使用一个可拷贝的类，包含LongIntTask的shared_ptr，是不是可以解决这个问题？
```c++
struct TaskItem {
    std::shared_ptr<LongIntTask> long_int_task;
}
```

**Comment by qiuhuiming** [comment]
这样可以解决，但是感觉会引入额外的包装类，并且对于一些明显需要移动的结构，语义上感觉不太合适。以后是否有计划支持这个呢，或者之后我可以写个PR吗？

**Comment by wwbmmm** [comment]
欢迎提PR
