### ISSUE TITLE
这段代码有问题吗

### ISSUE THREAD

**Issue by jiangdongzi** [apache/brpc#2208]
![image](https://user-images.githubusercontent.com/17529657/231682306-4cba9530-6f69-407c-813b-2638da3989b4.png)
切换到一个新bthread的时候,  `saved_errno` 和 `saved_unique_user_ptr` 不是毫无意义的值么?  第一次运行时在下面重新赋值了毫无意义的值?

**Comment by ehds** [comment]
jump_stack 会切换到其他 bthread 执行任务，上下文切换了，当执行到下面的逻辑，`saved_errno` 和 `saved_unique_user_ptr`已经发生了更改，需要重新赋值。
