### ISSUE TITLE
RDMA coredump

### ISSUE THREAD

**Issue by trevor211** [apache/brpc#2213]
**Describe the bug (描述bug)**
example/rdma_performance测试，client coredump。
<img width="1915" alt="1681720740452-image" src="https://user-images.githubusercontent.com/5462911/232948356-941f0854-2c18-415e-85c9-8a534b1def91.png">

**To Reproduce (复现方法)**
1. 准备2台支持rdma的机器：host_a, host_b。
2. host_a部署example/rdma_performance中的server，host_b部署example/rdma_performance中的client。
3. 在host_a中，执行rdma故障注入，故障注入脚本down_rdma.sh：
``` bash
#!/bin/bash
source /etc/profile
eth_list=`ip a | grep "eth" | grep "UP" | awk -F ': ' '{print $2}'`
for eth in $eth_list
do
    mlnx_qos -i $eth --pfc  0,0,0,0,0,0,0,0
    mlnx_qos -i $eth --buffer_size=262016,0,0,0,0,0,0,0
    mlnx_qos -i $eth --prio2buffer=0,0,0,4,0,0,0,0
done
```

**Expected behavior (期望行为)**
client不core

**Versions (各种版本)**
OS: CentOS Linux，VERSION="7 (Core)"
Compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
brpc: master分支
protobuf: 2.5.0-8.el7

**Additional context/screenshots (更多上下文/截图)**
--rdma_prepared_qp_cnt=1 和--rdma_prepared_qp_cnt=4000的时候不会core，设置为其他值会core。
出问题的cq没有提前释放。

**Comment by lorinlee** [comment]
这个问题辛苦 @Tuvie 帮忙看看哈

**Comment by Tuvie** [comment]
这个故障注入的原理是什么？我通过所提供的脚本无法实现故障注入，仍然正常运行。

**Comment by jiangzhuti** [comment]
> 这个故障注入的原理是什么？我通过所提供的脚本无法实现故障注入，仍然正常运行。

你好。这个脚本会关闭3队列网卡buffer,我们roce在3队列运行，关闭buffer后相当于主机侧rdma流量断开，用perftest打流测试表现为出现timeout cqe。我们通过这个脚本实现rdma的故障注入，并且不影响tcp协议

**Comment by Tuvie** [comment]
https://github.com/apache/brpc/pull/2220
可以试下这个pr。应该是预申请的资源释放的过早了。

**Comment by trevor211** [comment]
试过了，core问题解决了
