### ISSUE TITLE
CHECK触发后不会终止程序

### ISSUE THREAD

**Issue by Gangbiao** [apache/brpc#2216]
**Describe the bug (描述bug)**
CHECK触发后不会终止程序，

**To Reproduce (复现方法)**
显示增加CHECK(0);

**Expected behavior (期望行为)**
程序退出，并产生crush dump

**Versions (各种版本)**
OS: BigCloud Enterprise Linux release 7.6.1905 (Core)
Compiler:  4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
brpc: 1.0.4.g361b9c1-1.el7.bclinux.x86_64
protobuf: 2.5.0-8.el7

**Additional context/screenshots (更多上下文/截图)**

![d601c0ed10678d1a2bccd4ba2ff411f](https://user-images.githubusercontent.com/11597184/233273964-3d9e38fb-5758-4812-a57d-53e878ad1ca2.png)

**Comment by lorinlee** [comment]
有打开 -crash_on_fatal_log 这个flag吗

**Comment by Gangbiao** [comment]
没有打开，默认的是FALSE，打开之后可以crush了，谢谢。
