### ISSUE TITLE
服务端是否可以知道客户端已经超时返回了

### ISSUE THREAD

**Issue by vinllen** [apache/brpc#2222]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**
举个例子，客户端发送请求到服务端，配置超时3秒。但是服务端可能因为某些情况长时间没有返回，客户端超时退出了，我的需求是，在这个情况下，服务端能否提前知道客户端已经超时返回，那么就可以内部不在长期占用资源（比如一个很大的扫描请求，花费10分钟），提前结束这个消息。
类似有一个连接context，可以通过context获取到对端已经释放，那么当前服务端的请求就可以提前结束。

Controller类里面有一个IsCanceled()函数，但是看注释好像不能处理客户端超时导致的释放情况，不知道是否有别的参数可以感知到？
**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
如果client是用pooled模式发起rpc的，当rpc超时时，client会直接丢掉连接。server端应该能感知到连接断开，不过目前Controller没有开放接口获取peer_id。如果有这个接口，server端可以通过Address(peer_id)来判断请求是否可以提前结束。

**Comment by chenBright** [comment]
另一个方案是[Deadline Request 调用链超时](https://juejin.cn/post/6914091859463634951#heading-11)。这个方案的改造量比较大，需要brpc具备透传能力。还得考虑机器时钟同步的问题。

**Comment by yanglimingcn** [comment]
现在客户端可以通过controller设置timeout_ms，这个超时时间能传递到服务端，服务端可以给请求加上个timer，超时时间为timeout_ms，如果时间到了请求还没有处理，就删掉这个请求。

**Comment by vinllen** [comment]
@yanglimingcn 这个服务端如何获取，是通过哪个接口？另外，这个值取决于本地的墙上时钟，可能会不准？

**Comment by yanglimingcn** [comment]
服务端也是通过controller获取
    // Set/get timeout in milliseconds for the RPC call. Use
    // ChannelOptions.timeout_ms on unset.
    void set_timeout_ms(int64_t timeout_ms);
    int64_t timeout_ms() const { return _timeout_ms; }
需要设置上FLAGS_baidu_std_protocol_deliver_timeout_ms这个flag

**Comment by vinllen** [comment]
@yanglimingcn 你的意思是客户端设置以后，服务端通过Controller.timeout_ms()获取超时值，然后起一个本地的定时器判断超时吗？

**Comment by yanglimingcn** [comment]
> @yanglimingcn 你的意思是客户端设置以后，服务端通过Controller.timeout_ms()获取超时值，然后起一个本地的定时器判断超时吗？

是这样的，brpc的timer就是这样的作用，只是在客户端是集成在内部的，服务端要自己根据情况使用。

**Comment by vinllen** [comment]
> > @yanglimingcn 你的意思是客户端设置以后，服务端通过Controller.timeout_ms()获取超时值，然后起一个本地的定时器判断超时吗？
> 
> 是这样的，brpc的timer就是这样的作用，只是在客户端是集成在内部的，服务端要自己根据情况使用。

了解了，谢谢

**Comment by qingwen220** [comment]
> 服务端也是通过controller获取 // Set/get timeout in milliseconds for the RPC call. Use // ChannelOptions.timeout_ms on unset. void set_timeout_ms(int64_t timeout_ms); int64_t timeout_ms() const { return _timeout_ms; } 需要设置上FLAGS_baidu_std_protocol_deliver_timeout_ms这个flag 这是一个超时时间，是相对时间，比如500ms等。

@yanglimingcn  这个是那个版本开始支持的呢，我这边本地用的版本告知 timeout_ms() 是 client-side. methods，服务端使用行为是未定义的。我测试验证确实server端也拿不到 client 端设置的 timeout.

**Comment by yanglimingcn** [comment]
> > 服务端也是通过controller获取 // Set/get timeout in milliseconds for the RPC call. Use // ChannelOptions.timeout_ms on unset. void set_timeout_ms(int64_t timeout_ms); int64_t timeout_ms() const { return _timeout_ms; } 需要设置上FLAGS_baidu_std_protocol_deliver_timeout_ms这个flag 这是一个超时时间，是相对时间，比如500ms等。
> 
> @yanglimingcn 这个是那个版本开始支持的呢，我这边本地用的版本告知 timeout_ms() 是 client-side. methods，服务端使用行为是未定义的。我测试验证确实server端也拿不到 client 端设置的 timeout.

FLAGS_baidu_std_protocol_deliver_timeout_ms看一下这个选项，得打开它。

**Comment by qingwen220** [comment]
> > > 服务端也是通过controller获取 // Set/get timeout in milliseconds for the RPC call. Use // ChannelOptions.timeout_ms on unset. void set_timeout_ms(int64_t timeout_ms); int64_t timeout_ms() const { return _timeout_ms; } 需要设置上FLAGS_baidu_std_protocol_deliver_timeout_ms这个flag 这是一个超时时间，是相对时间，比如500ms等。
> > 
> > @yanglimingcn 这个是那个版本开始支持的呢，我这边本地用的版本告知 timeout_ms() 是 client-side. methods，服务端使用行为是未定义的。我测试验证确实server端也拿不到 client 端设置的 timeout.
> 
> FLAGS_baidu_std_protocol_deliver_timeout_ms看一下这个选项，得打开它。

我在client这边设置了 true，还是没有效果，这个是需要client 和 server端都打开？
