### ISSUE TITLE
使用cmake编译example出现大量 undefined错误

### ISSUE THREAD

**Issue by cmdmspaint** [apache/brpc#2226]
gcc版本8.3.0
brpc版本1.4.0
protobuf版本2.5.0
gflag版本2.2.1
leveldb版本1.18

这是cmake编译信息
![image](https://user-images.githubusercontent.com/50624748/235044542-b7370430-10c7-4863-b9e4-a2a5e6d21dd1.png)
但是在执行make的时候就出现了大量的undefine问题
![image](https://user-images.githubusercontent.com/50624748/235043301-d815dde6-94b6-4069-b9f0-9351e1c3d430.png)
![image](https://user-images.githubusercontent.com/50624748/235043391-e5697a7d-48de-405d-a4c7-503f54a07ba2.png)

**Comment by wwbmmm** [comment]
编译选项加上-D_GLIBCXX_USE_CXX11_ABI=0试试

**Comment by zhouhuahui** [comment]
请问这个问题解决了吗，我也出现了
