### ISSUE TITLE
brpc最大并发度bug，max_concurrency打满，流量停止后没有降下来

### ISSUE THREAD

**Issue by lyh123456** [apache/brpc#2227]
**Describe the bug (描述bug)**

brpc最大并发度bug，max_concurrency打满，流量停止后没有降下来
压测交高流量，并发度打满，流量停止后，并发度没有下降，服务无法访问
ELIMIT	2004	是	同时处理的请求数超过ServerOptions.max_concurrency了	"Reached server's limit=%d on concurrent requests"

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
可以提供解决方式

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by lyh123456** [comment]
@jamesge

**Comment by Zhihan-Lu** [comment]
请问这个问题后来是如何修复的？我们也遇到了类似的情况。
