### ISSUE TITLE
DynamicPartitionChannel [R1][E112]Fail to select channel, Host is down

### ISSUE THREAD

**Issue by xiedeacc** [apache/brpc#2239]
**Describe the bug (描述bug)**
服务的brpc使用了DynamicPartitionChannel， 服务运行几个小时候就会出现，[E112]Fail to select channel, Host is down [R1][E112]Fail to select channel, Host is down，只要不重启，就会一直完全连不上下游服务，重启后又能正常运行几个小时。下游服务一直运行正常，所以看起来是brpc客户端的bug。

**Versions (各种版本)**
OS:ubuntu18.04
Compiler:gcc11.3.0
brpc:1.3.0
protobuf:3.19.2

服务有多台机器，不会同时出现这个报错，也可以印证不是下游服务的问题，所以和https://github.com/apache/brpc/issues/1572 应该不是同一个问题

**Comment by TousakaRin** [comment]
有没有可以复现的代码呢

**Comment by xiedeacc** [comment]
看起来目前的会导致死锁 https://github.com/apache/brpc/issues/2259
