### ISSUE TITLE
咨询：请问brpc的start方法支持一个端口同时指定多个ip吗？

### ISSUE THREAD

**Issue by fsilent** [apache/brpc#2245]
brpc start方法不指定ip启动时，默认是0.0.0.0 ip。
请问brpc的start方法支持一个端口同时指定多个ip吗？如既指定本机ip，又指定127.0.0.1

**Comment by chenBright** [comment]
可以起多个server，每个server指定特定的ip

**Comment by fsilent** [comment]
多谢回复，我本意是想在一个进程里可以通过多个ip访问，但又不是监听全网ip。 后面没找到对应的方法，在客户端里把127.0.0.1的ip改成本机ip了

**Comment by chenBright** [comment]
可以在同一个进程内起多个server。https://github.com/apache/brpc/blob/master/docs/cn/server.md#%E7%9B%91%E5%90%AC%E5%A4%9A%E4%B8%AA%E7%AB%AF%E5%8F%A3
