### ISSUE TITLE
bthread 如何保证coredump下的正确 bt

### ISSUE THREAD

**Issue by athree** [apache/brpc#2268]
可能是一个基础问题

假如现在有4个pthread(A-D)，10个bthread(1-10)，bth1-4 在 pthA上(不考虑stolen)，其中bth1 中 segfault 触发 coredump，这个时候coredump一定是 bth1 的 context吗？是否会因为 user 侧的 scheduler 导致 coredump bt 回溯的是 bth2-3的 context？

如果不会，这个是怎么保障的呢？

**Comment by athree** [comment]
感谢

**Comment by TousakaRin** [comment]
如果coredump那么一定是bth1的context，除非栈溢出等原因导致指针写飞了。coredump天然就是这样的吧，会保存当前运行的上下文。
