### ISSUE TITLE
Grpc 向 Brpc迁移遇到的问题

### ISSUE THREAD

**Issue by 982945902** [apache/brpc#2286]
**Describe the bug (描述bug)**
client,server都采用h2:grpc协议，client请求server直连一切正常, 但是通过nginx转发会有一半出错, 请教下原因, 报错如下

upstream sent invalid http2 table index: 63 while reading response header from upstream
upstream sent invalid header while reading response header from upstream
错误码502 bad gate way

**To Reproduce (复现方法)**
必现
**Expected behavior (期望行为)**
正常通过

**Versions (各种版本)**
OS:ubuntu1~22.04
Compiler:gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
brpc:brpc-1.4.0
protobuf:protobuf-3.19.4

**Additional context/screenshots (更多上下文/截图)**
![image](https://github.com/apache/brpc/assets/49055103/42d89d0d-96f7-44c7-9dc9-1c5dd7c7afa8)

**Comment by jiangdongzi** [comment]
同遇到

**Comment by jiangdongzi** [comment]
https://github.com/apache/brpc/issues/2176

**Comment by 982945902** [comment]
> 同遇到

你可以看下我fork 的分支， 暂时规避了这个问题 https://github.com/982945902/brpc/tree/a1

**Comment by 982945902** [comment]
https://trac.nginx.org/nginx/ticket/1538
