### ISSUE TITLE
Fail to open rdma device(容器里跑rdma)

### ISSUE THREAD

**Issue by riverzhang** [apache/brpc#2298]
**Describe the bug (描述bug)**
https://github.com/apache/brpc/blob/release-1.5/src/brpc/rdma/rdma_helper.cpp#L405C29-L405C53

**To Reproduce (复现方法)**
# cat job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: my-image
        command: ["my-command"]
        args: ["my-argument"]
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        volumeMounts:
        - name: infiniband
          mountPath: /dev/infiniband
      restartPolicy: Never
      volumes:
      - name: infiniband
        hostPath:
          path: /dev/infiniband

**Expected behavior (期望行为)**
可以发现rdma设备

**Versions (各种版本)**
OS: centos7
Compiler:
brpc: release-1.5
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Tuvie** [comment]
这个应该是容器有什么资源没有透进来或者是权限不对。可以在容器里面尝试strace运行一下，看看哪里fail了

**Comment by Tuvie** [comment]
可以按照提示把这些用到的文件的权限给加上

**Comment by riverzhang** [comment]
这个怎么加

**Comment by Tuvie** [comment]
这个请参考些容器方面的资料吧。不属于brpc问题了

**Comment by riverzhang** [comment]
容器里加特权，目前是我发现一种方法。 还有其它权限开小点的方法吗

**Comment by riverzhang** [comment]
使用device-plugin可以解决。

**Comment by Tuvie** [comment]
> 使用device-plugin可以解决。

OK

**Comment by yanglimingcn** [comment]
请问容器里面使用rdma，容器的网络配置方式有啥要注意的吗？桥接（bridge）、主机网络（Host）、Macvlan 网络
