### ISSUE TITLE
config_brpc.sh 从LIBS_IN中寻找protoc报错找不到

### ISSUE THREAD

**Issue by highkic** [apache/brpc#2300]
**Describe the bug (描述bug)**
config_brpc.sh 中从LIBS_IN中寻找protoc, 是不是不太对呀，正常protoc不会再/usr/bin或者/usr/local/bin中么
find_bin() {
    TARGET_BIN=$(find -L ${LIBS_IN} -type f -name "$1" 2>/dev/null | head -n1)
    if [ ! -z "$TARGET_BIN" ]; then
        $ECHO $TARGET_BIN
    else
        which "$1" 2>/dev/null
    fi
}
find_bin_or_die() {
    TARGET_BIN=$(find_bin "$1")
    if [ ! -z "$TARGET_BIN" ]; then
        $ECHO $TARGET_BIN
    else
        >&2 $ECHO "Fail to find $1"
        exit 1
    fi
}

**To Reproduce (复现方法)**
执行 config_brpc.sh
报错Fail to find protoc

**Expected behavior (期望行为)**
/usr/bin中有protoc，不应该报错Fail to find protoc

**Versions (各种版本)**
OS: linux 
Compiler: gcc 7.3.1
brpc: 1.4.0
protobuf: 3.6.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by wasphin** [comment]
优先使用 LIBS_IN 下的的 protoc，如果没有的话会找系统中的`which protoc`，这里要确认下 `which protoc` 是不是存在。

**Comment by highkic** [comment]
如你所说，我check了下镜像里没有which工具，所以报了问题，get
