### ISSUE TITLE
Socket::Revive为什么对socket引用次数+1

### ISSUE THREAD

**Issue by cooper-zhzhang** [apache/brpc#2305]
**Describe the bug (描述bug)**
最近在整体细读brpc的代码，但是有个位置的代码不太理解。
在如果一个socket的链接出现问题，就会对该socket开启健康检测。
如果检测成功，该socket又可以使用了，此时会调用Socket::Revive。
在Revive总会把socket的引用次数进行一次+1。这个是什么原因，进入Socket::Revive时引用次数为2，离开该函数时引用次数为3。
![image](https://github.com/apache/brpc/assets/16239579/8e964714-cbb4-4b9b-8628-2054e75e111a)

**To Reproduce (复现方法)**
无

**Expected behavior (期望行为)**
无

**Versions (各种版本)**
OS: debian
Compiler: g++
brpc: 1.1
protobuf: 2

**Additional context/screenshots (更多上下文/截图)**
无

**Comment by chenBright** [comment]
https://github.com/apache/brpc/blob/e4abb3fab3bacbbf127dcda553ddc6b67a2a0888/src/brpc/socket.cpp#L676-L682
`Create()`的时候，Socket持有了一个引用计数（`additional ref`）。

https://github.com/apache/brpc/blob/e4abb3fab3bacbbf127dcda553ddc6b67a2a0888/src/brpc/socket.cpp#L995-L997
`SetFailed`的时候，Socket会减去`additional ref`。

所以`Revive()`的时候，引用计数需要+1，表示持有`additional ref`。

https://github.com/apache/brpc/blob/e4abb3fab3bacbbf127dcda553ddc6b67a2a0888/src/brpc/details/health_check.cpp#L161-L162
而健康检查持有的引用计数，会在健康检查结束的时候释放。
