### ISSUE TITLE
centos 7.6.1810编译异常报错

### ISSUE THREAD

**Issue by lyykjen** [apache/brpc#2307]
**Describe the bug (描述bug)**
按照[Fedora/CentOS](https://github.com/apache/brpc/blob/master/docs/cn/getting_started.md#fedoracentos)编译安装步骤，执行make失败报错

**To Reproduce (复现方法)**
按照上述步骤编译在centos7.4编译brpc

**Expected behavior (期望行为)**
编译通过，可以使用

**Versions (各种版本)**
OS:centos 7.6.1810
Compiler: gcc 4.8.5 
brpc: git clone master 
protobuf: 

**Additional context/screenshots (更多上下文/截图)**
![image](https://github.com/apache/brpc/assets/22764583/a535c110-79c8-44cd-98ab-d5dfbadbb852)

**Comment by lyykjen** [comment]
使用brpc 1.5.0版本即可解决问题

**Comment by Kegem0** [comment]
我也有同样的问题，并且用的是release -1.5.0的版本，依然没有解决这个问题。
我在各个centos7的虚拟机下，重复试验都是遇到一样的问题，用了master分支下的代码，也用了1.6.0，用了bprc网站上下载的tar包，最后都终止于这个错误。
