### ISSUE TITLE
brpc支持http服务的流式响应

### ISSUE THREAD

**Issue by highkic** [apache/brpc#2311]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
brpc支持http服务的流式响应么？
看了下文档中流式rpc, 也是支持server端支持client端流式多批次写入
并且需要使用baidu_std协议
```
目前Stream都由Client端建立。Client先在本地创建一个Stream，再通过一次RPC（必须使用baidu_std协议）与指定的Service建立一个Stream，如果Service在收到请求之后选择接受这个Stream， 那在response返回Client后Stream就会建立成功。过程中的任何错误都把RPC标记为失败，同时也意味着Stream创建失败。用linux下建立连接的过程打比方，Client先创建[socket](http://linux.die.net/man/7/socket)（创建Stream），再调用[connect](http://linux.die.net/man/2/connect)尝试与远端建立连接（通过RPC建立Stream），远端[accept](http://linux.die.net/man/2/accept)后连接就建立了（service接受后创建成功）。
```
**Describe the solution you'd like (描述你期望的解决方法)**
1. 想跟brpc维护的同学高效咨询明确下当前brpc是否能满足基于http协议，流式响应的需求
2. 如果支持，希望给一些更详细的demo，如果不支持，是否考虑支持

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
目前http client支持[持续下载](https://github.com/apache/brpc/blob/master/docs/cn/http_client.md#%E6%8C%81%E7%BB%AD%E4%B8%8B%E8%BD%BD)、http service支持[持续发送](https://github.com/apache/brpc/blob/master/docs/cn/http_service.md#%E6%8C%81%E7%BB%AD%E5%8F%91%E9%80%81)。

**Comment by highkic** [comment]
@chenBright 有demo的示例吗？

**Comment by highkic** [comment]
在你明确的回复后，找到此处的示例demo，https://github.com/apache/brpc/blob/master/example/http_c%2B%2B/http_server.cpp#L102C30-L102C57 
感谢

**Comment by chenBright** [comment]
https://github.com/apache/brpc/blob/af899d7b7e985886f5ac3fb71077c664e88e7da0/test/brpc_http_rpc_protocol_unittest.cpp#L530-L541

也可以看看UT
