### ISSUE TITLE
现在为什么不支持rdma多网卡

### ISSUE THREAD

**Issue by Jiaao-Bai** [apache/brpc#2321]
想了解下具体因为什么原因导致支持rdma多网卡不在计划之中

**Comment by Jiaao-Bai** [comment]
@Tuvie 老板求看看，，我想改一下这块，不知道具体成本有多少，不太敢动

**Comment by Tuvie** [comment]
之前的场景没有这块需求，所以暂时没在计划中。
如果要改这块，需要启用多个设备对应的ibv_context、ibv_pd等，并且iobuf内存应该在多个设备上同时注册。
具体每个Socket创建的时候，需要根据路由确定其QP从哪个设备创建出来。

**Comment by Jiaao-Bai** [comment]
感谢老板！

**Comment by YanLongDai** [comment]
@Jiaao-Bai 多网卡支持有什么解决方案吗？感觉做的方向类似，能否加个联系方式？我weixin：13323815576
