### ISSUE TITLE
comile warning as error, -Waddress

### ISSUE THREAD

**Issue by zhyq0520** [apache/brpc#2331]
**Describe the bug (描述bug)**
cmake编译出现-Waddress ，被当做error 编译失败

**To Reproduce (复现方法)**
cmake && make

**Expected behavior (期望行为)**

消除warning
**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

/root/3rd/brpc/src/butil/endpoint.cpp:394:25: warning: the address of ‘int bthread_connect(int, const sockaddr*, socklen_t)’ will never be NULL [-Waddress]
  394 |     if (bthread_connect != NULL) {
      |                         ^
/root/3rd/brpc/src/butil/endpoint.cpp:46:16: note: ‘int bthread_connect(int, const sockaddr*, socklen_t)’ declared here
   46 | int BAIDU_WEAK bthread_connect(

**Comment by Huixxi** [comment]
是在什么平台编译的？

**Comment by zhyq0520** [comment]
> 

解决了，我改了CMakeLists.txt引入的
3q~
