### ISSUE TITLE
服务超时后，产生大量的close_wait

### ISSUE THREAD

**Issue by dandyhuang** [apache/brpc#2353]
请教一个问题，线上没有开启熔断，但connect的超时时间，大于rpc的超时时间， 服务发现用的是consul。现在发现当下游服务请求超时的时候，返回错误码1008，过了一段时间是会零星的返回E110(Fail to connect Socket)和[E101]Fail to connect Socket。还会有[E112]Fail to select server from consul://xxx报错。服务产生大量的close_wait。  使用的是rr负载，链接方式使用pool。

**Comment by lorinlee** [comment]
什么版本的brpc

**Comment by feng-y** [comment]
@dandyhuang 这个问题后面解决了么？

**Comment by dandyhuang** [comment]
> @dandyhuang 这个问题后面解决了么？

没有，brpc的老问题了，说新版本修复了，但是好像还是很多人反馈有这个问题
