### ISSUE TITLE
grpc客户端访问brpc，如何拿response_attachment

### ISSUE THREAD

**Issue by historyliao** [apache/brpc#2359]
[issuse 1158中有人问了](https://github.com/apache/brpc/issues/1158)
但是没有从根本上回答这个问题，如果不是http协议呢？如果就是grpc协议呢？是不是其它协议不能获取response_attachment?

**Comment by wwbmmm** [comment]
grpc协议不支持附件，所以是无法用grpc客户端获取到response_attachment的
