### ISSUE TITLE
done_guard.release() 相关疑问

### ISSUE THREAD

**Issue by tkzky** [apache/brpc#2379]
官方文档中关于 done_guard.release() 的描述：
异步Service中，退出服务回调时请求未处理完成，done->Run()不应被调用，done应被保存下来供以后调用，乍看起来，这里并不需要用ClosureGuard。但在实践中，异步Service照样会因各种原因跳出回调，如果不使用ClosureGuard，一些分支很可能会在return前忘记done->Run()，所以我们也建议在异步service中使用done_guard，**与同步Service不同的是，为了避免正常脱离函数时done->Run()也被调用，你可以调用done_guard.release()来释放其中的done。**
而在brpc/exapmle/asynchronous_echo_c++/server.cpp 中，并未调用 done_guard.release()？

**Comment by chenBright** [comment]
这个demo中，client发起异步rpc，Service不是异步的。

https://github.com/apache/brpc/blob/5dc6562049390ac2e25c044f5b975b01022b80f1/example/asynchronous_echo_c%2B%2B/client.cpp#L96-L101

**Comment by tkzky** [comment]
> 

感谢您的回答，请问example中有异步service的例子吗？

**Comment by chenBright** [comment]
这个example用了异步service
https://github.com/apache/brpc/blob/5dc6562049390ac2e25c044f5b975b01022b80f1/example/session_data_and_thread_local/server.cpp#L171-L182

**Comment by tkzky** [comment]
> 这个example用了异步service
> 
> https://github.com/apache/brpc/blob/5dc6562049390ac2e25c044f5b975b01022b80f1/example/session_data_and_thread_local/server.cpp#L171-L182

好的，我看下，多谢您的回答！
