### ISSUE TITLE
长期未访问，再次访问抛出E112 Not Connectted错误

### ISSUE THREAD

**Issue by WonderLiu96** [apache/brpc#2384]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
在这样一个场景中，client使用`CONNECTION_TYPE_SINGLE`建立channel与server通信。当client长时间没有和server通信（超过server端配置的`idle_timeout_s`），之后cient再次访问时，抛出E112 Not Connectted的错误。

在我们的场景中，存在很多这样的低频访问，我们不想把这个错误抛出来，是否存在某种机制可以检查这样的情况？

**Describe the solution you'd like (描述你期望的解决方法)**
我看了brpc是存在健康检查的，但是它的健康检查机制也是先抛出错误再进行check，而且是使用`Connect()`重新建立，不太符合我们的需求。另一种方式是想着捕获这个错误，但是看了官方文档，会有很多情况出现E112，不知道有没有更细致的错误码？

**Describe alternatives you've considered (描述你想到的折衷方案)**
目前我们折衷的方案是调大`idle_timeout_s`的值来暂时规避

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
使用ip:port还是名字访问server？

**Comment by WonderLiu96** [comment]
> 使用ip:port还是名字访问server？

是用ip:port访问的server，在client中还用缓存了channel。

**Comment by chenBright** [comment]
server断开连接，client需要经过HealthCheck才能恢复对这个server的正常访问。

**Comment by chenBright** [comment]
改用CONNECTION_TYPE_POOLED应该可以避免这个问题

**Comment by WonderLiu96** [comment]
> 改用CONNECTION_TYPE_POOLED应该可以避免这个问题

使用连接池的话，我看文档的描述
```
当连接池中的某个连接在-idle_timeout_second时间内没有读写，则被视作“闲置”，会被自动关闭。默认值为10秒。此功能只对连接池(pooled)有效。打开-log_idle_connection_close在关闭前会打印一条日志。
```
仍然是会有个"闲置"的关闭时间，我们的场景有很多客户端，有一些访问很惰性，感觉这个还是没法满足😂。

**Comment by WonderLiu96** [comment]
> > server断开连接，client需要经过HealthCheck才能恢复对这个server的正常访问。
> 
> 嗯，这个我看了是在`SetFailed()`里面启动的，那目前brpc是没有其他的类似保活的机制吗？

其实我们场景的需求就是想着把这种错误在我们程序内部给消化掉，不暴露给用户，要是能有一个特定的错误码能够唯一标识这种情况就好了

**Comment by chenBright** [comment]
池里的连接是不会进行HealthCheck，所以不会出现关闭空闲连接导致112的问题的。

**Comment by WonderLiu96** [comment]
> 池里的连接是不会进行HealthCheck的，所以不会出现关闭空闲连接导致112的问题的。

那链接关闭了，我可以通过什么感知？因为当我访问server时，若关闭了，我需要内部重试

**Comment by chenBright** [comment]
空闲关闭的，还需要感知吗？

**Comment by WonderLiu96** [comment]
> 空闲关闭的，还需要感知和重试吗？

可能我没有表达清楚，我意思是client通过缓存的channel和server通信，但是在一次通信之后，长时间未通信，连接被server关闭。关闭后，client再发送请求，就会得到E112。而这个错误只需要等HealthCheck之后重试就行了，我们的需求是在我们这一层是要作为SDK给用户使用，所以这种错误我们想能够精确知道，然后内部直接重试吞掉。但E112看文档有很多原因可能导致，因此我们想能不能有其他精确的定位这个错误的方式。

**Comment by chenBright** [comment]
使用CONNECTION_TYPE_POOLED的话，空闲关闭后，会直接丢掉这个连接，下一次就会新建连接的，不会出现关闭空闲连接导致112的问题的。

**Comment by WonderLiu96** [comment]
> 使用CONNECTION_TYPE_POOLED的话，空闲关闭后，会直接丢掉这个连接。下一次rpc时，池会新建连接的，所以不会出现关闭空闲连接导致112的问题的。

好的，谢谢大佬解答，我们评估一下。

**Comment by chenBright** [comment]
SingleServer场景下，只要到server的Socket Failed了且没恢复，就会出现112了
https://github.com/apache/brpc/blob/0ef35f3498dbfbdef3d8dcda62e815c1b1e06d37/src/brpc/controller.cpp#L1045-L1055

而POOLED下，连续n次连接超时，会将main Socket SetFailed
https://github.com/apache/brpc/blob/0ef35f3498dbfbdef3d8dcda62e815c1b1e06d37/src/brpc/socket.cpp#L1469-L1480

https://github.com/apache/brpc/blob/0ef35f3498dbfbdef3d8dcda62e815c1b1e06d37/src/brpc/controller.cpp#L737-L745
