### ISSUE TITLE
brpcStream服务端如何主动发送数据给客户端

### ISSUE THREAD

**Issue by foreverneverer** [apache/brpc#2391]
当客户端建立好stream并且服务端accept后，希望服务端立即可以使用streamID进行回传stream。但是目前好像需要客户端再writeStream，然后服务端在onMessage中writeStream进行回传。

怎么可以在建立链接后，服务端单向传输数据给客户端呢？

**Comment by wwbmmm** [comment]
服务端accept之后就用streamID进行Write不行吗？

**Comment by foreverneverer** [comment]
> 服务端accept之后就用streamID进行Write不行吗？

抱歉，可以的。代码的BUG，已经修复，多谢！
