### ISSUE TITLE
singleserver模式下重试没有检测socket是不是变成了可连接状态

### ISSUE THREAD

**Issue by huocun-ant** [apache/brpc#2395]
**Describe the bug (描述bug)**
A B两方，都是singleServer模式，配置了重试，A先起来，向B发送消息，此时B还没起来，A进入重试，在A重试期间，启动B，此时socket应该可以连接了，但是A还是在一直重试，直到最大重试次数，Send失败。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
在B起来后A在重试期间应该能够感知B起来了，退出重试。

**Versions (各种版本)**
OS: Linux
Compiler: GCC
brpc: brpc-1.6.0
protobuf:

**Additional context/screenshots (更多上下文/截图)**
![image](https://github.com/apache/brpc/assets/131865681/f620fc16-1226-488b-8a97-d8144a7c15a4)
上图是达到了最大重试次数，Send失败，
<img width="596" alt="image" src="https://github.com/apache/brpc/assets/131865681/ebba7a7b-64fd-4501-b76d-07666b908658">
在这个流程中才发现socket可用了，这个时候send已经失败了。

**Comment by chenBright** [comment]
Socket HealthCheck还没成功，就不会恢复Socket。这个场景下，重试期间基本上不会成功的了。

使用CONNECTION_TYPE_POOLED看看，cntl->set_connection_type(brpc::CONNECTION_TYPE_POOLED)

**Comment by huocun-ant** [comment]
> Socket HealthCheck还没成功，就不会恢复Socket。这个场景下，重试期间基本上不会成功的了。
> 
> 使用CONNECTION_TYPE_POOLED看看，cntl->set_connection_type(brpc::CONNECTION_TYPE_POOLED)

使用pool也是一样，现象还是在重试期间没有运行HealthCheck，即使对端起来，本端socket还是报`Not connected`.

**Comment by chenBright** [comment]
这个场景下，pool不会HealthCheck，每次都是建新连接发请求。这说明了B的端口还不通吧

**Comment by chenBright** [comment]
可以使用[重试退避](https://github.com/apache/brpc/blob/master/docs/cn/client.md#%E9%87%8D%E8%AF%95%E9%80%80%E9%81%BF)，让A能等一小段时间再重试，这样B起来的概率大一些。

**Comment by huocun-ant** [comment]
> 可以使用[重试退避](https://github.com/apache/brpc/blob/master/docs/cn/client.md#%E9%87%8D%E8%AF%95%E9%80%80%E9%81%BF)，让A能等一小段时间再重试，这样B起来的概率大一些。

都是有的，每次重试等一秒，可以确定的是在A重试的时候B起来了，但是A依然重试了20多次。

**Comment by chenBright** [comment]
看看使用pool的日志？
也是connection refuse吗？

**Comment by huocun-ant** [comment]
> 看看使用pool的日志？ 也是connection refuse吗？

![image](https://github.com/apache/brpc/assets/131865681/97c41db2-e0b4-4858-a7a2-fa5cf2e75b9d)

**Comment by chenBright** [comment]
> 这个场景下，pool不会HealthCheck，每次都是建新连接发请求。这说明了B的端口还不通吧

记错了，ECONNREFUSED也会HealthCheck。

**Comment by chenBright** [comment]
看原问题的日志，HealthCheck是在rpc失败后才启动的，不像有重试退避。

**Comment by huocun-ant** [comment]
> 看原问题的日志，HealthCheck是在rpc失败后才启动的，不像有重试退避。

是的，我也觉得奇怪的点是重试期间没有发现对端起来。我是重定义的`GetBackoffTimeMs `,时间是一秒，`CanRetryBackoffInPthread`返回的也是`true`.

**Comment by wwbmmm** [comment]
> > 看原问题的日志，HealthCheck是在rpc失败后才启动的，不像有重试退避。
> 
> 是的，我也觉得奇怪的点是重试期间没有发现对端起来。我是重定义的`GetBackoffTimeMs `,时间是一秒，`CanRetryBackoffInPthread`返回的也是`true`.

是不是超时设置太短了？如果Retry backoff时间大于超时时间，则Retry backoff不生效

**Comment by huocun-ant** [comment]
> > > 看原问题的日志，HealthCheck是在rpc失败后才启动的，不像有重试退避。
> > 
> > 
> > 是的，我也觉得奇怪的点是重试期间没有发现对端起来。我是重定义的`GetBackoffTimeMs `,时间是一秒，`CanRetryBackoffInPthread`返回的也是`true`.
> 
> 是不是超时设置太短了？如果Retry backoff时间大于超时时间，则Retry backoff不生效

![image](https://github.com/apache/brpc/assets/131865681/3bde38f2-2865-47ae-bc65-3b91c933febb)
不会，ni'ke'yi你可以看看这个图，超时之前重试了很多次了，我设置的超时时间是backoff的40倍

**Comment by wwbmmm** [comment]
default_brpc_retry_policy.cc 你这个重试是在上层做的吧？是每次都重新初始化一个Channel吗？

**Comment by huocun-ant** [comment]
> default_brpc_retry_policy.cc 你这个重试是在上层做的吧？是每次都重新初始化一个Channel吗？

https://github.com/secretflow/yacl/blob/main/yacl/link/transport/default_brpc_retry_policy.cc

**Comment by wwbmmm** [comment]
找到原因了。
要使Socket进入健康检查流程，首先要满足引用计数=2，在这里的WaitAndReset方法，会一直循环等待引用计数=2
https://github.com/apache/brpc/blob/master/src/brpc/details/health_check.cpp#L190

但是在这个issue的场景中，引用计数一直是3，导致无法进入健康检查流程。
这三个引用分别来自：
1. SocketMap对Socket的引用。参考：https://github.com/apache/brpc/blob/master/src/brpc/socket_map.cpp#L258
2. 健康检查流程对Socket的引用。参考：https://github.com/apache/brpc/blob/master/src/brpc/details/health_check.cpp#L78
3. Socket连接流程对Socket的引用。参考：https://github.com/apache/brpc/blob/master/src/brpc/socket.cpp#L1382

这里不正常的是第3个引用，按理说连接失败之后这个引用就应该释放，从代码上看，在连接失败后，会回调到
Socket::AfterAppConnected，在这个方法里，创建了一个SocketUniquePtr，当AfterAppConnected方法返回时这个SocketUniquePtr就会自动析构，释放引用计数
https://github.com/apache/brpc/blob/master/src/brpc/socket.cpp#L1469

但在这个问题中，实际的调用链是这个样的：
Socket::AfterAppConnected
-> Socket::ReleaseAllFailedWriteRequests
-> Socket::ReturnFailedWriteRequest
-> bthread_id_error2
-> Controller::HandleSocketFailed
-> Controller::OnVersionedRPCReturned
-> Controller::IssueRPC (重试)
-> Controller::HandleSendFailed
-> Controller::OnVersionedRPCReturned
…… （不断重试，直至重试耗尽）

由于Controller一直在递归的重试，导致Socket::AfterAppConnected方法无法退出，从而无法释放引用计数。
当重试次数耗尽后，Socket::AfterAppConnected方法退出，Socket的引用计数恢复成2，才开始进入健康检查。

**Comment by wwbmmm** [comment]
> 由于Controller一直在递归的重试，导致Socket::AfterAppConnected方法无法退出，从而无法释放引用计数。
> 当重试次数耗尽后，Socket::AfterAppConnected方法退出，Socket的引用计数恢复成2，才开始进入健康检查。

这个问题还有一个更严重的后果，Socket::AfterAppConnected追溯到更上层的调用来自EventDispatcher的回调，也就是说Controller递归重试把EventDispatcher阻塞了，无法再响应其它的EventDispatcher事件
在brpc的设计中，bthread_id和bthread_timer的回调函数里都不应该有阻塞性的调用。但是RetryBackoffPolicy和用户自定义RetryPolicy的引入会破坏这个原则，所以解决方案是新起一个bthread来执行包含RetryPolicy的相关逻辑，见PR #2419

**Comment by huocun-ant** [comment]
> > 由于Controller一直在递归的重试，导致Socket::AfterAppConnected方法无法退出，从而无法释放引用计数。
> > 当重试次数耗尽后，Socket::AfterAppConnected方法退出，Socket的引用计数恢复成2，才开始进入健康检查。
> 
> 这个问题还有一个更严重的后果，Socket::AfterAppConnected追溯到更上层的调用来自EventDispatcher的回调，也就是说Controller递归重试把EventDispatcher阻塞了，无法再响应其它的EventDispatcher事件 在brpc的设计中，bthread_id和bthread_timer的回调函数里都不应该有阻塞性的调用。但是RetryBackoffPolicy和用户自定义RetryPolicy的引入会破坏这个原则，所以解决方案是新起一个bthread来执行包含RetryPolicy的相关逻辑，见PR #2419

所以这个修改一举两得啊，哈哈
