### ISSUE TITLE
网卡和交换机的mtu会影响brpc的latency吗？是否可以设置brpc发包使用的mtu？

### ISSUE THREAD

**Issue by Funlxy** [apache/brpc#2396]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Tuvie** [comment]
mtu是网卡的设置，作为一个应用层程序，brpc本身没有能力设置mtu。如有root权限，可以直接在系统里设置

**Comment by Funlxy** [comment]
> mtu是网卡的设置，作为一个应用层程序，brpc本身没有能力设置mtu。如有root权限，可以直接在系统里设置

感谢您的回答。因为在RDMA环境下，好像是可以通过代码指定对应的MTU（但也必须网卡和交换机支持所设置的MTU)。所以并不知道在非RDMA环境下是否设置了网卡和交换机的MTU后是否还需在代码层面指定。

**Comment by Tuvie** [comment]
rdma允许给一个qp设置mtu。这个和tcp场景不一样。tcp的程序是没有设置mtu能力的
