### ISSUE TITLE
安全漏洞反馈【细节已删除】

### ISSUE THREAD

**Issue by l1ubai** [apache/brpc#2401]
【细节已删除】

**Comment by wwbmmm** [comment]
问题已收到。请勿在公开页面讨论安全漏洞。反馈渠道：https://www.apache.org/security/

**Comment by l1ubai** [comment]
> 问题已收到。请勿在公开页面讨论安全漏洞。反馈渠道：https://www.apache.org/security/

Sorry, it has been submitted to security@apache.org.
