### ISSUE TITLE
mbvar如何清空所有的lable

### ISSUE THREAD

**Issue by qqwangxiaow** [apache/brpc#2404]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

我定义了一个mbvar, 不断向里面添加数据, 一段时间窗口内想统计一次并清空, 目前有啥好点的方法吗
 bvar::MultiDimension<bvar::Adder<int> > g_request_count("request_count", {"idc", "method", "status"});

**Comment by serverglen** [comment]
MultiDimension类里面有一个[delete_stats](https://github.com/apache/brpc/blob/master/src/bvar/multi_dimension.h#L133)方法，不过目前是private的。

**Comment by qqwangxiaow** [comment]
看着得把bvar直接干掉替换一个了

**Comment by serverglen** [comment]
> 看着得把bvar直接干掉替换一个了

刚提了个PR，增加一个clear_stats方法 #2407

**Comment by serverglen** [comment]
> 看着得把bvar直接干掉替换一个了

#2407 已合入

**Comment by qqwangxiaow** [comment]
感谢!

> > 看着得把bvar直接干掉替换一个了
> 
> #2407 已合入
