### ISSUE TITLE
dump http请求

### ISSUE THREAD

**Issue by hejingzhilian** [apache/brpc#2423]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
http 支持rpc_dump 否？ 
我用master分支， 编译example/http_c++ 
启动命令

`./http_server -rpc_dump=true -rpc_dump_dir=./rpc_data/rpc_dump/`

发现用curl 和 http_client 的命令都不dump 请求，排查源码 发下卡在 method->input_type()->field_count() 这一行了，

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
目前只支持 http 协议接收 rpc方式的请求 (请求body能转为protobuf message）的rpc dump。如果是example/http_c++里那种纯http的请求还不支持

**Comment by hejingzhilian** [comment]
好吧
