### ISSUE TITLE
Fail to wait EPOLLOUT of fd=17215: Connection timed out [110]

### ISSUE THREAD

**Issue by kobebryantlin0** [apache/brpc#2426]
**Describe the bug (描述bug)**
Fail to wait EPOLLOUT of fd=17215: Connection timed out [110]

**To Reproduce (复现方法)**
链接一直不释放

**Expected behavior (期望行为)**
正常

**Versions (各种版本)**
OS: CentOS7
Compiler:
brpc: 0.9.5
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
连接超时有可能是因为网络延时或者对端服务器繁忙，也有可能是因为客户端cpu负载过高

**Comment by TousakaRin** [comment]
可以尝试增加event_dispather线程数量看看，机器是否繁忙可以观察cpu使用和worker_usage，或者看看这个错误能否通过压测复现。

**Comment by endlesscyl** [comment]
大佬，这个问题最后是怎样解决的？
