### ISSUE TITLE
http持续发送功能，curl客户端不是持续接收和显示

### ISSUE THREAD

**Issue by zhaocc1106** [apache/brpc#2436]
**Describe the bug (描述bug)**
https://github.com/apache/brpc/blob/master/example/http_c%2B%2B/http_server.cpp
启动上述example样例测试服务持续发送时，使用curl命令和chrome浏览器请求发现不是持续接收的，而是最后一起显示出来。

启动一个如下flask服务对比是没问题的：
```
from flask import Flask, Response
import time

app = Flask(__name__)

@app.route('/stream')
def stream():
    def generate():
        for i in range(10000):
            yield f"Number: {i}\n" # 每次生成一行数据并发送给客户端
            time.sleep(0.01)
    return Response(generate(), mimetype='text/plain') # 返回一个流式响应

if __name__ == '__main__':
    app.run()
```

**To Reproduce (复现方法)**
1. 启动样例https://github.com/apache/brpc/blob/master/example/http_c%2B%2B/http_server.cpp
2. 使用curl命令访问：curl -v http://0.0.0.0:8010/FileService/largefile

**Expected behavior (期望行为)**
持续接收到一部分内容并显示。

**Versions (各种版本)**
OS: Ubuntu 18.04.5 LTS \n \l
Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
brpc: 1.6.0
protobuf: libprotoc 3.9.2

**Additional context/screenshots (更多上下文/截图)**

**Comment by zhaocc1106** [comment]
可以帮忙看看吗？

**Comment by thorneliu** [comment]
> 可以帮忙看看吗？

你有抓包看看吗

**Comment by zhaocc1106** [comment]
> > 可以帮忙看看吗？
> 
> 你有抓包看看吗

没有呢，但是这个问题是必现的，您那边是正常的现象还是和我的现象一样呢？

**Comment by zhaocc1106** [comment]
解决了，curl带上--no-buffer参数，或者返回字符串块加上换行结尾就可以了。
