### ISSUE TITLE
brpc是不是不支持oneway调用

### ISSUE THREAD

**Issue by tmacjay2015** [apache/brpc#2448]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

xx
**Describe the solution you'd like (描述你期望的解决方法)**

xx
**Describe alternatives you've considered (描述你想到的折衷方案)**
xx

**Additional context/screenshots (更多上下文/截图)**
xx

**Comment by Huixxi** [comment]
你是指异步调用么？可以描述下使用场景

**Comment by tmacjay2015** [comment]
> 你是指异步调用么？可以描述下使用场景

rpc请求发出后 客户端不需要等待回复 （服务端也不需要回复）

**Comment by jiangdongzi** [comment]
> > > 你是指异步调用么？可以描述下使用场景
> > 
> > 
> > rpc请求发出后 客户端不需要等待回复 （服务端也不需要回复）
> 
> 看下bRPC异步调用的文档，传一个回调函数 Done，我理解就可以满足你这种使用场景

但是这样, 服务端还是需要回复

**Comment by wwbmmm** [comment]
是的，不支持oneway调用
