### ISSUE TITLE
docker容器中单连接转发rpc夯住

### ISSUE THREAD

**Issue by chongg039** [apache/brpc#2453]
**Describe the bug (描述bug)**

我们有一个场景是在容器中启动A和B两个服务，其中A在收到客户端请求后会建立到B的单连接，访问B的数据后返回给客户端，其中A访问B的过程是一个同步rpc。

我们在部分线上环境遇到了很奇怪的现象，即从客户端发起对A的访问后会hang住不返回，有以下调查：
1. A和B在同一个容器中，端口互相能ping通
2. 直接curl访问B的服务，正常。通过A转发访问B hang住不返回
3. 抓包发现只有tcp三次握手的报文，没有数据报文
4. 重启A和B均无效果
5. 没有任何iptables的配置
6. gdb A查看发现是hang在这里：IssueRPC认为已经成功（虽然网卡上没有包），Join不到对应的id：
![image](https://github.com/apache/brpc/assets/18239939/b094741d-8672-44d2-a1b6-fd30c382ac6e)
![image](https://github.com/apache/brpc/assets/18239939/ecd8ea59-c982-4d25-9199-6f2bc881b307)
此时也不触发超时机制，一直不会退出

目前该问题还没有进一步的调查结论。想先问一下各位有遇到过类似现象的问题吗，感谢。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc: release-1.5
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by chongg039** [comment]
这里打码一下：对应的tcp连接已经是建立好的，从connections页面上看起来也有，只是protocol貌似不是baidustd：
![image](https://github.com/apache/brpc/assets/18239939/4e28e73a-0dff-407c-96aa-e5ac476ff6d2)
![image](https://github.com/apache/brpc/assets/18239939/1c77a801-1cf7-4ee4-9d81-a219c1b5d036)

**Comment by sinomiko** [comment]
以前遇到过卡死的case ，cntl 如果是复用的，没有reset ，就会卡死

**Comment by FancyJan** [comment]
没有发起rpc的cntl直接join会卡死

**Comment by chongg039** [comment]
@sinomiko @FancyJan 这两个场景都不是。后来调查了一下，现场是一个8核的vm，就开了9个pthread worker。我们的程序后台有一些bthread task，有的地方还混用了pthread lock的逻辑，猜测应该是哪里的代码有点问题，没有worker来干活了。通过调大pthread数，或者关闭那些后台的task，都不会再次出现。准备详细调查一下相关的代码实现，看看是不是写挫了。

**Comment by FancyJan** [comment]
> @sinomiko @FancyJan 这两个场景都不是。后来调查了一下，现场是一个8核的vm，就开了9个pthread worker。我们的程序后台有一些bthread task，有的地方还混用了pthread lock的逻辑，猜测应该是哪里的代码有点问题，没有worker来干活了。通过调大pthread数，或者关闭那些后台的task，都不会再次出现。准备详细调查一下相关的代码实现，看看是不是写挫了。

我好像也碰到过这种，在bthread上使用pthread锁可能会有问题：例如一个读写锁的场景，写线程持有锁被切换到后台，此时所有的worker如果刚好都在读同一把锁被阻塞，就没有worker去释放写锁了。
可以试一下换成bthread::Mutex，或者开启--usercode_in_pthread=true看看还会不会卡住。

**Comment by chongg039** [comment]
> > @sinomiko @FancyJan 这两个场景都不是。后来调查了一下，现场是一个8核的vm，就开了9个pthread worker。我们的程序后台有一些bthread task，有的地方还混用了pthread lock的逻辑，猜测应该是哪里的代码有点问题，没有worker来干活了。通过调大pthread数，或者关闭那些后台的task，都不会再次出现。准备详细调查一下相关的代码实现，看看是不是写挫了。
> 
> 我好像也碰到过这种，在bthread上使用pthread锁可能会有问题：例如一个读写锁的场景，写线程持有锁被切换到后台，此时所有的worker如果刚好都在读同一把锁被阻塞，就没有worker去释放写锁了。 可以试一下换成bthread::Mutex，或者开启--usercode_in_pthread=true看看还会不会卡住。

是的，其实我们之前出现过好几个类似的问题，但是由于确实对bthread了解的不够深，这次在网卡上没收到包的时候其实压根没往这里想，还是心血来潮尝试调大一下worker数才发现的。后来看了下其实文档里面已经提到过了：
![image](https://github.com/apache/brpc/assets/18239939/b9ffa3dd-e29c-4495-84d3-0d36c2c2b47e)
这个场景恰好比较特殊，只有8个核，其他线上的机器核数都比较多，恰好没出现过此类问题。
