### ISSUE TITLE
bthread在持有了pthread的锁之后，如果遇到bthread_sleep的调用，是否会切换工作线程？？

### ISSUE THREAD

**Issue by weingithub** [apache/brpc#2456]
**Describe the bug (描述bug)**

bthread在A线程中持有了pthread_mutex的锁 L1，之后执行了好几层的业务调用逻辑（可能有bthread_sleep调用），在unlock L1时，触发了pthread不一致的assert，导致程序出core

**To Reproduce (复现方法)**
在bthread中对pthread_mutex加锁，之后调用bthread_sleep，再unlock时，增加pthread一致性的检查

**Expected behavior (期望行为)**
pthread一致？

**Versions (各种版本)**
OS: centos
Compiler:  gcc 4.8
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

想知道，在这种情况下，在bthread_sleep之后，是否有可能会发生工作线程的切换？？
@leaf-potato @wanglun

**Comment by chenBright** [comment]
调用bthread_sleep时，bthread会被挂起，等时间到了，会随机选择一个worker线程来调度该bthread，这时候可能已经切换了worker线程了。所以，使用bthread时，不能在pthread锁临界区内执行会挂起bthread的操作（bthread_mutex、rpc、bthread_usleep等）。否则，会导致死锁或者其他未定义行为。

**Comment by weingithub** [comment]
> 大概率会。因为调用bthread_sleep时，bthread会被挂起，等时间到了，会随机选择一个worker线程来调度该bthread，这时候可能已经切换了worker线程了。 所以，使用bthread时，不能在pthread锁临界区内执行会挂起bthread的操作（bthread_mutex、rpc、bthread_usleep等）。否则，会导致死锁或者其他未定义行为。
非常感谢你的回答，我看https://www.iquanku.com/read/brpc-0.9.7-zh/adb9e61c135a61a7.md这个链接里面的描述的话，好像是如果在bthread中调用pthread_mutex_lock的话，如果是等待拿锁，那么这个时候，bthread是不会切换工作线程的。不知道是不是可以这么理解？
![a1](https://github.com/apache/brpc/assets/8966017/64799a34-6f2d-4fca-86cd-2bb7980085b4)

还有个就是，brpc为什么也会导致bthread协程切换？

**Comment by weingithub** [comment]
> 不能在pthread锁临界区内执行会挂起bthread的操作（bthread_mutex、rpc、bthread_usleep等）

不能在pthread锁临界区内执行会挂起bthread的操作（bthread_mutex、rpc、bthread_usleep等）。这个rpc不是指brpc吗？

**Comment by chenBright** [comment]
> > 不能在pthread锁临界区内执行会挂起bthread的操作（bthread_mutex、rpc、bthread_usleep等）
> 
> 不能在pthread锁临界区内执行会挂起bthread的操作（bthread_mutex、rpc、bthread_usleep等）。这个rpc不是指brpc吗？

是的。异步rpc应该不会有问题，同步rpc在发完数据后，会调用bthread::Join等回包，会挂起bthread。
https://github.com/apache/brpc/blob/806f4d46c9393f6aeb92aa558d95fe95d1784355/src/brpc/channel.cpp#L576-L587

**Comment by weingithub** [comment]
> > > 不能在pthread锁临界区内执行会挂起bthread的操作（bthread_mutex、rpc、bthread_usleep等）
> > 
> > 
> > 不能在pthread锁临界区内执行会挂起bthread的操作（bthread_mutex、rpc、bthread_usleep等）。这个rpc不是指brpc吗？
> 
> 是的。异步rpc应该不会有问题，同步rpc在发完数据后，会调用Join等回包，会挂起bthread。
> 
> https://github.com/apache/brpc/blob/806f4d46c9393f6aeb92aa558d95fe95d1784355/src/brpc/channel.cpp#L576-L587

谢谢啦。

**Comment by jinshuai86** [comment]
> > 如果在bthread中调用pthread_mutex_lock的话，如果是等待拿锁，那么这个时候，bthread是不会切换工作线程的。不知道是不是可以这么理解？
> 
> 是的

想问下，如果 bthread 只是调用阻塞 pthread 的 API（read、write），在 bthread 和 pthread 等待期间或者被唤醒后，会触发当前 bthread 切换到其它 pthread 吗？
