### ISSUE TITLE
在大流量下，消息大，下游hang住情况下，内存暴涨

### ISSUE THREAD

**Issue by sinomiko** [apache/brpc#2457]
**Describe the bug (描述bug)**
如标题：
k8s部署，使用jemalloc 5.3.0，在突发大流量下2000qps, 下游hang住后，服务会内存突然上涨并直到oom。

流量下降后，concurrency 最大800，恢复到2，查看了下socket iobuf，也会恢复正常。

看了下brpc有些使用的是object pool，怀疑在这里。
```
WriteRequest* req = butil::get_object<WriteRequest>();
```

能否在brpc上增加一个接口，将object pool信息导出到metrics接口，或者bvar上

**To Reproduce (复现方法)**

服务开启了snappy压缩；
基本消息都很大，大多超过100K

**Expected behavior (期望行为)**
流量恢复后，concurrency，mem恢复正常。

**Versions (各种版本)**
OS:Ubuntu 20.04.3
Compiler:clang : "8.0"
brpc:1.4.0|HEAD|cfa1800
protobuf:3.15.8

**Additional context/screenshots (更多上下文/截图)**
![image](https://github.com/apache/brpc/assets/12888642/8539d257-b031-4057-a35f-941871019cca)
![image](https://github.com/apache/brpc/assets/12888642/97057863-d507-4b57-ac22-d6d8e22e00b9)
![image](https://github.com/apache/brpc/assets/12888642/90bcc584-82b3-41d3-9920-fbbb699452d6)
![image](https://github.com/apache/brpc/assets/12888642/dc331350-6181-4cbb-80a9-192d45c327b7)

![image](https://github.com/apache/brpc/assets/12888642/8cf5858b-a5d4-4464-8531-f8117efc6cb4)

**Comment by sinomiko** [comment]
最初怀疑是`SharedObject` `IOBuf`导致:

加了全局兼容`SharedObject`个数监控，申请和释放都是正常的。
`IOBuf` 这块从已有监控看也是释放了的。


从heap profile看是arena 有大量内存没有释放，排查protobuf有个类似问题
[memory leak in PackFrom() on arena-allocated Any objects](https://github.com/protocolbuffers/protobuf/issues/8264)

找到一个可以[优化的地方](https://github.com/apache/brpc/issues/2466)
先关掉这个卡

**Comment by imdouyu** [comment]
这个问题有结论吗
