### ISSUE TITLE
RDMA build失败

### ISSUE THREAD

**Issue by r-value** [apache/brpc#2478]
**Describe the bug (描述bug)**
当前（2023.12.25）版本的master代码在 `WITH_RDMA=ON` 时无法build

**To Reproduce (复现方法)**
```
git checkout master
mkdir build && cd build
cmake -DWITH_RDMA=ON ..
make
```
![image](https://github.com/apache/brpc/assets/30104163/440ad807-41d2-4321-b446-1a843aea2d19)

**Expected behavior (期望行为)**
正常build

**Versions (各种版本)**
brpc: master 2023.12.25

**Additional context/screenshots (更多上下文/截图)**
根据 git blame 信息，接口变动为 #2358 引入
cc PR author @yanglimingcn

**Comment by yanglimingcn** [comment]
我修改一下
