### ISSUE TITLE
怎么理解这段汇编？

### ISSUE THREAD

**Issue by Huoke** [apache/brpc#2489]
**Describe the bug (描述bug)**
```c++
inline Atomic32 Barrier_AtomicIncrement(volatile Atomic32* ptr, Atomic32 increment)
{
  Atomic32 temp = increment;
  __asm__ __volatile__("lock; xaddl %0,%1"
                       : "+r" (temp), "+m" (*ptr)
                       : : "memory");
  // temp now holds the old value of *ptr
  if (AtomicOps_Internalx86CPUFeatures.has_amd_lock_mb_bug) {
      __asm__ __volatile__("lfence" : : : "memory");
  }
  return temp + increment;
}
```
上面的代码中内联汇编原子交换和相加，temp保存的是旧的*ptr中的值，那么*ptr中保存的是不是相加后的值？
内联汇编这里的输出操作数这里看不懂，求解惑
**To Reproduce (复现方法)**
null
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc: 1.0.0-rc02
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by TousakaRin** [comment]
看了看文档，我尝试翻译一下:
- [lock](https://www.felixcloutier.com/x86/lock) 前缀表示后续的指令是原子操作
- [xaddl src dst](https://www.felixcloutier.com/x86/xadd):  等价于: temp = src + dst; src = dst; dst = temp; 也就是 fetch_add。
- `+r (temp), +m(*ptr)`， 这一句是表明这段汇编代码的输出操作数，也就是这个汇编代码会改变的变量，其中 temp 由编译器选一个寄存器保存，记为%0，*ptr 则需要直接访问内存，记为 %1
- `lock xaddl %0, %1`，这里注意gcc的汇编语法第一个数是src操作数，intel语法第一个是dst操作数。所以 %0 对应xaddl 指令中的src, %1 对应 dst

综上所述，这段汇编代码翻译过来就是
```c++
Atomic32 temp = increment;

// 以下三行是原子操作
Atomic32 asm_temp = temp + *ptr;
temp = *ptr;
*ptr = asm_temp;

return temp + increment
```
所以说，ptr 中保存的就是相加后的值。对gcc内嵌汇编也不是特别熟悉，有错误欢迎指正。

**Comment by Huixxi** [comment]
From gpt：
这段代码使用了GCC的内联汇编。`__asm__ __volatile__` 是 GCC 的内联汇编语句，其中 `__volatile__` 表示编译器在优化时不要移动这段汇编代码的位置，以避免可能的副作用。
"lock; xaddl %0,%1" 是 x86 指令，`xaddl` 是原子交换并加的操作，`lock` 是一个前缀，保证了这个指令在多核环境下的原子性。
`"+r" (temp), "+m" (*ptr)` 是内联汇编的输入/输出操作数部分。
"+"表示这个操作数既是输入又是输出，"r"表示将`temp`放入一个寄存器中，"m"表示`*ptr`是一个内存位置。
在执行`xaddl`指令后，`temp`和`*ptr`的值会互换，然后`*ptr`会增加`temp`的值。所以，`temp`现在保存的是`*ptr`原来的值，而`*ptr`保存的是相加后的值。
至于`AtomicOps_Internalx86CPUFeatures.has_amd_lock_mb_bug`和`lfence`，它们是处理一些特定的CPU bug。`lfence`是一个内存屏障指令，确保某些CPU在执行`lock`指令时不会出现预期之外的行为。
最后，函数返回的是`temp + increment`，即原始的`*ptr`值加上增量。

`xaddl` 是 x86 汇编语言中的一条指令，它是 "exchange and add" 的缩写。这条指令将两个操作数相加，并将结果存储在第二个操作数所指定的位置。同时，它将第二个操作数原来的值存储在第一个操作数所指定的位置。这是一个原子操作，也就是说，在多线程环境中，这个操作是不可中断的。这使得 `xaddl` 指令在实现某些并发算法，如计数器或互斥锁等，时非常有用。
`xaddl` 指令的工作原理可以简化为以下几步：
1. 将两个操作数相加。
2. 将结果存储在第二个操作数所指定的位置。
3. 将第二个操作数原来的值存储在第一个操作数所指定的位置。
这个过程是原子的，也就是说，一旦开始就不会被其他线程中断。这就确保了在多线程环境中，不会出现两个线程同时修改同一块内存的情况。
例如，如果我们有一个 `xaddl` 指令如下：
```asm
xaddl %eax, (%ebx)
```
在这个指令执行之后，`%ebx` 所指向的内存位置的值会增加 `%eax` 的值，而 `%eax` 则会得到 `%ebx` 所指向的内存位置原来的值。
