### ISSUE TITLE
bthread可以只在特定的pthread_worker上执行吗？

### ISSUE THREAD

**Issue by MJY-HUST** [apache/brpc#2507]
pthread_worker所在的pthread上有一个thread_local变量。现在，我想启用一个周期性执行的bthread，其绑定一个固定的pthread，负责处理pthread_local变量，请问bthread目前支持这种场景吗？

**Comment by MJY-HUST** [comment]
场景是：server中会处理一些io任务。每个pthread worker维护一个thread local IO_uring实例用于提交和收割IO，使用server收到rpc请求后直接基于bthread来处理，此时，对于每个pthread worker想维护一个定时任务，用于提交请求。

**Comment by chenBright** [comment]
目前应该没法支持绑定处理请求的worker pthread。

**Comment by yanglimingcn** [comment]
> 场景是：server中会处理一些io任务。每个pthread worker维护一个thread local IO_uring实例用于提交和收割IO，使用server收到rpc请求后直接基于bthread来处理，此时，对于每个pthread worker想维护一个定时任务，用于提交请求。 如果可以直接在server 处理逻辑对应的pthread上执行绑定的bthread任务，可以避免额外线程的创建

为啥要一个定时器提交请求，收到rpc请求，直接提交到当前thread local的io_uring就可以了吧

**Comment by MJY-HUST** [comment]
> > 场景是：server中会处理一些io任务。每个pthread worker维护一个thread local IO_uring实例用于提交和收割IO，使用server收到rpc请求后直接基于bthread来处理，此时，对于每个pthread worker想维护一个定时任务，用于提交请求。 如果可以直接在server 处理逻辑对应的pthread上执行绑定的bthread任务，可以避免额外线程的创建
> 
> 为啥要一个定时器提交请求，收到rpc请求，直接提交到当前thread local的io_uring就可以了吧

说错了，是收割请求。整体的逻辑是提交请求后让bthread sleep，然后收割请求后使用bthread_t来唤醒sleep的bthread继续执行。想让每个task group 所在的pthread固定周期执行收割请求的任务。

**Comment by yanglimingcn** [comment]
> > > 场景是：server中会处理一些io任务。每个pthread worker维护一个thread local IO_uring实例用于提交和收割IO，使用server收到rpc请求后直接基于bthread来处理，此时，对于每个pthread worker想维护一个定时任务，用于提交请求。 如果可以直接在server 处理逻辑对应的pthread上执行绑定的bthread任务，可以避免额外线程的创建
> > 
> > 
> > 为啥要一个定时器提交请求，收到rpc请求，直接提交到当前thread local的io_uring就可以了吧
> 
> 说错了，是收割请求。整体的逻辑是提交请求后让bthread sleep，然后收割请求后使用bthread_t来唤醒sleep的bthread继续执行。想让每个task group 所在的pthread固定周期执行收割请求的任务。

你专门启动一个专门的协程收割都有io_uring的请求？

**Comment by yanglimingcn** [comment]
> > io_uring
> 
> > > > > 场景是：server中会处理一些io任务。每个pthread worker维护一个thread local IO_uring实例用于提交和收割IO，使用server收到rpc请求后直接基于bthread来处理，此时，对于每个pthread worker想维护一个定时任务，用于提交请求。 如果可以直接在server 处理逻辑对应的pthread上执行绑定的bthread任务，可以避免额外线程的创建
> > > > 
> > > > 
> > > > 为啥要一个定时器提交请求，收到rpc请求，直接提交到当前thread local的io_uring就可以了吧
> > > 
> > > 
> > > 说错了，是收割请求。整体的逻辑是提交请求后让bthread sleep，然后收割请求后使用bthread_t来唤醒sleep的bthread继续执行。想让每个task group 所在的pthread固定周期执行收割请求的任务。
> > 
> > 
> > 你专门启动一个专门的协程收割都有io_uring的请求？
> 
> 如果IO_uring是thread_local的话，协程如果收割要io_uring，则必须运行在对应的task group中，但是目前的协程可能会被其他task group steal。 所以除非把IO_uring设置为全局的，然后再使用一个协程/线程来处理收割逻辑？ 如果基于bthread的task group来做的话，不太清楚是否有可行的方法

thread local的指针可以存到一个全局数组中，那个专门的协程可以得到所以io_uring
