### ISSUE TITLE
Support protobuf 22+

### ISSUE THREAD

**Issue by Superskyyy** [apache/brpc#2537]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
The current bRPC cannot compile with a protobuf runtime v22.0+

**Describe the solution you'd like (描述你期望的解决方法)**
This issue is mainly due to the backwards-incompatible changes introduced by abseil logging, the current brpc still uses the old logging stubs which are removed by protobuf since v22.0. Not sure if there are other changes needed. https://protobuf.dev/support/migration/#abseil

**Describe alternatives you've considered (描述你想到的折衷方案)**
Currently I have to downgrade my protobuf used by other dependencies to match bRPC, this is not an ideal solution in the long run. Any help is greatly appreciated.

**Additional context/screenshots (更多上下文/截图)**

**Comment by ketor** [comment]
希望可以早日支持protobuf v22.0+
