### ISSUE TITLE
疑似DoublyBufferedData::WrapperTLSGroup一处笔误

### ISSUE THREAD

**Issue by shanhe72101** [apache/brpc#2561]
**Describe the bug (描述bug)**

代码位置src/butil/containers/doubly_buffered_data.h

template <typename T, typename TLS, bool AllowBthreadSuspended>
class DoublyBufferedData<T, TLS, AllowBthreadSuspended>::WrapperTLSGroup {
public:
    const static size_t RAW_BLOCK_SIZE = 4096;
    const static size_t ELEMENTS_PER_BLOCK = (RAW_BLOCK_SIZE + sizeof(T) - 1) / sizeof(T);

上一行两处sizeof(T)应该改为sizeof(DoublyBufferedData::Wrapper)

Wrapper类定义增加BAIDU_CACHELINE_ALIGNMENT修饰

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
欢迎提PR
