### ISSUE TITLE
CentOS编译失败，openssl版本问题

### ISSUE THREAD

**Issue by missximon** [apache/brpc#2585]
make
[ 11%] Built target PROTO_LIB
[ 44%] Built target BUTIL_LIB
[ 94%] Built target SOURCES_LIB
[ 94%] Built target brpc-static
[ 94%] Built target protoc-gen-mcpack
[ 95%] Linking CXX executable ../../output/bin/parallel_http
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `brpc::SetSSLOptions(ssl_ctx_st*, std::string const&, int, brpc::VerifyOptions const&)':
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:400: undefined reference to `SSL_CTX_set_options'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `SSLGetDH1024':
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:713: undefined reference to `BN_get_rfc2409_prime_1024'
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:731: undefined reference to `DH_set0_pqg'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `SSLGetDH2048':
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:736: undefined reference to `BN_get_rfc3526_prime_2048'
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:754: undefined reference to `DH_set0_pqg'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `SSLGetDH4096':
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:759: undefined reference to `BN_get_rfc3526_prime_4096'
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:777: undefined reference to `DH_set0_pqg'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `SSLGetDH8192':
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:782: undefined reference to `BN_get_rfc3526_prime_8192'
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:800: undefined reference to `DH_set0_pqg'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `sk_GENERAL_NAME_num':
/usr/local/include/openssl/x509v3.h:166: undefined reference to `OPENSSL_sk_num'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `sk_GENERAL_NAME_value':
/usr/local/include/openssl/x509v3.h:166: undefined reference to `OPENSSL_sk_value'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `sk_GENERAL_NAME_pop_free':
/usr/local/include/openssl/x509v3.h:166: undefined reference to `OPENSSL_sk_pop_free'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `brpc::CreateServerSSLContext(std::string const&, std::string const&, brpc::ServerSSLOptions const&, std::string const*, std::vector<std::string, std::allocator<std::string> >*)':
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:519: undefined reference to `TLS_server_method'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `brpc::Print(std::ostream&, x509_st*, char const*)':
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:871: undefined reference to `X509_getm_notBefore'
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:873: undefined reference to `X509_getm_notAfter'
../../output/lib/libbrpc.a(ssl_helper.cpp.o): In function `brpc::CreateClientSSLContext(brpc::ChannelSSLOptions const&)':
/home/siwei.zm/brpc/src/brpc/details/ssl_helper.cpp:481: undefined reference to `TLS_client_method'
../../output/lib/libbrpc.a(dh.cpp.o): In function `brpc::policy::DHWrapper::copy_public_key(char*, int*) const':
/home/siwei.zm/brpc/src/brpc/policy/dh.cpp:56: undefined reference to `DH_get0_key'
../../output/lib/libbrpc.a(dh.cpp.o): In function `brpc::policy::DHWrapper::do_initialize()':
/home/siwei.zm/brpc/src/brpc/policy/dh.cpp:94: undefined reference to `BN_get_rfc2409_prime_1024'
/home/siwei.zm/brpc/src/brpc/policy/dh.cpp:112: undefined reference to `DH_set0_pqg'
../../output/lib/libbrpc.a(dh.cpp.o): In function `brpc::policy::DHWrapper::initialize(bool)':
/home/siwei.zm/brpc/src/brpc/policy/dh.cpp:41: undefined reference to `DH_get0_key'
../../output/lib/libbrpc.a(global.cpp.o): In function `brpc::GlobalInitializeOrDieImpl()':
/home/siwei.zm/brpc/src/brpc/global.cpp:349: undefined reference to `OPENSSL_init_ssl'
/home/siwei.zm/brpc/src/brpc/global.cpp:351: undefined reference to `OPENSSL_init_ssl'
collect2: error: ld returned 1 exit status
make[2]: *** [output/bin/parallel_http] Error 1
make[1]: *** [tools/parallel_http/CMakeFiles/parallel_http.dir/all] Error 2
make: *** [all] Error 2

有人遇到过这种报错吗？看起来像是版本问题？但是替换了好几个openssl版本，都没有成功
一天了都没成功，有木有大佬可以直接提供一个编译镜像啊呜呜呜呜呜

**Comment by aMagicNeko** [comment]
我也是，解决了吗哥
