### ISSUE TITLE
限制同一个进程内不同 server 能够使用的实际 worker 数量

### ISSUE THREAD

**Issue by zhengJade** [apache/brpc#2597]
**描述**

brpc 自带的 ServerOptions 中 num_threads 是一个 hint，建议 server 使用的 worker数量，对于同一个进程内存在多个 brpc server 的情况，这些 server 实际是共享 worker 的 
![image](https://github.com/apache/brpc/assets/30115816/c661b66b-2068-4267-bc1c-ff0a7b2053e0)
那么如果一个 server 是阻塞的，另一个 server 不是，阻塞的 server 用尽了 worker ，非阻塞的由于没有 worker 会造成请求超时。
**需求**
能够限制 server 能够调用的 worker 数量，这样可以保证非阻塞的 server 不会请求超时。

**Comment by yanglimingcn** [comment]
可以不同server使用不同bthread_tag，将不同server线程池分开。
