### ISSUE TITLE
mongo相关的代码是干嘛用的,  看起来没什么用途?

### ISSUE THREAD

**Issue by jiangdongzi** [apache/brpc#2604]
本来想当异步客户端用, 结果发现不是...

**Comment by wwbmmm** [comment]
mongo只实现了服务端的逻辑

**Comment by jiangdongzi** [comment]
> mongo只实现了服务端的逻辑

mongo协议头字段中包含requestId和responseTo字段, 我看global.cpp中配置的mongo客户端时pooled, 为什么不是all呢, 即也支持单链接

**Comment by wwbmmm** [comment]
> 我看global.cpp中配置的mongo客户端时pooled, 为什么不是all呢, 即也支持单链接

没有实现客户端，所以这个配置没啥用吧
