### ISSUE TITLE
目前有对iobuf 进行crc校验、压缩的工具或者方法吗

### ISSUE THREAD

**Issue by cmdmspaint** [apache/brpc#2612]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
iobuf 进行crc校验、压缩

**Comment by cmdmspaint** [comment]
分别在什么场景会使用bigview/smallview

**Comment by TousakaRin** [comment]
smallview 是一个SSO，IOBuf创建的时候默认都是smallview，此时它所引用的BlockRef都直接保存在对象内部的数组里（SmallView::refs)，当这个IOBuf所引用的BlockRef超过这个数组大小时，转而从堆上申请一个数组。这么做的原因猜测是因为存在大量直接在栈上创建的，大小很小的IOBuf，使用SSO可以大量减少malloc的调用次数

**Comment by cmdmspaint** [comment]
如果要获取iobuf中的data 是否可以通过 iobuf的backing_block_num()获取block数量，然后使用backing_block(index)的方式取出iobuf中的所有用户数据呢

**Comment by TousakaRin** [comment]
如果是为了压缩可以参考 brpc/policy/gzip_compress.cpp, 计算crc的话，可以考虑调用IOBuf::copy_to/to_string等接口。直接读取backing_block_num也是可行的，参考IOBuf::copy_to的实现提取数据即可

**Comment by cmdmspaint** [comment]
看了一下 IOBuf::copy_to/to_string会调用memcpy,在不想引入这次内存拷贝的前提下，直接读取backing block是不是一个更好的选择

**Comment by TousakaRin** [comment]
嗯，注意计算偏移量即可，建议如果对性能敏感最好做下benchmark
