### ISSUE TITLE
308 Unknown status code

### ISSUE THREAD

**Issue by zengkui** [apache/brpc#2647]
**Describe the bug (描述bug)**
使用brpc实现了一个http client 发送请求到公司内部的一个web server上 ，同样的这个代码 使用brpc 1.7.0  返回的结果是 [E1010]HTTP/1.1 308 Unknown status code (308)。 而使用brpc 1.1.0 请求是正常的。 

**To Reproduce (复现方法)**
由于这个web server是内部的服务，暂时没法提供公开的可复现的服务。 

**Expected behavior (期望行为)**
想请教下 这个1.7.0 版本的308报错意味什么？ 是有参数设置不合理导致的？ 

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
308是server响应的状态码。如果server响应308状态码的话，http rpc就会失败。这块逻辑没有改动过。
