### ISSUE TITLE
遇到一个编译问题

### ISSUE THREAD

**Issue by yozhao** [apache/brpc#2648]
third_party/brpc-1.9.0/src/brpc/span.h:207:7: error: ‘class brpc::SpanFilter’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class SpanFilter {
       ^~~~~~~~~~
       
       
 说 SpanFilter 没有 virtual destructor。

编译标准差异导致的？

**Comment by TousakaRin** [comment]
应该是编译器版本或者编译选项导致的，欢迎提个PR给他加上一个virtual destructor

**Comment by lorinlee** [comment]
fixed by #2651
