### ISSUE TITLE
leveldb已经老旧化，是否考虑切到rocksdb

### ISSUE THREAD

**Issue by corznoc** [apache/brpc#2652]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
leveldb已经老旧化，是否考虑切到rocksdb

**Describe the solution you'd like (描述你期望的解决方法)**
期待支持切到rocksdb，或者编译时运行不使用leveldb。
如果不使用内建服务，应该不依赖leveldb。

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
目前是生产环境遇到了什么问题吗？

依赖管理角度的话，确实可以支持一个编译参数关闭对leveldb的依赖。

切换rocksdb我觉得需要看看实际的遇到问题是什么，rocksdb确实比leveldb在很多地方都有优化，但也导致了它整个实现是比较复杂的，要看引入的必要性了。在rpcz这个场景我个人觉得leveldb是够用的，切换到rocksdb的好处是什么呢

**Comment by corznoc** [comment]
用的挺好的，没有遇到问题，rocksdb我也觉得复杂了些，只是leveldb公司不让用了😀-------- 原始邮件 --------发件人： LorinLee ***@***.***>日期： 2024年5月29日周三 23:33收件人： apache/brpc ***@***.***>抄送： corznoc ***@***.***>, Author ***@***.***>主    题： Re: [apache/brpc] leveldb已经老旧化，是否考虑切到rocksdb (Issue #2652)
目前是生产环境遇到了什么问题吗？
依赖管理角度的话，确实可以支持一个编译参数关闭对leveldb的依赖。
切换rocksdb我觉得需要看看实际的遇到问题是什么，rocksdb确实比leveldb在很多地方都有优化，但也导致了它整个实现是比较复杂的，要看引入的必要性了。在rpcz这个场景我个人觉得leveldb是够用的，切换到rocksdb的好处是什么呢

**Comment by wwbmmm** [comment]
可以考虑抽象出一个存储接口，默认提供leveldb实现，如果用户有需要可以自己实现这个接口。

**Comment by corznoc** [comment]
好的，多谢。发自我的荣耀手机
