### ISSUE TITLE
bvar::PassiveStatus<std::string> 无法暴露指标

### ISSUE THREAD

**Issue by shishc9** [apache/brpc#2653]
你好，咨询一下 PassiveStatus<std::string> 设计初衷是什么呢，或者针对哪些场景？
根据 [bvar::PassiveStatus\<std::string\>](https://github.com/apache/brpc/blob/master/docs/cn/bvar_c%2B%2B.md#bvarpassivestatus) 文档，process_username 不能作为指标暴露出去，这个特化模板正确使用方法是什么呢？

**Comment by lorinlee** [comment]
这里“作为指标暴露出去”是指期望怎么暴露？使用场景的话，比如可以用builtin service看这个bvar，访问 http://ip:internal_port/vars/process_username 就可以看到这个bvar对应的值。

**Comment by cdjingit** [comment]
> 你好，咨询一下 PassiveStatusstd::string 设计初衷是什么呢，或者针对哪些场景？ 根据 [bvar::PassiveStatus<std::string>](https://github.com/apache/brpc/blob/master/docs/cn/bvar_c%2B%2B.md#bvarpassivestatus) 文档，process_username 不能作为指标暴露出去，这个特化模板正确使用方法是什么呢？
文档中描述的场景比较清楚。不能暴露的原因，如上面所说，因为系统默认已经有一个process_username对应的bvar了

**Comment by j05070415** [comment]
谢谢，您的邮件我已收到！
