### ISSUE TITLE
Is there already any plan about switch bazel workspace to bzlmod?

### ISSUE THREAD

**Issue by oathdruid** [apache/brpc#2654]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
transitive dependency managed in an elegant way, especially when combine with other repo
final user can depend as this exmaple: https://github.com/baidu/babylon/tree/main/example/use-with-bthread
```
# MODULE.bazel
bazel_dep(name = 'abseil-cpp', version = '20210324.2')
bazel_dep(name = 'babylon', version = '1.1.6')
bazel_dep(name = 'brpc', version = '1.9.0')
```

**Describe the solution you'd like (描述你期望的解决方法)**
add MODULE.bazel support and register release to public registry, BCR for example

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
Sorry, at the moment, there are no development plans related to this feature. We are very welcoming of your initiative to submit a Pull Request.

**Comment by oathdruid** [comment]
https://github.com/apache/brpc/pull/2670
@lorinlee try to make one. is there some one could help to review it?

**Comment by chenBright** [comment]
Sorry, I'm not familiar with bazel.

@wwbmmm Is there anyone familiar with bazel who can review it?
