### ISSUE TITLE
variable.cpp   error:  ‘StringFlagDestructor’ does not name a type

### ISSUE THREAD

**Issue by skyflower** [apache/brpc#2679]
centos 8 stream system,   glog version is 0.3.5, gflags version is 1:2.1.2-8.el8 ,  protobuf version 3.5.0
gcc 8.5.0,  linux kernel 4.18.0

compiler step:
1.  make build
2.  cd build
3.  cmake ../ -DWITH_GLOG=ON

![image](https://github.com/apache/brpc/assets/5895849/a8d8befb-9e5a-4b89-94cd-183b9d80ac02)

**Comment by wasphin** [comment]
gflags 2.1 中有一处 namespace 的问题，在 2.2 中修复了，可以升级下

https://github.com/gflags/gflags/commit/408061b46974cc8377a8a794a048ecae359ad887

**Comment by skyflower** [comment]
ok, I'll try it. Thank you for your help.
