### ISSUE TITLE
Questions about idle_timeout_sec of server

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/brpc#2681]
If the server side executes a rpc request for more than idle_timeout_sec, and the connection does not transmit any other rpc during this period, will the connection be closed in this case, causing the rpc request to fail?
Does brpc have other mechanisms like keep alive to clean up unavailable connections instead of using idle_timeout_sec?

related issue: https://github.com/apache/brpc/issues/731

**Comment by chenBright** [comment]
In this case, the connection will be closed until all rpc requests are completed. Idle timeout mechanism only release the additional reference.
