### ISSUE TITLE
brpc AddService 添加的服务实例之间的关系，以及服务实例是否有限制

### ISSUE THREAD

**Issue by yaocunhao** [apache/brpc#2690]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

全局注册一个唯一的server后， 通过server.AddService 将服务器里面添加服务实例，有如下几个疑问请求解答  

1、以什么粒度来划分服务实例？

2、服务实例的数量有限制么
    比如一个业务十个接口，可以提供一个服务实例包含十个接口。也可以写成十个服务实例，每个服务实例一个接口。 这两种实现有差别么(除了维护程度上)

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by GOKINGD** [comment]
个人的理解是，启动一个server可以添加多个service，一个service可以有多个method接口。但是不同service的请求proto是不同的，所以不同proto的service需要单独划分为一个实例，即单独拉一个进程，单独部署。如有不对，望大佬指正~

**Comment by yanglimingcn** [comment]
不同server定义不同端口，现在可以不同server可以指定不同线程池，能起到资源隔离作用。一个server下的多个service共享资源

**Comment by yaocunhao** [comment]
> 不同server定义不同端口，现在可以不同server可以指定不同线程池，能起到资源隔离作用。一个server下的多个service共享资源

感谢解答。 如果是一个server下的多个service 共享资源的话， 对于一个server来说，十个功能写成十个service 和 写成一个service十个接口没什么区别了

**Comment by yanglimingcn** [comment]
> > 不同server定义不同端口，现在可以不同server可以指定不同线程池，能起到资源隔离作用。一个server下的多个service共享资源
> 
> 感谢解答。 如果是一个server下的多个service 共享资源的话， 对于一个server来说，十个功能写成十个service 和 写成一个service十个接口没什么区别了

接口和server层面上有限流功能，service层面上没有。

**Comment by yaocunhao** [comment]
> > > 不同server定义不同端口，现在可以不同server可以指定不同线程池，能起到资源隔离作用。一个server下的多个service共享资源
> > 
> > 
> > 感谢解答。 如果是一个server下的多个service 共享资源的话， 对于一个server来说，十个功能写成十个service 和 写成一个service十个接口没什么区别了
> 
> 接口和server层面上有限流功能，service层面上没有。

如果仅仅启动一个server， 要想限流，是不是说明， 将更多的接口归纳到service中，减少service 数量可能会更好控制

这个限流功能是可配置的么，辛苦指一下道路，我去看看， 再次感谢 ~~

**Comment by yanglimingcn** [comment]
https://github.com/apache/brpc/blob/master/docs/cn/server.md
