### ISSUE TITLE
请问为什么会有 L388 - 391 行的判断，看起来这个函数的第一次执行会没有效果 

### ISSUE THREAD

**Issue by Yxiaoge** [apache/brpc#2691]
https://github.com/apache/brpc/blob/8b5571fdfdc07fb7412404fc912e63e5cae1da7a/src/bthread/bthread.cpp#L388

**Comment by jamesge** [comment]
@yanglimingcn

**Comment by yanglimingcn** [comment]
这个和never_set_bthread_concurrency类似，gflags第一次加载的时候不执行任何操作。
