### ISSUE TITLE
如何通过pprof工具生成火焰图？

### ISSUE THREAD

**Issue by 617076674** [apache/brpc#2694]
在这篇文章（https://brpc.apache.org/zh/docs/builtin-services/cpu_profiler/），介绍了如何进行cpu profile。

但是我折腾了2天时间，没搞定如何用pprof工具生成火焰图。

按照文章里的指示，我得到了类似红框中的文件。

![image](https://github.com/user-attachments/assets/91c78ce4-f79a-422e-9b27-2b33cad400e0)

但是如何把这个文件转变成火焰图呢？网上找了很多资料，都没搞定。

我希望是能在linux服务器上直接生成一个svg文件，然后下载到本地可以用浏览器查看的那种形式。

**Comment by 617076674** [comment]
> 可以考虑用golang带的pprof，可以有个交互式的web，直接就能看到flamegraph
> 
> 本地安装golang，之后执行 go tool pprof -http 127.0.0.1:web_port http://brpc_ip:internal_port/pprof/profile?seconds=30

linux服务器上并没有web浏览器

**Comment by 617076674** [comment]
> 可以考虑用golang带的pprof，可以有个交互式的web，直接就能看到flamegraph
> 
> 本地安装golang，之后执行 go tool pprof -http 127.0.0.1:web_port http://brpc_ip:internal_port/pprof/profile?seconds=30

linux服务器上没有web浏览器，看不了网页。

**Comment by lorinlee** [comment]
@617076674 这个只是启动一个web服务，可以用本地机器访问，和--web参数不一样，可以看看pprof的帮助文档

**Comment by 617076674** [comment]
> @617076674 这个只是启动一个web服务，可以用本地机器访问，和--web参数不一样，可以看看pprof的帮助文档

有没有能直接生成svg文件的方式呢？

**Comment by chenBright** [comment]
https://brpc.apache.org/zh/docs/builtin-services/cpu_profiler/#%E7%81%AB%E7%84%B0%E5%9B%BE

设置好[FlameGraph](https://github.com/brendangregg/FlameGraph)路径后，在cpu内置服务可以选择火焰图展示profile结果。
