### ISSUE TITLE
如何进行流量统计、记录所有请求

### ISSUE THREAD

**Issue by utopia9527** [apache/brpc#2698]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
brpc 服务端层面不能记录所有的流量请求。
举例：
  在访问brpc 服务端时，content-type 不填充 "application/proto"
  客户端可从返回的失败原因中看到 "Fail to parse http body xxx"。但是从服务端角度来说无法对个请求进行埋点统计。也没有输出对应的日志

请问下针对这种请求达到服务端的情况， 有办法让服务侧感知到么。 

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
访问builtin service的web服务，点击status，对应的service应该会显示错误数，这个可以满足需求么

**Comment by yaocunhao** [comment]
> 访问builtin service的web服务，点击status，对应的service应该会显示错误数，这个可以满足需求么

更多是想体现在服务器日志中，或者说能将这个信息返回给业务层来进行统计，做到业务能够有感知

**Comment by wwbmmm** [comment]
现在应该做不到让业务感知

**Comment by chenBright** [comment]
metrics内置服务的信息可以满足需求吗？

**Comment by yaocunhao** [comment]
> metrics内置服务的信息可以满足需求吗？
不太了解这个，请问大佬这个能够将信息透传给服务侧不（不是需要在外部访问内置服务status这种方式）

**Comment by chenBright** [comment]
可以将bvar导出到[文件](https://github.com/apache/brpc/blob/master/docs/cn/bvar.md#%E7%9B%91%E6%8E%A7bvar)或者[Prometheus](https://github.com/apache/brpc/blob/master/docs/cn/bvar.md#%E5%AF%BC%E5%87%BA%E5%88%B0prometheus)。

如果希望在代码中获取这些信息，可以参考继承bvar::Dumper实现一个派生类，参考PrometheusMetricsDumper。
https://github.com/apache/brpc/blob/5ae6ad62b174538a839ceef62644054da4f1960d/src/brpc/builtin/prometheus_metrics_service.cpp#L48-L83

**Comment by utopia9527** [comment]
> 可以将bvar导出到[文件](https://github.com/apache/brpc/blob/master/docs/cn/bvar.md#%E7%9B%91%E6%8E%A7bvar)或者[Prometheus](https://github.com/apache/brpc/blob/master/docs/cn/bvar.md#%E5%AF%BC%E5%87%BA%E5%88%B0prometheus)。
> 
> 如果希望在代码中获取这些信息，可以参考继承bvar::Dumper实现一个派生类，参考PrometheusMetricsDumper。
> 
> https://github.com/apache/brpc/blob/5ae6ad62b174538a839ceef62644054da4f1960d/src/brpc/builtin/prometheus_metrics_service.cpp#L48-L83

感谢~~
