### ISSUE TITLE
半同步半异步rpc在调用brpc::StartCancel之前已经结束，此时调用StartCancel是什么行为

### ISSUE THREAD

**Issue by pirDOL** [apache/brpc#2702]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
通过半同步半异步rpc请求两个下游服务S1和S2，先Join S1，等待其返回后，如果S2有返回则直接使用，否则调用StartCancel不再继续等待S2
目前想通过StartCancel+Join实现对S2的TryJoinOrCancel的语义
那么如果调用StartCancel之前请求S2的rpc已经结束，调用StartCancel(S2)以后，是否会影响S2 Controller的相关内容，比如ErrorCode、Failed状态等

**Describe the solution you'd like (描述你期望的解决方法)**
不涉及

**Describe alternatives you've considered (描述你想到的折衷方案)**
不涉及

**Additional context/screenshots (更多上下文/截图)**
不涉及

**Comment by chenBright** [comment]
rpc结束后，StartCancel不会起作用了。
