### ISSUE TITLE
glog 里面也使用了__thread,  为什么brpc能够兼容？

### ISSUE THREAD

**Issue by yaocunhao** [apache/brpc#2703]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
glog 里面也使用了thread local,  为什么brpc能够兼容。  请问这里做了什么处理

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
具体是什么兼容问题呢？

**Comment by yaocunhao** [comment]
> 具体是什么兼容问题呢？

文档里面不是说brpc不兼容线程本地变量么(切换走再切换回来，可能不再是同一个线程)。 glog里面用了本地线程变量缓存了当前线程的日志，所以想请教下这样为什么能够兼容

**Comment by chenBright** [comment]
glog打日志的时候不会挂起协程，肯定都在同一个线程上的吧。

**Comment by yaocunhao** [comment]
> glog打日志的时候不会挂起协程，肯定都在同一个线程上的吧。

明白了，感谢解答。 顺带请教下协程在那些情况下会切换线程。翻看了以的记录，得知协程会在rpc调用，以及brpc自身的一些挂起操作导致切换线程。想请教下除此之外，还会有其他的非brpc自身功能函数导致切换的情况么。

**Comment by chenBright** [comment]
非brpc自身功能函数不会导致切换。

**Comment by yaocunhao** [comment]
> 非brpc自身功能函数不会挂起协程。

感谢！！
