### ISSUE TITLE
RDMA build failure with 1.10

### ISSUE THREAD

**Issue by Alvicne** [apache/brpc#2706]
Compile failed with RDMA on.
`src/brpc/rdma/rdma_endpoint.cpp:1260:51: error: ‘class brpc::Socket’ has no member named ‘_bthread_tag’; did you mean ‘_read_buf’?`

This field was removed by commit [122355a29e2dd3341ad6f47e17682b482c45b7e4](https://github.com/apache/brpc/commit/122355a29e2dd3341ad6f47e17682b482c45b7e4).

**Comment by wwbmmm** [comment]
@chenBright 看一下，好像是之前的改动不兼容了

**Comment by chenBright** [comment]
@Alvicne 更新master试试
