### ISSUE TITLE
mac 无法自定义 OpenSSL 路径

### ISSUE THREAD

**Issue by lqxhub** [apache/brpc#2714]
https://github.com/apache/brpc/blob/5ae6ad62b174538a839ceef62644054da4f1960d/CMakeLists.txt#L256-L260

在cmake这里, 如果是mac平台,会把 `OPENSSL_ROOT_DIR` 设置为 Homebrew 安装的目录,这时候如果我想自定义 **OpenSSL** 的目录是无效的

**解决办法**

多一个判断,如果通过参数传入了, 就不要再强制修改了, 使用 cmake参数传入的

这个方案是否可行, 如果可行的话 我可以提交PR

**Comment by chenBright** [comment]
欢迎提交PR
