### ISSUE TITLE
RDMA 模块支持 RDMA_READ/RDMA_WRITE 的可行性

### ISSUE THREAD

**Issue by ivanallen** [apache/brpc#2742]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

存储领域，大块 IO，如果能使用 RDMA_READ/RDMA_WRITE 这种单边操作，会节省 cpu，用更少的核达到更高的吞吐。

目前看代码 send/recv 已经是 zero copy，不确定单边操作是否可获得实质性的收益。

**Describe the solution you'd like (描述你期望的解决方法)**

可能可以借鉴 [NVMe/RDMA Transport  spec](https://nvmexpress.org/wp-content/uploads/NVM-Express-RDMA-Transport-Specification-1.0d-2024.07.01-Ratified.pdf) 中描述的架构。

**Comment by yanglimingcn** [comment]
@Tuvie 辛苦评估一下
