### ISSUE TITLE
想问下为什么braft里的单测可以访问私有成员变量？

### ISSUE THREAD

**Issue by a87159909** [apache/brpc#2746]
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/6eaecabe-3c5f-4b08-8934-9d48805c0207">

**Comment by GreateCode** [comment]
参数：-fno-access-control

**Comment by a87159909** [comment]
> 参数：-fno-access-control

具体在哪里使用了呢？我搜索代码貌似没有用到这个参数

**Comment by GreateCode** [comment]
https://github.com/apache/brpc/blob/master/test/BUILD.bazel#L33
