### ISSUE TITLE
能否在cuda编程中直接使用brpc ？

### ISSUE THREAD

**Issue by knightXun** [apache/brpc#2750]
能否在cuda编程中直接使用brpc ？如果可以能否提供一份 demo

**Comment by jamesge** [comment]
cuda代码的host部分就是常规c++程序，应该是可以用的，不过cuda编译器是nvcc，可能会有一些warning或error要处理。

**Comment by knightXun** [comment]
> cuda代码的host部分就是常规c++程序，应该是可以用的，不过cuda编译器是nvcc，可能会有一些warning或error要处理。

能提供一些demo么

**Comment by Huixxi** [comment]
没有这方面的使用demo，可以尝试一下，同步一下验证结果。

**Comment by knightXun** [comment]
> 没有这方面的使用demo，可以尝试一下，最好能同步一下验证结果～
已解决，多谢
