### ISSUE TITLE
Protobuf v5 support

### ISSUE THREAD

**Issue by Tradias** [apache/brpc#2757]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

The brpc vcpkg port depends on protobuf. Since vcpkg maintains a single-version scheme, updating protobuf requires brpc to support it.

**Describe the solution you'd like (描述你期望的解决方法)**

Protobuf v5 support. V4 support can be broken in the process.

**Describe alternatives you've considered (描述你想到的折衷方案)**

Patching brpc, see https://github.com/microsoft/vcpkg/blob/052b06a95da4cee184bab4422e02e7f316055a99/ports/brpc/protobuf.patch

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
cc @wasphin

**Comment by wasphin** [comment]
Just missed this, will try it this weekend, thanks.
