### ISSUE TITLE
Question:How to use the brpc to build my own apps(如何使用brpc构建自己的程序)

### ISSUE THREAD

**Issue by iTomGeller** [apache/brpc#2764]
各位大佬我知道这个问题很trival，但是能力有限还是无法解决所以提了一个issue。

请问如何利用brpc这个库构建一个自己的cpp，具体而言有什么方法可以做到像引入一个第三方头文件```#include<xxx>```这样来调用brpc的方法。

文档里给的都是编译使用给定的example，而似乎没有提及怎么使用brpc写自己的app，还请各位大佬指教。

**Comment by wanghenshui** [comment]
cmake/bazel创建项目引入







ted&nbsp;mostly
---
***@***.***
www.github.com/wanghenshui

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月14日(周六) 凌晨0:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [apache/brpc] Question:How to use the brpc to build my own apps(如何使用brpc构建自己的程序) (Issue #2764)




 
各位大佬我知道这个问题很trival，但是能力有限还是无法解决所以提了一个issue。
 
请问如何利用brpc这个库构建一个自己的cpp，具体而言有什么方法可以做到像引入一个第三方头文件#include<xxx&gt;这样来调用brpc的方法。
 
文档里给的都是编译使用给定的example，而似乎没有提及怎么使用brpc写自己的app，还请各位大佬指教。

**Comment by Lin807188583** [comment]
编译时加上target(cmake --build build --target install)会把对应库加到/usr/local。
然后cmake里面要配置相关链接库 保证能找到
然后自己的项目引入头文件(类似#include <brpc/server.h> ）这样就可以正常使用了。

**Comment by thorneliu** [comment]
```
    && cd ./incubator-brpc \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j8 \
    && make install \
```
用这样的编译命令将brpc安装到系统中。头文件中引用 #include <brpc/server.h> 
Cmake中需要添加选项链接brpc
```
target_link_libraries(${PROJECT_NAME} brpc ...}
```
