### ISSUE TITLE
centos7 gcc4.8.5编译失败

### ISSUE THREAD

**Issue by ugenehan** [apache/brpc#2767]
**Describe the bug (描述bug)**
centos7 gcc4.8.5编译失败

**To Reproduce (复现方法)**

centos7 gcc4.8.5编译
**Expected behavior (期望行为)**

编译成功
**Versions (各种版本)**
OS:centos7.9
Compiler:gcc 4.8.5
brpc:1.10.0
protobuf:3.17

**Additional context/screenshots (更多上下文/截图)**
![image](https://github.com/user-attachments/assets/6b5500da-1f07-4857-bb6f-4d1a2e6dd831)

**Comment by chenBright** [comment]
可以参考 #2307
