### ISSUE TITLE
execution_queue_join安全吗?

### ISSUE THREAD

**Issue by zergvszerg** [apache/brpc#2775]
使用场景是先execution_queue_stop再间隔不定时间execution_queue_join, 但考虑到resource pool会归还使用完的资源, ExecutionQueueId可能会被复用, 那么execution_queue_join就可能等待在一个还没有execution_queue_stop的execution queue上, 从而不安全, 请问有什么好的解决方法?

**Comment by chenBright** [comment]
ExecutionQueueId是是带版本号的（类似[bthread_t](https://github.com/apache/brpc/blob/master/docs/cn/memory_management.md#%E7%94%9F%E6%88%90bthread_t)），归还之后的资源的版本号已经变了，所以execution_queue_join是安全的，不会等其他execution_queue。
