### ISSUE TITLE
mbvar最大的 metric map size可以支持自定义么

### ISSUE THREAD

**Issue by qqwangxiaow** [apache/brpc#2788]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

日志一直在打 ERROR
Too many stats seen, overflow detected, max stats count:20000

看着这个变量是写死的
`constexpr uint64_t MAX_MULTI_DIMENSION_STATS_COUNT = 20000;
`
`        
    if (metric_map_ptr->size() > MAX_MULTI_DIMENSION_STATS_COUNT) {
           LOG(ERROR) << "Too many stats seen, overflow detected, max stats count:" << MAX_MULTI_DIMENSION_STATS_COUNT;
            return nullptr;
 }
`

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
20000条metrics一直会更新吗？有没有已经没用的？

**Comment by qqwangxiaow** [comment]
> 20000条metrics一直会更新吗？有没有已经没用的？

确实有一些是没用的  需要手工删除  但是这个值能不能支持扩展一下呢 有些时候指标确实很多

**Comment by chenBright** [comment]
可以支持。

**Comment by chenBright** [comment]
@qqwangxiaow 加了一个`set_max_stats_count`接口。
