### ISSUE TITLE
[Question] Is it compatible with the Stream feature of gRPC Python client

### ISSUE THREAD

**Issue by zhyncs** [apache/brpc#2791]
Hi bRPC developers @chenBright @wwbmmm @wasphin @thorneliu
As titled, is bRPC compatible with the Stream feature of gRPC Python client?
The main use case is similar to the SSE feature of ChatGPT, with the client accessing it being Python and using the Streaming mode.

**Comment by chenBright** [comment]
From what I understand, bRPC does not support gRPC streaming.
