### ISSUE TITLE
Used the free memory ??

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/brpc#2794]
Hi all,
This is Qianxin CodeSafe Team, we found a suspicious issue, where has used the free memory "kt"at
https://github.com/apache/brpc/blob/5cdf22f158722b3b11c7eabb7632690d719ccc4b/src/bthread/key.cpp#L240
but ,the memory already released at  
https://github.com/apache/brpc/blob/5cdf22f158722b3b11c7eabb7632690d719ccc4b/src/bthread/key.cpp#L239

**Comment by chenBright** [comment]
Here only the value of the kt pointer is used, not the memory it points to.

**Comment by QiAnXinCodeSafe** [comment]
Thank you for your reply
