### ISSUE TITLE
grpc是否可以使用连接池模式

### ISSUE THREAD

**Issue by WeiYan-Lynn** [apache/brpc#2809]
背景：当前我们环境的组网是，多个server上面接了一个elb,用来进行负载均衡以及对client屏蔽server节点的增删

在这种场景下，我们的服务即client，是通过链接elb来链接server的，因为当前brpc只支持单链接形式，所以即使初始化channel多次，也只建立一个到该elb 地址的链接，又因为是h2，只会在一个链接的基础上多路复用，所以elb只会对一个sever建立链接。

基于此，一个client实际只和一个sever进行了链接，其他server都处于空闲状态

诉求：是否可以通过多次初始化建立多个到相同地址的h2：grpc链接，或者支持连接池模式，

**Comment by chenBright** [comment]
> 是否可以通过多次初始化建立多个到相同地址的h2：grpc链接

设置不同的ChannelOptions::connection_group就可以使用不同的连接了。

**Comment by WeiYan-Lynn** [comment]
看代码这个是跟signature有关，感觉是可以的，但实测还是只建立了一个链接
以下是代码示例：
    auto channel = new brpc::Channel();
    brpc::ChannelOptions option;
    option.protocol = "h2:grpc";
    option.max_retry = 0;
    option.timeout_ms = timeout;
    option.connection_group = sceneIndex;
    channel->Init(url.c_str(), &option)

**Comment by chenBright** [comment]
只用了一个channel？

connection_group没问题的，可以通过内置服务connections页面确认一下有几个连接。

**Comment by WeiYan-Lynn** [comment]
可以了可以了，感谢
