### ISSUE TITLE
bthread::Mutex 和 bthread::butex 在使用上有啥区别吗

### ISSUE THREAD

**Issue by sikey647** [apache/brpc#2815]
在不同项目里看到分别有用bthread::Mutex和bthread::butex，这两者哪些区别，分别适合在哪些场景使用。

**Comment by yanglimingcn** [comment]
butex是很底层的源语言，类似于futex。Mutex类似于std::mutex，在开发过程中应该尽量使用Mutex这个层面的源语言。
