### ISSUE TITLE
add feature for bthread cpu time usage

### ISSUE THREAD

**Issue by icexin** [apache/brpc#2833]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
我期待在rpc服务端统计请求粒度的cpu使用时间，用于计算租户的cpu消耗，不能简单用qps这样的指标，因为不同的qps资源消耗不一样。

**Describe the solution you'd like (描述你期望的解决方法)**
类似线程有 `clock_gettime(CLOCK_THREAD_CPUTIME_ID, &ts)` 可以获取线程的真实cpu时间(不包括阻塞在系统调用)，希望bthread有类似的接口

**Comment by wwbmmm** [comment]
这个在百度内部是这样做的：bthread开放一个调度callback接口，用户可以设置一个callback函数，bthread每次切换的时候调用这个callback，用户可以自己在callback里统计cpu消耗，也可以做其它事情。

**Comment by chenBright** [comment]
之前在#1822 讨论过这个需求，看起来自定义callback不太满足这个需求：
1. 用户能知道第一次调度，但是不知道最后一次调度。
2. 用户需要熟悉bthread内部调度原理才能用好callback。

自定义callback结合#2851 中的bthread状态，应该会好用些。

https://github.com/apache/brpc/issues/1822#issuecomment-1202082072
> 考虑扩展一下bthread::TaskStatistics，加个cpu消耗的统计项，并且在bthread切换时更新该值。

我认为这个方案更合适。clock_gettime是系统调用，会影响bthread调度性能，所以在此方案的基础上补充两点：
1. 在bthread_attrflags_t加个开关，默认不统计纯cpu消耗。用户有需要可以通过bthread_attrflags_t启用该功能。
2. server bthread是由框架创建的，用户没法干预。在ServerOptions加上开关来启用该功能。

@wwbmmm 有什么建议吗？

**Comment by icexin** [comment]
我在内部分支写了一个版本，是通过动态flag控制的。主要是考虑到clock_gettime在获取thread cpu time的开销大概是200ns，常态开启会有一些影响，使用上可以接受类似pprof的开启一段时间，拿到数据后就不需要开启了。

具体实现是在调度器里面切换bthread的时候进行累加

**Comment by wwbmmm** [comment]
> 之前在#1822 讨论过这个需求，看起来自定义callback不太满足这个需求：
> 
> 1. 用户能知道第一次调度，但是不知道最后一次调度。
> 2. 用户需要熟悉bthread内部调度原理才能用好callback。
> 
> 自定义callback结合#2851 中的bthread状态，应该会好用些。
> 
> [#1822 (comment)](https://github.com/apache/brpc/issues/1822#issuecomment-1202082072)
> 
> > 考虑扩展一下bthread::TaskStatistics，加个cpu消耗的统计项，并且在bthread切换时更新该值。
> 
> 我认为这个方案更合适。clock_gettime是系统调用，会影响bthread调度性能，所以在此方案的基础上补充两点：
> 
> 1. 在bthread_attrflags_t加个开关，默认不统计纯cpu消耗。用户有需要可以通过bthread_attrflags_t启用该功能。
> 2. server bthread是由框架创建的，用户没法干预。通过ServerOptions/gflag来启用该功能。
> 
> @wwbmmm 有什么建议吗？

用户可能是想针对每一个请求获取具体的cpu时间，那么得给用户提供一个获取的接口，用户在执行完Server callback的最后调用这个接口，这个时候bthread实际上还没有结束。

不过，通过这种方式来统计请求消耗的cpu并不准确，因为请求相关的cpu计算并不仅仅发生在请求所在的那个bthread，还可能出现在其它后台线程、epoll线程、异步callback线程之中，这个取决于具体的业务逻辑。统计bthread的cpu时间只能提供一个参考。
