### ISSUE TITLE
brpc 客户端设置 connect 超时时间和 operate 超时时间一样的时候，当网络不可达的时候无法区分是连接超时还是请求操作超时

### ISSUE THREAD

**Issue by joke-lee** [apache/brpc#2836]
比如 curl 设置 connect 超时和 request 超时都是 1 秒的话，如果访问的地址比如是 10.0.0.1:8000 网络不可达（比如路由丢了），curl 会报 connect 超时
但是 brpc 都是报 reached timeout

![image](https://github.com/user-attachments/assets/cc5f225e-22ae-43fe-b501-28af3bc481de)

只有brpc 的 connect 超时设置 500ms，operate 超时设置 1 秒的时候访问 10.0.0.1:8000这样不可达的地址的时候 brpc 才会正常报 connection timeout 

![image](https://github.com/user-attachments/assets/8f914dc2-4bb0-451f-9282-8bc23d13c783)

希望客户端能够不要在 connect 超时和 request 超时设置一样的时候都是返回 read timeout，这样无法区分。

**Comment by wwbmmm** [comment]
把connect超时设置小一点就可以了。如果设置connect超时跟rpc超时一样，相当于connect超时是不生效的。
