### ISSUE TITLE
brpc redis怎么支持连接多个逻辑数据库

### ISSUE THREAD

**Issue by ufosky** [apache/brpc#476]
brpc的channel会根据ip和port组合合并连接，现在我的redis 服务器分了多个逻辑数据库，想要通过不同连接发送 SELECT 命令绑定不同的逻辑数据库，请问需要怎么实现？

**Comment by gydong** [comment]
你的问题是，尽管实例化了多个channel，但由于IP+port 是一样的，连接被重用了？

**Comment by ufosky** [comment]
@gydong 是的，由于连接被重用，我在一个 channel 里面发送`SELECT`命令选择了某个数据库，然后在另一个channel发送`SELECT`命令就会改掉之前channel选择的数据库

**Comment by gydong** [comment]
那你选择某个DB的依据是什么，说来听听。是上下文中携带DB号？

**Comment by ufosky** [comment]
@gydong 业务层调接口选择，数据是从配置文件中获取的

**Comment by ufosky** [comment]
可不可以给 Channel::Init 增加个参数标识这个这个channel底层连接复用的key，只有ip:port和key都相同才复用同一个连接

**Comment by gydong** [comment]
目前应该是不支持的哦

**Comment by ufosky** [comment]
应该可以直接在ChannelOptions上加

**Comment by ipconfigme** [comment]
为什么多个逻辑库的IP:Port相同呢？如果想连接不复用，可以使用POOLED和SHORT类型的连接

**Comment by ufosky** [comment]
POOLED并不是表示连接不复用吧，只是说由复用一个连接变成复用一个池子的连接，这样又怎么保证我从连接池取出来的那个连接刚好是我选择好的那个数据库的连接
SHORT连接连redis这个场景不太适合吧

**Comment by gydong** [comment]
因为redis提供的功能就是如此，逻辑库可以理解为namespace的概念。POOLED和SHORT都满足不了题主的需求。

**Comment by ipconfigme** [comment]
可以给SocketMap的key增加一个user_hint的string或者是int，这样相同endpoint的签名就不同了，类似不通的ssl证书

**Comment by gydong** [comment]
@ufosky  是说要修改brpc的源码才能支持吗？

**Comment by ufosky** [comment]
@gydong 是的，这也是一个比较通用的场景，只要一个连接里面带状态绑定的操作都会需要

**Comment by jamesge** [comment]
这个问题在增加client端ssl支持时遇到过了，目前client端对ssl的实现方式需要在SocketMapKey上传递一个很大的ChannelSSLOptions，以及不支持集群，也来自于没有解决好这个问题。
正确的方法就是如前几楼所言，应该把ChannelSSLOptions聚拢为统一的64-bit channel_signature，值由channel决定，相同的channel上下文应该产生相同的signature，不同的channel上下文应该产生极大概率不同的signature。这个signature也会传入NamingServiceThread，从而支持集群。
具体到redis的场景中，当有这个机制后，ChannelOptions中可以增加redis select相关的参数（可能就是个string），并影响到channel_signature的生成，从而让不同select配置的channel使用不同的连接。
具体到ssl的场景中，ssl_options会影响channel-signature，从而为不同的ssl_options建立不同的连接。但ssl-ctx并不在socketmap中生成，而是置于Socket.SharedPart中并按需建立。

**Comment by jamesge** [comment]
#482 中ChannelOptions中增加了connection_group
```
    // Channels with same connection_group share connections. In an another
    // word, set to a different value to not share connections.
    // Default: 0
    int connection_group;
```

**Comment by jamesge** [comment]
已merge入主干。connection_group的类型改为了string。对于这里的redis场景，可以针对不同的select命令设置不同的connection_group。

**Comment by wory117** [comment]
是不是可以用 redis pipeline，每个请求都用一次 AddCommand 设置一次逻辑数据库
