### ISSUE TITLE
支持pb3的arena分配

### ISSUE THREAD

**Issue by jamesge** [apache/brpc#535]
百度内很难动态判定pb的版本并进行相应的操作，这点在开源版中可以放开一些，使用宏或其他编译时的手段来处理。arena对于大request的分配和使用应该有一定的性能提升。

**Comment by gethinzhang** [comment]
目前看起来，是不是只要修改baidu_std_protocol里面New Message方法和Callback就可以了。还会有其他地方影响吗？

**Comment by jamesge** [comment]
应该没有其他地方了。之前的难点是怎么能同时兼容pb 2.x和3.x，这对于大型repo是个刚需（否则一个程序中可能会链入两个版本的brpc）。但对于小项目，编译时选项是ok的。

**Comment by gethinzhang** [comment]
好，我们内部先改一下试试，多谢

**Comment by feng-y** [comment]
这里是每个pv自己申请一个arena, pb 的message从这个arena上分配，pv 结束后再回收这个arena么？

**Comment by gxkevin** [comment]
这块目前有什么进展么，自己改的话需要改哪里 @gethinzhang

**Comment by huntinux** [comment]
尝试改了http协议里面的pb创建方式
