### ISSUE TITLE
brpc的baidu协议不支持catch异常，是处于什么考虑

### ISSUE THREAD

**Issue by hairet** [apache/brpc#681]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

现在有些业务调用一些底层库会抛异常，但是只有thrift等协议会catch,而如果是baidu协议，会一直回溯到完全无关的堆栈再coredump,不利于提示业务分析问题。
**Describe the solution you'd like (描述你期望的解决方法)**
想了解下这里不catch 异常的原因？

**Describe alternatives you've considered (描述你想到的折衷方案)**
暂时考虑在baidu协议里面自行cacth异常，log出来再 assert

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenBright** [comment]
#2256
