### ISSUE TITLE
使用bRPC client无法启动dummy server

### ISSUE THREAD

**Issue by raylinwu** [apache/brpc#703]
**Describe the bug (描述bug)**
server中使用bRPC 跟其他gRPC服务通信，在启动的bin目录
  echo 8090 >  dummy_server.port

netstat -anlp|grep 8090 没有端口监听

**To Reproduce (复现方法)**
可复现

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:CentOS Linux release 7.6.1810 (Core)
Compiler:gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
brpc:0.9.5
protobuf:3.6

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
