### ISSUE TITLE
rpc_press 压测时 proto中变量收不到数据？

### ISSUE THREAD

**Issue by LeungGeorge** [apache/brpc#713]
proto定义如下：
message MyRequest {
  required string my_type = 1;
  required bytes req_str = 2;
};

请问我执行 ./rpc_press  时，input中的json对应的字段 req_str该如何赋值？（这个字段对应得bytes转为字符串是一个json string） 
我现在使用下面两种方法都好使：
1.  json字符串（转以后）服务端收不到该字段；
2. 使用  json字符串（转以后） 对应的base64也收不到该字段；

**Comment by jamesge** [comment]
可以打开-http_verbose看看是否发出和收到对应的请求

**Comment by jamesge** [comment]
看看server端有无错误日志，以及可以试一些简单一些确认正确的base64字串
