### ISSUE TITLE
bthread_join  ret errno Sometimes 0 , Sometimes 11.

### ISSUE THREAD

**Issue by miniframework** [apache/brpc#739]
36 void* check_sleep() {
 46     while(true) {
 47       std::cout << "while" << std::endl;
 48       if (bthread_usleep(10) < 0) {
 49            if (errno == ESTOP) {
 50                std::cout << "ESTOP" << std::endl;
 51                break;
 52            }
 53            std::cout << "exit"<<std::endl;
 54            break;
 55       }
 56     }
 57 
 58     return NULL;
 59 }
 61 int main() {
 64     bthread_start_urgent(&th2, NULL,  check_sleep, (void*)0);
 84     sleep(1);
 85     bthread_stop(th2);
 87     int ret = bthread_join(th2, NULL);
 88     std::cout << "ret:" << errno << " " << strerror(errno) << std::endl;
}

output :
Sometimes：

while
while
while
ESTOP
ret:0 Success

----------------------------------------------
sometimes ：

while
while
while
ESTOP
ret:11 Resource temporarily unavailable

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
