### ISSUE TITLE
以同步调用的方式使用brpc thrift client，  当下游thrift服务端出现节点不可用的时候 ，task_group 线程组 会出现调度的极度不均匀

### ISSUE THREAD

**Issue by cauchy1988** [apache/brpc#743]
**Describe the bug (描述bug)**
brpc的大神们， 你们好；
最近使用brpc thrift-client 同步调用的功能， 服务A(暂时这么称呼)上线后， 发现：当下游的thrift 服务(暂时称作服务B)只要有一个节点出现重启或者down掉的时候 ， 服务A的latency迅速飚高，但仍然可用； 我自己通过观察后和试验后， 认为是task_control 线程组 调度的极不均匀造成的；

**To Reproduce (复现方法)**
1、模拟服务B: 使用简单的brpc自带的echo-thrift服务
2、模拟服务A: 程序创建多个pthread线程， 每个线程循环 以同步brpc thrift-client 的方式向B打请求(直接channel里只连接一台服务B就好)； 打开bvar_dump, 设置bvar_dump_file, 同时也打开show_per_worker_usage_in_vars （为了观察各个task_control线程的利用率）
3、首先观察一段时间的 bvar_dump_file里 各个task_control线程的利用率， 记录一下； 
4、重启服务B， 再观察一段时间的 bvar_dump_file里 各个task_control线程的利用率， 记录一下， 这个时候会发现某个task_control线程的usage基本占所有usage的100%
5、如果使用"半异步” 或者“纯异步” brpc thrift-client 就不会出现上述现象
**Expected behavior (期望行为)**
以同步调用的方式使用brpc thrift client，  当下游thrift服务端出现节点不可用的时候 ，task_group 线程组 的线程利用率分布和之前基本保持一致

**Versions (各种版本)**
OS:centos7
Compiler:g++ 4.8.5
brpc:master截止至今天的最新版
protobuf:3.5.1

**Additional context/screenshots (更多上下文/截图)**
![1555860614315](https://user-images.githubusercontent.com/7292411/56472164-bfa5ef00-648d-11e9-934d-b7a331285911.jpg)
![1555860608930](https://user-images.githubusercontent.com/7292411/56472168-c7659380-648d-11e9-8cf4-703511d40f52.jpg)

**Comment by cdjingit** [comment]
我们也在使用brpc thrift，用我们的服务试验了一下，没有复现这个问题。
试验的方法：iptables限制对某个(某几个)server节点的访问。

**Comment by cauchy1988** [comment]
> 我们也在使用brpc thrift，用我们的服务试验了一下，没有复现这个问题。
> 试验的方法：iptables限制对某个(某几个)server节点的访问。

也用的是“同步调用的方式”？

**Comment by cdjingit** [comment]
对的

**Comment by cauchy1988** [comment]
直接重启一台下游服务； 没有复现这个问题？  直接channel单连接一台下游服务试试；我昨天复现无数次了； 现在线上的服务改成半异步才好； 要不行我等下再试试； 然后整个程序包你也一起看看；

**Comment by kenshinxf** [comment]
> 直接重启一台下游服务； 没有复现这个问题？ 直接channel单连接一台下游服务试试；我昨天复现无数次了； 现在线上的服务改成半异步才好； 要不行我等下再试试； 然后整个程序包你也一起看看；

不太明白为啥channel连接下游一台服务器而不是下游集群， 这样的目的是？这样下游重启的时候，你的上游客户端岂不是都访问失败了？

**Comment by cauchy1988** [comment]
原因是这样的， 我们目前仍旧使用zookeeper作为服务发现的组件； 然后又没有针对brpc开发brpc的zookeeper服务发现插件； 所以目前比较low地用使用不同的channel 连不同的ip； 然后"服务发现”的逻辑我们自己在这层抽象上实现的： 比如发现某台服务失活了， 会erase掉对应的channel， 先这样理解吧； 确实不太好；

**Comment by cauchy1988** [comment]
> > 直接重启一台下游服务； 没有复现这个问题？ 直接channel单连接一台下游服务试试；我昨天复现无数次了； 现在线上的服务改成半异步才好； 要不行我等下再试试； 然后整个程序包你也一起看看；
> 
> 不太明白为啥channel连接下游一台服务器而不是下游集群， 这样的目的是？这样下游重启的时候，你的上游客户端岂不是都访问失败了？

原因是这样的， 我们目前仍旧使用zookeeper作为服务发现的组件； 然后又没有针对brpc开发brpc的zookeeper服务发现插件； 所以目前比较low地用使用不同的channel 连不同的ip； 然后"服务发现”的逻辑我们自己在这层抽象上实现的： 比如发现某台服务失活了， 会erase掉对应的channel， 先这样理解吧； 确实不太好；

**Comment by jamesge** [comment]
这个问题看起来和你们自研的“服务发现”逻辑有比较密切的关联。

**Comment by kenshinxf** [comment]
> > > 直接重启一台下游服务； 没有复现这个问题？ 直接channel单连接一台下游服务试试；我昨天复现无数次了； 现在线上的服务改成半异步才好； 要不行我等下再试试； 然后整个程序包你也一起看看；
> > 
> > 
> > 不太明白为啥channel连接下游一台服务器而不是下游集群， 这样的目的是？这样下游重启的时候，你的上游客户端岂不是都访问失败了？
> 
> 原因是这样的， 我们目前仍旧使用zookeeper作为服务发现的组件； 然后又没有针对brpc开发brpc的zookeeper服务发现插件； 所以目前比较low地用使用不同的channel 连不同的ip； 然后"服务发现”的逻辑我们自己在这层抽象上实现的： 比如发现某台服务失活了， 会erase掉对应的channel， 先这样理解吧； 确实不太好；

我说一下我们之前是怎么使用类似zk/etcd/consul/xxx服务发现的方案吧
brpc channel init的时候支持file类型的ip列表， 在ip列表有变化的时候brpc会自动更新， 所以我们就简单的在自己的服务里面启动一个获取ip列表的背景线程， 然后在有ip列表变化的时候更新那个文件（更新文件的时候要用mv的方式， 防止读写冲突）， 这样就和任意一个服务发现方式解耦了， 无论用那种服务发现最终都是调用获取ip接口，然后更新文件， 所以个人感觉brpc也没太大的必要集成各类服务发现

**Comment by SOSDAN** [comment]
重启同机部署的consul client之后，也出现了worker调度极不均衡的问题，服务可用但是失败率飙升。导致重启consul client之后必须重启连接consul client的服务，该服务才能恢复正常。用的是ConsulNamingService。

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
