### ISSUE TITLE
Redis client长时间超时无法恢复，只能重启

### ISSUE THREAD

**Issue by haolujun** [apache/brpc#744]
HI 大神：
    我在实际应用中，使用redis协议访问远程服务，会出现[E1008]Reached timeout=50ms @IP:PORT 错误，并且无法自动恢复，只能通过重启客户端所在的服务解决。 超时的时候只是客户端这面超时，服务端没有超时日志。并且，当时的客户端cpu，worker都没有用满。调用的是redis的 mget 命令，一次调用大概300个key。测试过key数目小的时候，超时是可以自己恢复的。当key数目大的时候，超时就无法恢复了。
18:52:41.589041    .     0 Requesting redis-server@IP:PORT redis log_id=0 call_id=25688199397437 trace=85eddf0ffb0c0072 span=4f3df8c7083b0072
18:52:41.589060    .    19 Requested(8745) [1]
18:52:41.639103    . 50043 [E1008]Reached timeout=50ms @IP:PORT
18:52:41.639119    .    16 Back to user's callsite

感觉应该是：当请求压力过大，导致brpc的某个地方出错，然后这个时候即使调低请求压力（1qps）brpc也一直恢复不了，一直报超时错误。因为我大qps下，网络请求数据量比较大，会不会导致某些缓冲区不足，造成了网络数据错误。

当把connection_type 改成 short后，就不会有超时错误了。

请教大神，这个问题有什么解决办法没有呀。

**Comment by gydong** [comment]
1、当时，connect_timeout设置的是多少ms？
2、当时，用命令行访问服务端，响应正常吗？

**Comment by haolujun** [comment]
> 1、当时，connect_timeout设置的是多少ms？
> 2、当时，用命令行访问服务端，响应正常吗？

50ms，1秒，都设置过，都超时。后来，把connection_type改成single或者pooled，就再也没有发现有超时错误。

**Comment by jamesge** [comment]
@haolujun 你的回复中对connection_type的描述是不是有些问题？

**Comment by haolujun** [comment]
多谢提醒，是描述的有问题。 是connection_type为single时，会出现超时。把connection_type改成short或者pooled后，就不会有超时现象了。

**Comment by jamesge** [comment]
怎么复现这个问题呢？持续地发那个"300个key“可以复现么？

**Comment by haolujun** [comment]
请求压力大些就可以复现，我这面压测的时候网络大概是200Mbps，基本上持续压上一段时间就会出现超时现象。

**Comment by jamesge** [comment]
这个redis-server是proxy还是什么，应该是single模式下流量都跑到一台redis-server上去了，而其他连接模式访问的是多台。这里的现象很可能就是压垮server端了。所谓“压垮”就是所有的请求都要在各层的buffer里排队，从而最终超时。这时候看client的cpu是没用的，brpc的redis client是多线程的，压死一个单线程redis-server是很轻松的。如果client是异步发请求（而同时向redis-server发起了很多的请求），可能性会更大一些。

**Comment by haolujun** [comment]
连接的是proxy，但是按照你的说法，那么出现超时的时候，此时redis-server是不可用的，但是我通过redis-cli连接这个proxy，各种命令畅通无阻。并且，重启redis-client进程，重新访问，立刻就不超时了。

**Comment by jamesge** [comment]
redis-cli，重启都不是走原来那个连接了吧。redis-server对于单个连接的处理速度未必很高

**Comment by haolujun** [comment]
重启之后，走的是新连接。但是如果这个时候不重启，我降低qps，由100qps降到1qps，依然会超时。

**Comment by jamesge** [comment]
你提供一份可复现的client代码，及详细的复现步骤吧。

**Comment by haolujun** [comment]
我这面复现步骤：
1: 每次mget 100个key，每个key的value大概为2K。
2: qps可以持续加大，可以一直加大到直到有超时错误，我这面大概是200qps。
3: 出现超时错误后，降低client的qps到1，这个时候依然会继续超时。

我这面的client是放在一个服务中的，所以我是通过控制请求该服务的qps，从而控制client请求redis-server的qps。

```
//redis_client.h
#ifndef REDIS_CLIENT_H
#define REDIS_CLIENT_H

#include <string>
#include <brpc/redis.h>
#include <brpc/channel.h>

class RedisClient {
public:
    RedisClient() {
        _channel.reset(new ::brpc::Channel());
    }

    //移动构造函数
    RedisClient(RedisClient&& client) = default;

    bool init(const std::string& ip, uint32_t port,
              uint32_t timeout_ms=1000, uint32_t max_retry=3);

    bool access_redis(const std::string& command,
                      ::brpc::RedisResponse& response);

    ~RedisClient() {}
private:

    std::unique_ptr<::brpc::Channel> _channel;
};
#endif
```

```
//redis_client.cpp
#include "redis_client.h"
#include <sstream>

bool RedisClient::init(const std::string& ip, uint32_t port,
                       uint32_t timeout_ms, uint32_t max_retry) {
    // Initialize the channel, NULL means using default options.
    ::brpc::ChannelOptions options;
    options.protocol = ::brpc::PROTOCOL_REDIS;
    // TODO magic
    options.timeout_ms = timeout_ms/*milliseconds*/;
    options.max_retry  = max_retry;
    options.connection_type = "single";  //改成pooled后，超时现象就会消失，非常神奇。
    std::stringstream ss;
    ss << ip << ":" << port;
    if (_channel->Init(ss.str().c_str(), &options) != 0) {
        LOG(ERROR) << "Fail to initialize channel";
        return false;
    }
    return true;
}

bool RedisClient::access_redis(const std::string& command,
                               ::brpc::RedisResponse& response) {
    ::brpc::RedisRequest request;
    if (!request.AddCommand(command.c_str())) {
        LOG(ERROR) << "Fail to add command";
        return false;
    }
    ::brpc::Controller cntl;
    _channel->CallMethod(NULL, &cntl, &request, &response, NULL);
    if (cntl.Failed()) {
        LOG(ERROR) << "Fail to access redis, " << cntl.ErrorText();
        return false;
    } else {
        return true;
    }
}
```

**Comment by yangkaiming666** [comment]
这个问题怎么解决的呢@haolujun

我这边也遇到这个问题，不过是偶发，并能自己恢复，我的并发比较高，QPS  15W 左右

**Comment by yangkaiming666** [comment]
百度的大神们帮忙解答一下吧。。。

**Comment by zhouqing910817** [comment]
我这边也是遇到redis client 报超时的问题，访问redis的qps 1.5k就会有出现大量超时同时也有访问成功的请求，经过排查不是redis server的问题，因为redis server端的监控没有耗时过长的请求，并且我这边的connection_type就是设置的pooled，求解答啊

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
