### ISSUE TITLE
brpc http client head请求问题

### ISSUE THREAD

**Issue by xinxinsh** [apache/brpc#764]
**Describe the bug (描述bug)**
利用brpc http client构建head请求，出现url链接不上Error [E1008]Reached timeout=30000ms ， 同样的url构建get是可以成功的，我用curl去构建head请求是可以的, 这个由于brpc构建head请求时， 如果返回的header的content-length不为0，在解析http响应时需要等待body读取，实际上head请求时不会返回body

**To Reproduce (复现方法)**
brpc http client构建head请求去访问， head请求返回时header包含content-length的返回， 但是content-length不为0

**Expected behavior (期望行为)**
brpc http client能处理head请求，对于head请求在处理http的返回时，即使响应的header里面的content-length不为0，也需要跳过响应的body的解析

**Versions (各种版本)**
OS: MacOs
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by lilithliu1** [comment]
这个问题有计划修复么

**Comment by shanghx** [comment]
这个修复后考虑合入master嘛？
