### ISSUE TITLE
brpc服务在ClosureGuard对象析构函数中coredump问题 Byte size calculation and serialization were inconsistent异常

### ISSUE THREAD

**Issue by tmqsoft** [apache/brpc#771]
HI 大神：
在构建一个brpc服务上线后 发现总是莫名的出现coredump 查看堆栈信息 进程core在ClosureGuard对象的析构函数里面 通过检查日志以及堆栈信息猜测 可能是业务代码抛出没有捕捉的异常导致 但是业务代码在捕捉异常之后 还是发生同样的coredump问题 
希望有遇到过类似问题的大神帮忙指点迷津 

部分core栈如下
![image](https://user-images.githubusercontent.com/50727007/57901451-dcb8bc80-7897-11e9-88b5-3989eab46abd.png)

每次core比出现的日志 怀疑是该问题引起 
[BaiduStreamingLogHandler] google/protobuf/message_lite.cc:71 CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation  and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification

**Comment by beforedream** [comment]
遇到了相同问题，请问下楼主已经解决吗

**Comment by beforedream** [comment]
我此前遇到这个问题的时候，是因为bool类型的数据，赋值时并非使用true/false，当时测试了10w+没有出现，后边又遇到这个了，这次就不晓得是什么原因

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
