### ISSUE TITLE
How to accepted files sent from http post ?

### ISSUE THREAD

**Issue by bidai541** [apache/brpc#774]
hi, Is there any way to accepted http post files by brpc?

```
# python client
requests.post(url=url, files=files, data=data)
```
I found nothing in brpc server size.
Looking forward to a reply！  thanks

**Comment by jamesge** [comment]
brpc servers do accept http post requests. You could turn on --http_verbose in the brpc server to see the http requests that it accepts.

**Comment by bidai541** [comment]
@jamesge  
Thank you for answering.
But how to convert request attachment into a [key,value]  pair similar to the previous one ? Does any  function that  can parse it?
