### ISSUE TITLE
controller偶尔报fatal（check failed:false,err code is 0）

### ISSUE THREAD

**Issue by szy441687879** [apache/brpc#814]
**Describe the bug (描述bug)**
在程序运行过程中，偶尔会出现brpc的fatal日志，调用栈如下
```
FATAL: 06-18 14:26:08:  baidu-rpc/src/baidu/rpc/controller.cpp:414] Check failed: false. error_code is 0
#0 0x0000018cbbde baidu::rpc::Controller::SetFailed()
#1 0x0000018cf808 baidu::rpc::Controller::HandleSocketFailed()
#2 0x000001a48ac3 bthread_id_error2_verbose()
#3 0x000001a48c77 bthread_id_error_verbose
#4 0x0000018ccfc4 baidu::rpc::Controller::DeleteStuff()
#5 0x0000018cf9f4 baidu::rpc::Controller::~Controller()
#9 0x0000015874f4 std::_Function_handler<>::_M_invoke()
#10 0x00000158741e std::_Function_handler<>::_M_invoke()
#11 0x0000014e446e std::__future_base::_State_base::_M_do_set()
#12 0x7f3db73f0973 __GI___pthread_once
#13 0x0000015877ea std::__future_base::_Task_state<>::_M_run()
#15 0x7f3db651a8a0 execute_native_thread_routine
#16 0x7f3db73eb1c3 start_thread
#17 0x7f3db5a7d12d __clone
```
大致的原因是controller析构的时候触发了_oncancel_id的回收,而_oncancel_id指向了另外一个rpc请求，也就预期外的cancel了一个rpc调用，可以同时看到一个不符合预期的访问失败日志如下， ErrorText是正常的，但是errcode为-1，和报错代码的处理逻辑match。而上次没有使用过NotifyOnCancel，因此oncancel_id不应该能够指向btread，也不应该会取消一个rpc请求，
`WARNING: 06-18 14:26:08:): call xxxx failed, ErrorCode=[-1], ErrorText[Success @xxxx:xxxx]
`
因此怀疑oncancel_id存在错乱的情况
**To Reproduce (复现方法)**
偶然发生，概率很低，无法稳定复现，但是触发fatal的controller是一个半同步调用，用法代码简化示例如下：
```
std::vector<std::shared_ptr<::baidu::rpc::Controller> > cntls;
for (int i = 0; i <= max; ++i) {
       cntls.push_back(std::make_shared<::baidu::rpc::Controller>());
}
for (int i = 0; i<= max; ++i) {
      stub.xxx(cntls[i].get(), &sub_requests[i], &sub_responses[i],
baidu::rpc::DoNothing());
 }
for (int i = 0; i<= max; ++i) {
     ::baidu::rpc::Join(cntls[i]->call_id());
}
for (int i = 0; i<= max; ++i) {
     if (cntls[i]->Failed()) {
    }else{
     }
}
```
**Expected behavior (期望行为)**
不应该去cancel一个不相关的bthread导致fatal并且一次rpc调用异常

**Versions (各种版本)**
OS: Centos
Compiler:gcc482
brpc:
protobuf:2-4-1

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
