### ISSUE TITLE
heap profile

### ISSUE THREAD

**Issue by fengliangwang** [apache/brpc#815]
heap profile获得调用信息，没有函数名都是地址怎么回事？

**Comment by zyearn** [comment]
这个问题暂时可以通过链接brpc的动态库解决

**Comment by jamesge** [comment]
系统版本是什么？ 看下 #608

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
