### ISSUE TITLE
为什么当传输double类型的数据的时候，和string比起来性能立马降低上十倍呢？

### ISSUE THREAD

**Issue by fishpenguin** [apache/brpc#842]
**Describe the bug (描述bug)**
同样的测试方法，同样大小的数据，传输double类型的数据的时候，要比传输string类型的数据慢十倍。即使是double类型数据需要序列化感觉性能也不会低这么多呀

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
有具体的schema么？另外你可以看下cpu profiler中的热点有何区别

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
