### ISSUE TITLE
bad performance for ParseFromCompressedData

### ISSUE THREAD

**Issue by gxkevin** [apache/brpc#852]
I have a performance problem when I using the brpc.
the detail is that:
    
    2019/07/23-20:07:08.314627 Received request(363037) from 10.70.1.105:38820 baidu_std     log_id=0 trace=192dcb7ef8fb4b8c span=bcaed61d10013381
    20:07:08.315041    .   414 Processing the request in a new bthread
    20:07:08.329446    . 14405 Enter bigo.pb3.rank.RankService.GetRankItems
    20:07:08.342318    . 12872 Requesting redis-server@10.70.1.103:19000 redis log_id=0 call_id=28071906275054 trace=192dcb7ef8fb4b8c span=bcaed61d10013382
    20:07:08.342337    .    19 Requested(62) [1]
    20:07:08.343101    .   764 Received response(40590) of request[1]
    20:07:08.343154    .    53 Processing the response in a new bthread
    20:07:08.343159    .     5 Back to user's callsite
    20:07:08.346688    .  3529 Requesting redis-server@10.70.1.103:19000 redis log_id=0 call_id=12343736037844 trace=192dcb7ef8fb4b8c span=abd375d94b1f34bc
    20:07:08.346717    .    29 Requested(48017) [1]
    20:07:08.348280    .  1563 Received response(6047) of request[1]
    20:07:08.348426    .   146 Processing the response in a new bthread
    20:07:08.348431    .     5 Back to user's callsite
    20:07:08.348642    .   211 Requesting redis-server@10.70.1.103:19000 redis log_id=0 call_id=15655155814872 trace=192dcb7ef8fb4b8c span=5072be9cdf8233e5
    20:07:08.348661    .    19 Requested(9280) [1]
    20:07:08.357212    .  8551 Received response(1039) of request[1]
    20:07:08.357277    .    65 Processing the response in a new bthread
    20:07:08.357282    .     5 Back to user's callsite
    20:07:08.375928    . 18646 Requesting redis-server@10.70.1.104:19000 redis log_id=0 call_id=34123515186521 trace=192dcb7ef8fb4b8c span=9d4d121f54e4355a
    20:07:08.375946    .    18 Requested(162) [1]
    20:07:08.376598    .   652 Received response(730) of request[1]
    20:07:08.376620    .    22 Processing the response in a new bthread
    20:07:08.376625    .     5 Back to user's callsite
    20:07:08.390983    . 14358 Leave bigo.pb3.rank.RankService.GetRankItems
    20:07:08.405965    . 14982 Responded(272653)

可以看到，除了时间消耗在redis上之外，还有大部分的时间消耗在Enter bigo.pb3.rank.RankService.GetRankItems、Leave bigo.pb3.rank.RankService.GetRankItems、Responded(272653)上面，通过vtune抓取的热点数据发现，有20%左右的时间消耗在了ParseFromCompressedData上面。

我想知道的是，Enter bigo.pb3.rank.RankService.GetRankItems、Leave bigo.pb3.rank.RankService.GetRankItems、Responded(272653)这三个阶段分别是干什么的，为什么这么耗时，是在做序列化和反序列化？有没有什么优化方式呢？

**Comment by zyearn** [comment]
这个数字代表的是当前事件和上一个事件的时间差，不是说花在“Enter bigo.pb3.rank.RankService.GetRankItems”的时间，而是“接受到数据“到”准备进入具体用户函数“之间的时间。具体看一下https://github.com/apache/incubator-brpc/blob/master/docs/cn/rpcz.md。

从你贴的图来看，Enter bigo.pb3.rank.RankService.GetRankItems前面的时间可能是ParseFromCompressedData占用比较多，看下req的解析时间是不是合理的。

Leave bigo.pb3.rank.RankService.GetRankItems时间长说明你的实现函数耗时比较长。

Responded之前会有压缩和序列化，对于兆级别的数据会达到毫秒级别。

**Comment by gxkevin** [comment]
也就是说，Leave bigo.pb3.rank.RankService.GetRankItems主要是GetRankItems这个函数本身的耗时？

**Comment by gxkevin** [comment]
request 360多K， response 270多K，感觉不算很大，解析却都需要十几ms，不知道是哪里出问题，用objectpool是不是会好一些

**Comment by jamesge** [comment]
看一下cpu热点吧，既然序列化和反序列化占据了显著的时间，应该在profiler中有一定的比例。

**Comment by gxkevin** [comment]
热点通过vtune抓了，时间占比26.9%左右 @jamesge @zyearn

    CPU Time
    1 of 101: 4.1% (0.940s of 23.005s)

    rerank ! tcmalloc::SLL_Next - [unknown source file]
    rerank ! tcmalloc::SLL_Pop + 0x25 - [unknown source file]
    rerank ! tcmalloc::ThreadCache::FreeList::Pop + 0x48 - [unknown source file]
    rerank ! tcmalloc::ThreadCache::Allocate + 0x88 - [unknown source file]
    rerank ! (anonymous namespace)::do_malloc_small + 0x8c - [unknown source file]
    rerank ! (anonymous namespace)::do_malloc + 0x3b - [unknown source file]
    rerank ! (anonymous namespace)::cpp_alloc + 0x1c - [unknown source file]
    rerank ! tc_new + 0x1c - [unknown source file]
    rerank ! google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>,   std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>,  std::allocator<char>>>::MapAllocator<google::protobuf::Map<std::__cxx11::basic_string<char,     std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>::InnerMap::Node>::allocate + 0x5e - map.h:208
    rerank ! google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>::InnerMap::Alloc<google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>::InnerMap::Node> + 0x4d - map.h:905
    rerank ! google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>::InnerMap::insert + 0xf8 - map.h:569
    rerank ! google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>::InnerMap::operator[] + 0x4e - map.h:598
     rerank ! google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>::operator[] + 0x26 - map.h:1048
    rerank ! google::protobuf::internal::MapEntryImpl<bigo::pb3::recommend::Item_PersonLabelsEntry_DoNotUse, google::protobuf::Message, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)9,   (int)0>::Parser<google::protobuf::internal::MapField<bigo::pb3::recommend::Item_PersonLabelsEntry_DoNotUse, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)9, (int)0>,   google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>,  std::allocator<char>>>>::MergePartialFromCodedStream + 0x1ee - map_entry_lite.h:358
    rerank ! google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual<google::protobuf::internal::MapEntryImpl<bigo::pb3::recommend::Item_PersonLabelsEntry_DoNotUse, google::protobuf::Message, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)9, (int)0>::Parser<google::protobuf::internal::MapField<bigo::pb3::recommend::Item_PersonLabelsEntry_DoNotUse, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)9, (int)0>, google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>> + 0x6e -  wire_format_lite_inl.h:493
    rerank ! bigo::pb3::recommend::Item::MergePartialFromCodedStream + 0x1892 - recommend.pb.cc:2567
    rerank ! google::protobuf::internal::WireFormatLite::ReadMessage + 0x79 - wire_format_lite_inl.h:447
    rerank ! bigo::pb3::rank::RankReq::MergePartialFromCodedStream + 0x36d - rank.pb.cc:594
    rerank ! google::protobuf::MessageLite::ParseFromCodedStream + 0x95 - [unknown source file] 
    rerank ! brpc::ParsePbFromZeroCopyStreamInlined + 0xbf - protocol.cpp:207
    rerank ! brpc::ParsePbFromIOBuf + 0x13 - protocol.cpp:218
    rerank ! brpc::ParseFromCompressedData + 0x72 - compress.cpp:82
    rerank ! brpc::policy::ProcessRpcRequest + 0x1082 - baidu_rpc_protocol.cpp:469
    rerank ! brpc::ProcessInputMessage + 0x6 - input_messenger.cpp:133
rerank ! brpc::RunLastMessage::operator() + 0x7 - input_messenger.cpp:139
rerank ! brpc::InputMessenger::OnNewMessages + 0x61c - input_messenger.cpp:214
rerank ! brpc::Socket::ProcessEvent + 0xc - socket.cpp:1070
rerank ! bthread::TaskGroup::task_runner + 0xc8 - task_group.cpp:293

**Comment by jamesge** [comment]
有常见的DAG图或是火焰图么？上面的调用栈看不到比例？另外也要排除一下优化相关的选项问题。

**Comment by gxkevin** [comment]
火焰图暂时还没抓@jamesge

**Comment by gxkevin** [comment]
火焰图如下附件

**Comment by gxkevin** [comment]
aa

**Comment by gxkevin** [comment]
@jamesge 
火焰图如附件

**Comment by gxkevin** [comment]
相关的flamegraph如下，ParseFromCompressedData 
确实占比较高
[perf-kernel.zip](https://github.com/apache/incubator-brpc/files/3459569/perf-kernel.zip)

**Comment by libratiger** [comment]
我也发现过这种情况，就是序列化和反序列化慢。我看了一下底层，都是调用的pb的反序列化，这个锅应该是pb的问题。

如果自己比较明确数据格式的画，可以尝试streaming rpc，这个里面没有调用Pb的反序列化，brpc会把IOBuf交给用户来处理。

但是brpc的streaming和grpc的差别好像很大，grpc不用改什么借口，但是brpc需要换成```StreamWrite```这些接口。这个文档也没有多说原因，如果能够补上会更好？@jamesge

**Comment by libratiger** [comment]
@gxkevin 你后来有其他的优化吗？

**Comment by hnwyllmm** [comment]
用map结构很难保证效率吧，repeated都还好，效率非常高

**Comment by libratiger** [comment]
@hnwyllmm 你有benchmark对比过吗？我觉得两者都快不了，不过从原理上理解，repeated应该是会快一点。

**Comment by hnwyllmm** [comment]
我们公司有一个序列化sdl，拿来跟pb对比过，列表模式性能pb稍快，map pb稍快。少量字段的数据结构，每秒百万最少的。所以你还是再考虑下map能不能优化掉。还有，用自己解析的二进制结构，不好做扩展，不过也看自己业务模式。

**Comment by jamesge** [comment]
@libratiger 
> 如果自己比较明确数据格式的画，可以尝试streaming rpc，这个里面没有调用Pb的反序列化，brpc会把IOBuf交给用户来处理。
碰到这种场景，一般用http + body是pb更合理一些，brpc中的streaming rpc是解决有序传输和处理问题，grpc层面的streaming目前brpc并不支持。

**Comment by libratiger** [comment]
> @libratiger
> 
> > 如果自己比较明确数据格式的画，可以尝试streaming rpc，这个里面没有调用Pb的反序列化，brpc会把IOBuf交给用户来处理。
> 
> 碰到这种场景，一般用http + body是pb更合理一些，brpc中的streaming rpc是解决有序传输和处理问题，grpc层面的streaming目前brpc并不支持。


嗯，我理解streaming rpc的设计不是干这个事的，但是我看如果把IOBuf交给用户来处理的画，应该是会比使用pb更加高效，可以减少反序列化的开销，尤其是用户自己知道格式的情况下。


btw: brpc有对pb, http+body这种的性能对比吗？
