### ISSUE TITLE
bthread_jump_fcontext 导致服务出core

### ISSUE THREAD

**Issue by hhhhhhhhik** [apache/brpc#873]
**Describe the bug (描述bug)**
服务运行一个月左右，目前出现一次coredump，没有复现，想问下，出现这种情况一般是什么问题导致？coredump的堆栈如下：
Program terminated with signal 7, Bus error.
#0  0x00000000006c4556 in bthread_jump_fcontext ()
(gdb) bt
#0  0x00000000006c4556 in bthread_jump_fcontext ()
Cannot access memory at address 0x300007ff8c9374e

**To Reproduce (复现方法)**
服务运行一个月，只出现一次，暂时没有复现

**Expected behavior (期望行为)**
正常运行，无core

**Versions (各种版本)**
OS:CentOS release 6.3 (Final)  内核 2.6.32_1-31-0-0
Compiler: gcc 4.8.2
brpc: 厂内stable版本
protobuf: 厂内stable依赖版本

**Additional context/screenshots (更多上下文/截图)**
dmesg中相关信息
![image](https://user-images.githubusercontent.com/3377227/62411646-db8e6480-b628-11e9-9ed6-037eb764527e.png)

**Comment by BillyJoy** [comment]
确认下，是否调用太深了，导致栈被覆盖了

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
