### ISSUE TITLE
cpu profiler无法显示图像

### ISSUE THREAD

**Issue by liziyangyang** [apache/brpc#923]
**Describe the bug (描述bug)**
如图，使用cpu profiler无法显示图像
![image](https://user-images.githubusercontent.com/15892914/65006449-aec2b200-d935-11e9-8e24-66928847ff92.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: ubuntu 16.04

Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

![image](https://user-images.githubusercontent.com/15892914/65006426-9bafe200-d935-11e9-9c0b-7abf22cb2df1.png)

**Comment by roczpwu** [comment]
顶，同遇到这个问题，请问解决了吗

**Comment by zhijunfu** [comment]
这个得看下那个perl脚本，它的逻辑是判断对应执行文件是否在当前目录，如果不在的话，就认为是remote。手动改下脚本就行了
