### ISSUE TITLE
tcpcopy拷贝流量时，brpc报错

### ISSUE THREAD

**Issue by dangding** [apache/brpc#930]
通过tcpcopy进行流量拷贝时，brpc服务报错如下：

`W0927 16:57:58.554148 101486 src/brpc/input_messenger.cpp:241] Close Socket{id=781684050597 fd=119 addr=192.168.2.254:44278:12353} (0x7fec080486d0) due to unknown message: \00\00......
`

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
