### ISSUE TITLE
BRPC crash when try to create thread id

### ISSUE THREAD

**Issue by imay** [apache/brpc#934]
**Describe the bug (描述bug)**

CHECK failed when brpc try to create id and lead process crash.

**To Reproduce (复现方法)**

No method to reproduce steadily. But it often appears when the system load is high.

**Expected behavior (期望行为)**

Don't crash the process

**Versions (各种版本)**
OS: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-862.el7.x86_64
Compiler: GCC 7.3.0
brpc: 0.9.5
protobuf: 3.5.1

**Additional context/screenshots (更多上下文/截图)**

Following is the message when the process crashed.

```
F1003 12:35:09.456410 19114 id.cpp:331] Check failed: meta->pending_q.empty() 
```

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
