### ISSUE TITLE
server端正常，但是客户端收到错误码

### ISSUE THREAD

**Issue by ilixiaocui** [apache/brpc#936]
在服务端正常的情况下，客户端首次请求收到110的错误，重试三次收到112的错误，这个问题要怎么排查？
E1005 11:24:48.301865 2170565 heartbeat.cpp:333] 10.198.136.138:8204 Fail to send heartbeat to MDS 10.198.136.132:6666, **cntl errorCode: 112** **cntl error: [E110]Fail to connect Socket{id=1042818
0601267 addr=10.198.136.132:6666:54198} (0x0x7fcd60068fc0): Connection timed out [R1][E112]Not connected to 10.198.136.132:6666 yet, server_id=10428180601267 [R2][E112]Not connected to 10.198
.136.132:6666 yet, server_id=10428180601267 [R3][E112]Not connected to 10.198.136.132:6666 yet, server_id=10428180601267**

**Comment by jamesge** [comment]
这个错误的表面原因是[连续3次](https://github.com/apache/incubator-brpc/blob/fc07b7bf45c4b2aa90ae5c832f3b48a8da124640/src/brpc/socket.cpp#L93)rpc超时触发熔断，client会对那个server[每隔3秒](https://github.com/apache/incubator-brpc/blob/fc07b7bf45c4b2aa90ae5c832f3b48a8da124640/src/brpc/socket_map.cpp#L35)做健康检查，直到连上或机器被移除为止。这个功能的动机是防止持续访问频繁失联的机器。"连续3次超时"还是比较强的限制，只要中间任何一次成功了，就会从头算起，如果觉得这个还松，可以继续调大。调到很大的数值就相当于取消了这个功能。

**Comment by MaggieCui** [comment]
> 这个错误的表面原因是[连续3次](https://github.com/apache/incubator-brpc/blob/fc07b7bf45c4b2aa90ae5c832f3b48a8da124640/src/brpc/socket.cpp#L93)rpc超时触发熔断，client会对那个server[每隔3秒](https://github.com/apache/incubator-brpc/blob/fc07b7bf45c4b2aa90ae5c832f3b48a8da124640/src/brpc/socket_map.cpp#L35)做健康检查，直到连上或机器被移除为止。这个功能的动机是防止持续访问频繁失联的机器。"连续3次超时"还是比较强的限制，只要中间任何一次成功了，就会从头算起，如果觉得这个还松，可以继续调大。调到很大的数值就相当于取消了这个功能。

有疑问的地方在于server端是正常提供服务的，其他rpc请求都正常响应，这个rpc偶尔会出现这种错误。这个原因要怎么排查呢？

**Comment by jamesge** [comment]
检查下日志中是否有连续的Connection timed out

**Comment by MaggieCui** [comment]
> 检查下日志中是否有连续的Connection timed out

没有连续的。偶尔出现一下，我们这边是每隔10s发送一次，本次失败，下次就成功了

**Comment by jamesge** [comment]
用的什么负载均衡方式？

**Comment by MaggieCui** [comment]
没有负载均衡。我们是一个分布式存储系统，由元数据节点mds和各存储节点组成。各存储节点每隔10s向mds发送心跳。假期期间发现某些存储节点发送心跳偶尔出现失败的情况，且失败的errcode和text都相同。查看metric发现mds的实际实用的线程数量较小，cpu压力也很小，按道理来说不会出现超时的情况

**Comment by jamesge** [comment]
mds只是一台机器，client通过ip去访问它么？如果是这样的话，只能解释为，mds偶尔断线导致的健康检查，下面日志中应该有Checking开头，指向10.198.136.132:6666的内容

**Comment by MaggieCui** [comment]
> mds只是一台机器，client通过ip去访问它么？如果是这样的话，只能解释为，mds偶尔断线导致的健康检查，下面日志中应该有Checking开头，指向10.198.136.132:6666的内容

1. checking开头的相关日志是在存储节点日志中还是mds中？
2. 看了存储节点的metric, 发现在timeout的时候存储节点上的load或者cpu或者读写延迟会飙高一下，这会不会导致这种错误的产生？

**Comment by jamesge** [comment]
1. 存储节点
2. 有可能。client端由于cpu不足而得不到及时运行也可能导致超时

**Comment by MaggieCui** [comment]
> 1. 存储节点
> 2. 有可能。client端由于cpu不足而得不到及时运行也可能导致超时

> 1. 存储节点
> 2. 有可能。client端由于cpu不足而得不到及时运行也可能导致超时

没有找到checking相关的日志

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.

**Comment by johndb2016** [comment]
@ilixiaocui 后面咋解决的，不用brpc了么？
