### ISSUE TITLE
/proc/self/io: Fail to fscanf: Permission denied

### ISSUE THREAD

**Issue by wu-hanqing** [apache/brpc#944]
**Describe the bug (描述bug)**
日志中经常出现 bvar/default_variables.cpp:442] Fail to fscanf: Permission denied，1s一次

**To Reproduce (复现方法)**
我们为qemu提供了一个block driver，在使用的时候会出现上面的日志。

**Expected behavior (期望行为)**
看了一下对应的代码，奇怪的是可以打开/proc/self/io，但是在后续fscanf的时候提示没有权限。
#788 是一个比较类似的，他们的情况是打开的时候就提示无权限。

现在期望能定位一下问题，或者，能不能把这个功能`read_proc_io`暂时屏蔽了。

**Versions (各种版本)**
OS: debian7(3.10)
Compiler: gcc-4,9
brpc: 0.9.6
protobuf: 2.4.1

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/10327590/67463334-d236f600-f673-11e9-854f-3dcc16299937.png)

**Comment by jamesge** [comment]
可能和格式有关，导致fscanf失败，可以贴一下io文件的内容，看看是怎么对不上的

**Comment by BeautyCJ** [comment]
请问，是否已经解决了这个问题？

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
