### ISSUE TITLE
cpu利用率低，服务超时

### ISSUE THREAD

**Issue by wzw921026** [apache/brpc#948]
**Describe the bug (描述bug)**
cpu还剩50%，qps上不去，压力变高延时随之也变高，这种应该怎么追查和优化？

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
bthread_worker_usage 多大？看起来是有锁阻塞。

**Comment by wzw921026** [comment]
bthread_worker_count : 49

bthread_worker_usage : 33.0149

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.
