### ISSUE TITLE
0.96 release WRR负载均衡分配的QPS不均匀

### ISSUE THREAD

**Issue by cool-colo** [apache/brpc#986]
**Describe the bug (描述bug)**
0.96 release WRR负载均衡分配的QPS不均匀
老版本正常的，新版就经常出现下游QPS不均匀的问题。
新版平时波动也比老版本大， 偶尔出非常大的波动（上线，或qps高峰期经常出现） 

**To Reproduce (复现方法)**
1. brpc做client 发http请求
2. 负载均衡为WRR
3. IP列表为list形式， 100+下游机器

**Expected behavior (期望行为)**
下游QPS分布均匀

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**
096版本出问题时候的qps截图
<img width="866" alt="屏幕快照 2019-12-05 下午9 05 41" src="https://user-images.githubusercontent.com/20718701/70237946-3258a600-17a3-11ea-947d-bf227f43f167.png">

回滚到1年以前的版本恢复正常
<img width="688" alt="屏幕快照 2019-12-05 下午9 09 06" src="https://user-images.githubusercontent.com/20718701/70238083-89f71180-17a3-11ea-9f49-aeeb21685ca4.png">

**Comment by cdjingit** [comment]
首先，用list naming service不好配置tag 设置权重吧。
有详细能复现这个问题的场景吗？比如权重怎么配置的，用的什么连接方式等等。越详细越好便于定位问题。

**Comment by cool-colo** [comment]
> 首先，用list naming service不好配置tag 设置权重吧。
> 能详细描述复现这个问题的场景配置吗？比如权重怎么配置的，用的什么连接方式等等。越详细越好便于定位问题。

list://10.2.14.131:5555 10,10.2.14.132:5555 10,10.2.14.133:5555 10,10.2.14.134:5555 10,10.2.14.158:5555 10,10.2.14.160:5555 10,10.2.14.161:5555 10,10.2.14.163:5555 10,10.2.14.162:5555 10,10.2.12.142:5555 10,10.2.14.164:5555 10,10.2.15.1:5555 10,10.2.15.2:5555 10,10.2.15.3:5555 10
权重配置就像上面这样， 有100+机器，其中一台机器权重为1，其余权重全为10,

其它参数
load_balancer: "wrr"
max_retry: 0
connection_type: ""
protocol_type: 1
backup_request_ms: -1
connect_timeout_ms: 500
timeout_ms: 500

**Comment by cdjingit** [comment]
> > 首先，用list naming service不好配置tag 设置权重吧。
> > 能详细描述复现这个问题的场景配置吗？比如权重怎么配置的，用的什么连接方式等等。越详细越好便于定位问题。
> 
> list://10.2.14.131:5555 10,10.2.14.132:5555 10,10.2.14.133:5555 10,10.2.14.134:5555 10,10.2.14.158:5555 10,10.2.14.160:5555 10,10.2.14.161:5555 10,10.2.14.163:5555 10,10.2.14.162:5555 10,10.2.12.142:5555 10,10.2.14.164:5555 10,10.2.15.1:5555 10,10.2.15.2:5555 10,10.2.15.3:5555 10
> 权重配置就像上面这样， 有100+机器，其中一台机器权重为1，其余权重全为10,
> 
> 其它参数
> load_balancer: "wrr"
> max_retry: 0
> connection_type: ""
> protocol_type: 1
> backup_request_ms: -1
> connect_timeout_ms: 500
> timeout_ms: 500

看你的qps记录 是运行一段时间出现了这个问题？我们自己的所有服务都在用wrr的形式，brpc版本也是刚同步过社区的最新版，唯一区别用的是file名字服务。目前没有发现qps不均的情况。我尝试复现一下吧。用example/下的demo类子尝试复现成功过吗？其他协议是否也有类似问题？

**Comment by one0320heart** [comment]
每个地址可以附带一个tag，在常见的命名服务中，如果地址后有空格，则空格之后的内容均为tag。 相同的地址配合不同的tag被认为是不同的实例，brpc会建立不同的连接。用户可利用这个特性更灵活地控制与单个地址的连接方式。 如果你需要"带权重的轮询"，你应当优先考虑使用wrr算法，而不是用tag来模拟。
---------------------------------------------------------------
我理解你这个ip:port+空格 后面的这个数字，我理解应该是tag，而不是你理解的权重
但是如何配置wrr，貌似文档中也没有给出来

**Comment by seahime** [comment]
> ## 每个地址可以附带一个tag，在常见的命名服务中，如果地址后有空格，则空格之后的内容均为tag。 相同的地址配合不同的tag被认为是不同的实例，brpc会建立不同的连接。用户可利用这个特性更灵活地控制与单个地址的连接方式。 如果你需要"带权重的轮询"，你应当优先考虑使用wrr算法，而不是用tag来模拟。
> 我理解你这个ip:port+空格 后面的这个数字，我理解应该是tag，而不是你理解的权重
> 但是如何配置wrr，貌似文档中也没有给出来

同意你的理解，我读文档时也是这样理解的。
但是我刚刚使用 example/echo_c++ 中的代码做测试时（仅更改client.cpp中 init channele），发现实际是如下的情况：
在形如 `ip:port tag` 的配置写法下，无论是 list 还是 file naming service，tag 都被 wrr 算法当成权重处理了。

附实验：
三个 server 进程，端口和tag分别为：
> 8001 2
> 8002 3
> 8003 5
client echo 100 次 ，结果三个 servers 承担的请求数量分别为 20、30、50

**Comment by cdjingit** [comment]
wrr lb会把tag解读成权重。

**Comment by serverglen** [comment]
可以使用wr(weighted random) load balancer试试
